type ScreenHelp = { title: string; description: string }

const screenTopics: Record<string, ScreenHelp> = {
  Overview: { title: 'Business overview', description: 'Use the cards and totals to choose a task or review recent business activity. A card may open setup when that workspace has no records yet; it does not create a sale.' },
  POS: { title: 'Product sales', description: 'Add stocked products, review quantities and the total, then record the payment received. A completed sale saves a receipt and deducts stock. Hold saves an unpaid basket for later; it does not complete the sale.' },
  Oil: { title: 'Oil sales', description: 'Select oil products and enter the quantity in each product’s saved base unit, or use a configured container. Review customer or bulk pricing and stock availability before recording payment. Completing the sale saves a receipt and deducts the equivalent base-unit stock.' },
  Payments: { title: 'Payments & receipts', description: 'Enter what the customer is paying for, the quantity, unit price and payment method, then save the receipt. These descriptions do not deduct product stock. Use Jobs & invoices for estimates, work progress, deposits and balances.' },
  Counter: { title: 'Order counter', description: 'Build an order from the saved menu, set quantities and extras, then choose whether to take payment now or send it for preparation. Preparation progress is tracked separately from payment. Recipes consume ingredients when preparation starts; linked packaged goods deduct stock when paid.' },
  Restaurant: { title: 'Tables & tabs', description: 'Open a table or named tab, add order rounds and seats, then track preparation and serving. Bills can be settled by whole bill, seat or selected items. Recipes and linked packaged goods consume stock when preparation starts.' },
  RetailOrders: { title: 'Online orders', description: 'Review customer-submitted goods orders, check stock and fulfilment details, and accept an order on one till while connected. Acceptance assigns that till to the order; synchronize to share updates. Food orders are handled in Order counter or Tables & tabs.' },
  Register: { title: 'Cash register', description: 'Open a shift with the counted starting cash, record cash in or out with a reason, then close by entering the counted amount. Review the expected-versus-counted difference before saving the close.' },
  Inventory: { title: 'Inventory', description: 'Use this area to find products and manage stock records. Add or import products with their actual units, costs, prices and opening quantities. Receiving, transfers, stock counts and price changes have their own workflows; a product list entry alone does not record a supplier delivery.' },
  Stocktake: { title: 'Stock count', description: 'Count the physical quantity for the selected products and compare it with the expected stock. Save a draft while counting; review the differences and enter a reason before approval because approval updates stock.' },
  Movements: { title: 'Stock movements', description: 'Review recorded stock increases and reductions, including their reasons and references. Use the matching action—receiving, transfer, adjustment, wastage or sale—to create a movement rather than editing this history.' },
  Wallet: { title: 'Customer accounts', description: 'Find a customer to review contact details and account balance. Deposits and repayments add prepaid value or reduce debt; withdrawals remove prepaid value. These account movements are separate from a sale receipt.' },
  Team: { title: 'Staff & access', description: 'Manage staff accounts and the screens each person may use. Assign only the permissions needed for their role. Disabling a business workspace does not erase the saved staff permission choices.' },
  Sales: { title: 'Sales history', description: 'Search saved receipts and transactions, inspect payment evidence, and use the available return or reconciliation actions. A voided item and a refund are separate records; check the transaction history before retrying an uncertain action.' },
  Reports: { title: 'Reports', description: 'Choose the report or date period you need and read totals in the business reporting timezone. Reports summarize saved records; they do not replace receipt, stock or cash-register corrections.' },
  Owner: { title: 'Business performance', description: 'Review the business-level sales, stock and cost summary. Open the detailed reports when you need a date range or transaction list; estimates depend on recorded purchase costs and expenses.' },
  Activity: { title: 'Staff activity', description: 'Choose a date range and staff member to review recorded sales, expenses and item voids. The page reports saved activity; it does not show every unsaved basket or draft.' },
  Settings: { title: 'Business settings', description: 'Choose the settings area before changing configuration. Workspace, business and payment settings affect the business; printer and device settings apply to the current checkout device. Save changes and synchronize to share them.' },
  Device: { title: 'Printers & devices', description: 'Configure the hardware attached to this checkout device and use the available test or pairing controls to confirm it works. Device settings do not automatically configure other tills.' },
  Sync: { title: 'Sync issues', description: 'Review each rejected or conflicting change, compare the local and accepted versions, then choose the appropriate resolution. Synchronize after resolving an issue; do not repeat a payment or stock action just because its sync result is delayed.' },
  Display: { title: 'Customer display', description: 'Pair a customer-facing device to show the current basket and completed-sale confirmation. The paired view is read-only and expires; it cannot add items or take payment.' },
  Subscription: { title: 'Subscription', description: 'Review the current plan, access status and available renewal actions. If selling access has expired, renew here; business records, reports and settings remain available.' },
  Account: { title: 'Close business account', description: 'This area starts a permanent account-closure request. Read the displayed retention period and confirmation steps carefully before submitting.' },
  Guide: { title: 'How to use Stockroom', description: 'Choose a topic from the guide. For a quick explanation of the current operational screen, return to it and select Help for this screen.' },
}

const sectionTopics: Record<string, ScreenHelp> = {
  'add-search': { title: 'Add or search product', description: 'Search the existing catalogue or start a product entry. Enter the product name and selling unit, then review barcode, cost, price, opening stock and reorder level before saving. A barcode lookup is a suggestion; verify the product and pack size.' },
  'new-product': { title: 'Add product', description: 'Enter one distinct item and its actual unit, cost, selling price and current stock. Use a manufacturer barcode only when it belongs to this exact product and pack size. Saving adds a catalogue record; it does not create a supplier receipt.' },
  purchasing: { title: 'Purchasing & suppliers', description: 'Use a supplier order to track what was requested, then receive only the quantities that arrived. Check unit conversion, batch cost and expiry where applicable. Recording a supplier payment settles the supplier balance; it is not a second expense.' },
  transfers: { title: 'Transfer stock between branches', description: 'Choose a product, active destination branch, quantity and reason. The transfer records a reduction at this branch and a matching increase at the destination; synchronize both branches to share it.' },
  import: { title: 'Import products', description: 'Upload a catalogue file, map its columns and review proposed rows before saving. Match existing products by barcode or SKU where possible, and verify unit, cost, price and quantity; importing a catalogue must not be treated as receiving new stock.' },
  'import-csv': { title: 'Import CSV', description: 'Choose a CSV under 20 MB. The first row supplies column names; match each field, then load up to 2,000 product rows for review. Name, SKU, barcode, category, unit, price, cost, stock and reorder point can be mapped. Existing barcode or SKU matches are skipped by default and keep their saved details.' },
  'import-barcode': { title: 'Find by barcode', description: 'Scan or enter the barcode on the product. Stockroom checks food, household and personal-care catalogues, then drug and medical-device registries when available. A catalogue name is a starting point for your product upload: edit it to match the product in your hand, then enter your own price, cost and stock.' },
  'import-photo': { title: 'Read product photo', description: 'Use a clear JPG, PNG or WebP image up to 15 MB. Choose a single package label or a supplier list. The app extracts suggested details; review and correct them before saving.' },
  'import-reference': { title: 'Find saved reference', description: 'Search reference products saved for this business on this device. A reference provides product details for review, but does not create inventory or change stock.' },
  'import-save-reference': { title: 'Save offline references', description: 'Save names, barcodes, categories and units from the mapped CSV for future barcode or name lookup on this device. This does not add inventory products, prices or stock.' },
  'import-review': { title: 'Review imported products', description: 'Check each proposed name, SKU, barcode, category, unit, cost, price and opening quantity. Select valid rows to save. Existing product stock is preserved; importing a catalogue is not receiving a supplier delivery.' },
  pricing: { title: 'Product prices and packs', description: 'Select a product and enter price tiers or customer-specific rates using the saved base stock unit. Configure pack conversions separately. Review how thresholds apply to the combined quantity before saving.' },
  expiry: { title: 'Expiring stock', description: 'Review batches by expiry date and quantity. This screen helps prioritize stock; it does not automatically remove expired goods. Record disposal or wastage through the stock action provided.' },
  starters: { title: 'Catalogue starters', description: 'Browse the full starter list for this business type, search by name, category or unit, and select the products you sell. Saving creates product records with the suggested name, category and unit plus an automatically generated SKU. Barcodes stay blank because they depend on the exact product pack. Set actual price, cost and opening stock afterward.' },
  options: { title: 'Product variants and extras', description: 'Group existing products into variants or add optional priced extras for checkout. Confirm that each variant has the correct stock record; extras do not consume ingredient stock automatically.' },
  handwritten: { title: 'Product list or form import', description: 'Upload a catalogue image or completed product form, review each extracted field and correct uncertain text. Nothing is saved until you confirm the reviewed product details.' },
  'sales-receipt-history': { title: 'Receipt history', description: 'Find a saved receipt to view, print or share it. Reprinting does not make another sale. If a receipt is missing, refresh or synchronize before retrying the original payment.' },
  'sales-payment-evidence': { title: 'Payment evidence', description: 'Compare saved payment references and evidence with the corresponding transaction. A reference or image is supporting information; staff still confirm that external funds were received.' },
  'sales-reconciliation': { title: 'Match payments', description: 'Compare imported provider or bank entries with saved receipts, then mark only verified matches. Reconciliation records a match; it does not charge the customer or create a sale.' },
  'sales-void-history': { title: 'Voided items', description: 'Review item removals and their recorded reasons. A void does not necessarily refund an already paid receipt; use the return workflow when money must be returned.' },
  'new-customer': { title: 'Add customer', description: 'Enter the customer’s name and optional phone number, then save. Use the customer account afterward to record a deposit, repayment or withdrawal; do not use those actions to record a sale.' },
  birthdays: { title: 'Customer birthdays', description: 'Review upcoming birthdays and each customer’s reminder preference. Birthday reminders do not alter the customer account or create a transaction.' },
  expenses: { title: 'Expenses', description: 'Review saved operating expenses. Supplier purchases that remain in stock belong in Purchasing, while rent, transport and utilities belong here. Do not record the same cost in both places.' },
  'new-expense': { title: 'Record expense', description: 'Choose a category, describe what was paid for, enter the amount and date incurred, then save. Record the real operating cost once; supplier payments and stock purchases follow Purchasing.' },
  'stock-report': { title: 'Stock report', description: 'Review stock quantities, valuation and alerts for the selected branch. Values depend on saved product costs and batch records; use Inventory or stock workflows to correct the underlying records.' },
  'team-add-staff': { title: 'Add staff', description: 'Enter the staff member’s identity and sign-in details, then assign role and screen permissions. Share credentials securely and confirm the staff member can sign in before they operate a till.' },
  'team-members': { title: 'Staff and permissions', description: 'Choose a staff member to review their role, branch and screen access. Changes affect future access; disabling a screen does not delete the person’s saved permission choices.' },
  links: { title: 'Staff sign-in links', description: 'Copy the business-specific link for staff to open on their own device, then have them sign in using their own account. The link identifies the business and is not a password.' },
}

export function screenHelpFor(screen: string, section = '', settingsTab = '', paymentTab = ''): ScreenHelp {
  if (screen === 'Settings') {
    if (settingsTab === 'shop') return { title: 'Workspaces and timezone', description: 'Choose the business type and which separate selling screens the business uses. Save workspace changes, then synchronize other devices. The reporting timezone controls report dates; it does not change transaction timestamps.' }
    if (settingsTab === 'sales') return { title: 'Sales settings', description: 'These controls set shared checkout rules such as tax, discounts, loyalty and payment behavior. Review the effect on each enabled sales screen before saving.' }
    if (settingsTab === 'food') return { title: 'Food menu and recipes', description: 'Configure menu names, prices, availability and recipes. Recipes describe the ingredients for one prepared portion and are consumed when preparation starts.' }
    if (settingsTab === 'restaurant') return { title: 'Restaurant menu and tables', description: 'Configure restaurant offerings and table/seat layout. Save menu and table changes before staff use them for open bills.' }
    if (settingsTab === 'receipts') return { title: 'Receipt settings', description: 'Choose the business details and receipt content shown on saved transactions. Settings affect new receipts; older receipts retain their saved details.' }
    if (settingsTab === 'devices') return screenTopics.Device
    return screenTopics.Settings
  }
  if (screen === 'Payments' && paymentTab) {
    if (paymentTab === 'Service catalogue') return { title: 'Service catalogue', description: 'Add or edit reusable service names and prices for payments and jobs. These entries do not change stock; add service details and prices to each transaction as needed.' }
    if (paymentTab.includes('Job')) return { title: 'Jobs and invoices', description: 'Create an estimate or issue an invoice for described work, then record job stages and deposits or balance payments. An estimate is not a sale; issue it before collecting invoice payment.' }
    if (paymentTab.toLowerCase().includes('history')) return { title: 'Payment history', description: 'Review saved payment receipts and their payment details. Use the receipt actions to print or share; creating a new payment is a separate action.' }
  }
  return sectionTopics[section] || screenTopics[screen] || { title: 'Current screen', description: 'Review the labels and current records on this screen before saving. If the page is for setup, save its settings before returning to daily work.' }
}
