import { createServer } from 'node:http'
import { chromium } from '@playwright/test'
import { spawn } from 'node:child_process'
import { mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { once } from 'node:events'
import assert from 'node:assert/strict'

const data = await mkdtemp(join(tmpdir(), 'stockroom-counter-browser-'))
const base = 'http://127.0.0.1:9467'
const cloud = createServer(async (request, response) => {
  response.setHeader('Content-Type', 'application/json')
  if (request.url === '/v1/sync/capabilities') { response.end(JSON.stringify({ capabilities: ['counter-v3'] })); return }
  if (request.url.startsWith('/v1/sync/push')) {
    let raw = ''; for await (const chunk of request) raw += chunk
    response.end(JSON.stringify({ acceptedOperationIds: JSON.parse(raw).operations.map(row => row.operationId), conflicts: [] })); return
  }
  if (request.url.startsWith('/v1/sync/pull')) { response.end(JSON.stringify({ operations: [], cursor: '' })); return }
  response.end(JSON.stringify({ businessId: 'counter-test', testMode: true }))
})
await new Promise(resolve => cloud.listen(9469, '127.0.0.1', resolve))
const child = spawn(process.execPath, ['server/index.mjs'], { env: { ...process.env, PORT: '9467', CUSTOMER_DISPLAY_PORT: '9468', STOCKROOM_DATA_DIR: data, SYNC_CONFIG_PATH: join(data, 'sync.json'), SYNC_API_URL: 'http://127.0.0.1:9469', SYNC_DEVICE_TOKEN: 'test', BUSINESS_ID: 'counter-test', DEVICE_ID: 'counter-device' }, stdio: 'ignore' })
let browser
try {
  for (let n = 0; n < 100; n++) { try { if ((await fetch(base + '/api/health')).ok) break } catch {} await new Promise(resolve => setTimeout(resolve, 100)) }
  const account = await (await fetch(base + '/api/setup', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ appName: 'Corner Shop', ownerName: 'Owner', email: 'counter@test.local', password: 'long-test-password' }) })).json()
  const headers = { 'Content-Type': 'application/json', Authorization: `Bearer ${account.token}` }
  const drink = await (await fetch(base + '/api/products', { method: 'POST', headers, body: JSON.stringify({ name: 'Bottled juice', price: 3, category: 'Drinks', sku: 'JUICE', stock: 8, reorder: 1, cost: 1, unit: 'bottle' }) })).json()
  assert.equal((await fetch(base + '/api/pos/counter', { headers })).status, 400)
  browser = await chromium.launch({ channel: 'msedge', headless: true })
  const page = await browser.newPage({ viewport: { width: 1366, height: 900 } })
  const errors = []; page.on('pageerror', error => errors.push(error.message))
  await page.route('**/*', route => route.request().url().startsWith(base) ? route.continue() : route.abort())
  await page.route('**/api/subscriptions/access', route => route.fulfill({ json: { testMode: true, blocked: false, status: 'test' } }))
  await page.addInitScript(account => { localStorage.setItem('stockroom-token', account.token); localStorage.setItem('stockroom-user', JSON.stringify(account.user)) }, account)
  await page.goto(base)
  await page.getByRole('button', { name: 'Stock & checkout', exact: true }).waitFor()
  assert.equal(await page.getByRole('button', { name: 'Fast food', exact: true }).count(), 0)
  await page.getByRole('button', { name: 'Business settings', exact: true }).click()
  await page.getByRole('button', { name: 'Workspaces', exact: true }).click()
  await page.getByLabel('Payment screens', { exact: true }).selectOption('fast-food')
  await page.getByRole('button', { name: 'Save payment screens', exact: true }).click()
  await page.getByText('Payment screens saved. Use Sync now to share this choice with your other devices.', { exact: true }).waitFor()
  await page.getByRole('button', { name: 'Fast food', exact: true }).click()
  const workspace = page.locator('.counter-workspace')
  await workspace.getByRole('heading', { name: 'Fast food workspace', exact: true }).waitFor()
  assert.equal(await page.getByRole('button', { name: 'Stock & checkout', exact: true }).count(), 0)
  assert.equal(await page.getByRole('heading', { name: 'Basket', exact: true }).count(), 0)
  assert.equal(await workspace.getByRole('heading',{name:'Choose menu items',exact:true}).count(),1)
  assert.equal(await workspace.getByRole('button',{name:'Menu',exact:true}).count(),0)
  assert.equal(await workspace.getByRole('button',{name:'Setup',exact:true}).count(),0)
  await page.getByRole('button',{name:'Business settings',exact:true}).click()
  await page.getByRole('button',{name:'Food menu & recipes',exact:true}).click()
  await page.getByRole('button',{name:'Business settings',exact:true}).click()
  await page.getByRole('button',{name:'Food menu & recipes',exact:true}).click()
  await workspace.getByRole('button', { name: 'Packaged stock', exact: true }).click()
  await workspace.getByLabel('Packaged product name', { exact: true }).fill('Bottled water')
  await workspace.getByLabel('Packaged selling price', { exact: true }).fill('3')
  await workspace.getByLabel('Purchase cost per item', { exact: true }).fill('1')
  await workspace.getByLabel('Opening packaged stock', { exact: true }).fill('4')
  await workspace.getByRole('button', { name: 'Add packaged product', exact: true }).click()
  await workspace.getByText('Packaged product saved. Link it to a menu item.', { exact: true }).waitFor()
  const stockRow = workspace.locator('form.customer-row').filter({ hasText: 'Bottled water' })
  await stockRow.getByLabel('Add stock', { exact: true }).fill('2')
  await stockRow.getByRole('button', { name: 'Restock', exact: true }).click()
  await stockRow.getByText('Bottled water — 6 in stock', { exact: true }).waitFor()
  assert.equal((await (await fetch(base + '/api/products', { headers })).json()).products.find(row => row.name === 'Bottled water').stock, 6)
  await page.getByRole('button',{name:'Business settings',exact:true}).click()
  await page.getByRole('button',{name:'Food menu & recipes',exact:true}).click()
  await workspace.getByRole('button', { name: 'Menu', exact: true }).click()
  await workspace.getByRole('button', { name: 'Add menu item', exact: true }).click()
  const groups = workspace.locator('.counter-menu-editor .submission-fields > fieldset')
  await groups.nth(0).getByLabel('Menu item name', { exact: true }).fill('Burger')
  await groups.nth(0).getByLabel('Menu price', { exact: true }).fill('10')
  await groups.nth(0).getByRole('button', { name: 'Add option or extra', exact: true }).click()
  await groups.nth(0).getByLabel('Option name', { exact: true }).fill('Cheese')
  await groups.nth(0).getByLabel('Extra price', { exact: true }).fill('2')
  await workspace.getByRole('button', { name: 'Add menu item', exact: true }).click()
  await groups.nth(1).getByLabel('Menu item name', { exact: true }).fill('Juice')
  await groups.nth(1).getByLabel('Menu price', { exact: true }).fill('3')
  await groups.nth(1).getByLabel('Offering type', { exact: true }).selectOption('stock')
  await groups.nth(1).getByLabel('Linked stock product', { exact: true }).selectOption(drink.id)
  await workspace.getByRole('button', { name: 'Save menu', exact: true }).click()
  await workspace.getByText('Menu saved.', { exact: true }).waitFor()
  await page.getByRole('button',{name:'Business settings',exact:true}).click()
  await page.getByRole('button',{name:'Food menu & recipes',exact:true}).click()
  await workspace.getByRole('button', { name: 'Recipes', exact: true }).click()
  await workspace.getByText('Ingredient stock', { exact: true }).click()
  for (const ingredient of [{ name: 'Flour', unit: 'kg', cost: '4', stock: '10' }, { name: 'Cheese ingredient', unit: 'piece', cost: '0.5', stock: '10' }]) {
    await workspace.getByLabel('Ingredient name', { exact: true }).fill(ingredient.name)
    await workspace.getByLabel('Stock unit', { exact: true }).selectOption(ingredient.unit)
    await workspace.getByLabel('Purchase cost per stock unit', { exact: true }).fill(ingredient.cost)
    await workspace.getByLabel('Opening ingredient stock', { exact: true }).fill(ingredient.stock)
    await workspace.getByRole('button', { name: 'Add ingredient', exact: true }).click()
    await workspace.getByText('Ingredient saved. Add it to a recipe.', { exact: true }).waitFor()
    await page.waitForFunction(() => document.querySelector('.counter-workspace input[name="name"]')?.value === '')
  }
  const ingredients = (await (await fetch(base + '/api/products', { headers })).json()).products
  const flour = ingredients.find(row => row.name === 'Flour'), cheese = ingredients.find(row => row.name === 'Cheese ingredient')
  await workspace.getByLabel('Restock Flour (kg)', { exact: true }).fill('0.5')
  await workspace.getByLabel('Restock Flour (kg)', { exact: true }).locator('..').locator('..').getByRole('button', { name: 'Restock ingredient', exact: true }).click()
  await workspace.getByText('Ingredient stock updated.', { exact: true }).waitFor()
  const burgerMenu = (await (await fetch(base + '/api/pos/counter', { headers })).json()).menu
  await workspace.getByLabel('Prepared menu item', { exact: true }).selectOption(burgerMenu.items[0].id)
  await workspace.getByRole('button', { name: 'Add recipe ingredient', exact: true }).first().click()
  await workspace.getByLabel('Ingredient', { exact: true }).first().selectOption(flour.id)
  await workspace.getByLabel('Quantity per portion', { exact: true }).first().fill('0.1')
  await workspace.getByText('Cheese: extra ingredients', { exact: true }).click()
  await workspace.getByRole('button', { name: 'Add recipe ingredient', exact: true }).last().click()
  await workspace.getByLabel('Ingredient', { exact: true }).last().selectOption(cheese.id)
  await workspace.getByLabel('Quantity per portion', { exact: true }).last().fill('1')
  await workspace.getByRole('button', { name: 'Save recipe', exact: true }).click()
  await workspace.getByText('Recipe saved. Existing orders keep their original ingredients.', { exact: true }).waitFor()

  await page.getByRole('button',{name:'Fast food',exact:true}).click()
  await workspace.getByRole('button', { name: 'New order', exact: true }).click()
  await workspace.getByRole('button', { name: /^Burger/ }).click()
  await workspace.getByLabel(/Cheese/).check()
  await workspace.getByLabel('Quantity', { exact: true }).fill('2')
  await workspace.getByRole('button', { name: 'Add to order', exact: true }).click()
  await workspace.getByRole('button', { name: /^Juice/ }).click()
  await workspace.getByRole('button', { name: 'Add to order', exact: true }).click()
  await workspace.getByLabel('Preparation note (optional)', { exact: true }).fill('No onions')
  await page.reload()
  await workspace.getByLabel('Preparation note (optional)', { exact: true }).waitFor()
  assert.equal(await workspace.getByLabel('Preparation note (optional)', { exact: true }).inputValue(), 'No onions')
  await workspace.getByRole('button', { name: 'Send and take payment', exact: true }).click()
  await workspace.getByRole('heading',{name:/Payment for order/}).waitFor()
  await workspace.getByRole('heading', { name: 'Open orders', exact: true }).waitFor()
  assert.match(await workspace.locator('.counter-order').textContent(), /Queued.*Unpaid/)
  assert.equal((await (await fetch(base + '/api/products', { headers })).json()).products.find(row => row.id === drink.id).stock, 8)
  await page.getByRole('button',{name:'Fast food',exact:true}).click()
  await workspace.getByRole('button', { name: 'Preparation', exact: true }).click()
  assert.equal(await workspace.getByRole('button', { name: 'Take payment', exact: true }).count(), 0)
  await workspace.getByRole('button', { name: 'Start preparing', exact: true }).click()
  await workspace.getByRole('button', { name: 'Mark ready', exact: true }).waitFor()
  const afterPreparation = (await (await fetch(base + '/api/products', { headers })).json()).products
  assert.equal(afterPreparation.find(row => row.id === flour.id).stock, 10.3)
  assert.equal(afterPreparation.find(row => row.id === cheese.id).stock, 8)
  assert.match(await workspace.locator('.counter-order').textContent(), /Ingredient cost used:.*1.80/)

  await workspace.getByRole('button', { name: 'Mark ready', exact: true }).click()
  assert.equal(await workspace.getByRole('button', { name: 'Hand over', exact: true }).isDisabled(), true)
  await page.getByRole('button',{name:'Fast food',exact:true}).click()
  await workspace.getByRole('button', { name: 'Orders', exact: true }).click()
  await workspace.getByRole('button', { name: 'Take payment', exact: true }).click()
  await workspace.getByLabel('Order cash received', { exact: true }).fill('30')
  await workspace.getByRole('button', { name: 'Save order payment', exact: true }).click()
  await workspace.getByRole('heading', { name: 'Order payment saved', exact: true }).waitFor()
  assert.equal((await (await fetch(base + '/api/products', { headers })).json()).products.find(row => row.id === drink.id).stock, 7)
  await page.evaluate(() => { window.print = () => { window.counterReceipt = document.querySelector('.print-receipt').textContent } })
  await workspace.getByRole('button', { name: 'Print receipt', exact: true }).last().click()
  await page.waitForFunction(() => typeof window.counterReceipt === 'string')
  assert.match(await page.evaluate(() => window.counterReceipt), /Order:.*Burger \/ Cheese.*Juice.*Change given:/)
  await workspace.getByRole('button', { name: 'Hand over', exact: true }).click()
  await workspace.getByText('No open orders.', { exact: true }).waitFor()
  await page.reload()
  await page.getByRole('button',{name:'Fast food',exact:true}).click()
  await workspace.getByRole('button', { name: 'Orders', exact: true }).click()
  await workspace.getByText('Collected orders (1)', { exact: true }).waitFor()
  await workspace.getByText('Collected orders (1)', { exact: true }).click()
  await workspace.getByRole('button', { name: 'Refund order', exact: true }).click()
  await workspace.getByLabel('Refund reason', { exact: true }).fill('Customer returned the order')
  await workspace.getByLabel('Return this packaged item to stock', { exact: true }).check()
  await workspace.getByRole('button', { name: 'Save refund', exact: true }).click()
  await workspace.getByText('Refund saved. A fully refunded open order can now be cancelled.', { exact: true }).waitFor()
  assert.equal((await (await fetch(base + '/api/products', { headers })).json()).products.find(row => row.id === drink.id).stock, 8)
  await page.getByRole('button',{name:'Business settings',exact:true}).click()
  await page.getByRole('button',{name:'Food menu & recipes',exact:true}).click()
  await workspace.getByRole('button', { name: 'Menu', exact: true }).click()
  await workspace.getByText('Tax and rewards settings', { exact: true }).click()
  await workspace.getByRole('button', { name: 'Edit tax and rewards', exact: true }).click()
  await workspace.getByLabel('Calculate tax', { exact: true }).check()
  await workspace.getByLabel('Tax rate (%)', { exact: true }).fill('10')
  await workspace.getByRole('button', { name: 'Save tax and rewards', exact: true }).click()
  await workspace.getByText('Tax and rewards settings saved. Existing orders keep their saved totals.', { exact: true }).waitFor()
  await page.getByRole('button',{name:'Fast food',exact:true}).click()
  await workspace.getByRole('button', { name: 'New order', exact: true }).click()
  await workspace.getByRole('button', { name: /^Burger/ }).click()
  await workspace.getByRole('button', { name: 'Add to order', exact: true }).click()
  await workspace.getByText('Discount', { exact: true }).click()
  await workspace.getByLabel('Discount value', { exact: true }).fill('1')
  await workspace.getByRole('button', { name: 'Send for preparation', exact: true }).click()
  await workspace.getByRole('button', { name: 'Correct order', exact: true }).click()
  await workspace.getByLabel('Correction reason', { exact: true }).fill('Customer requested extra burger')
  await workspace.getByRole('button', { name: /^Burger/ }).click()
  await workspace.getByRole('button', { name: 'Add to order', exact: true }).click()
  await workspace.getByRole('button', { name: 'Save correction', exact: true }).click()
  await workspace.getByRole('heading', { name: 'Open orders', exact: true }).waitFor()
  assert.match(await workspace.locator('.counter-order').textContent(), /20.90/)
  await page.evaluate(() => { window.print = () => { window.counterTicket = document.querySelector('.print-order').textContent } })
  await workspace.getByRole('button', { name: 'Print preparation ticket', exact: true }).click()
  await page.waitForFunction(() => typeof window.counterTicket === 'string')
  assert.match(await page.evaluate(() => window.counterTicket), /PREPARATION TICKET.*Burger/)
  await workspace.getByRole('button', { name: 'Cancel order', exact: true }).click()
  await workspace.getByLabel('Cancellation reason', { exact: true }).fill('Customer changed their mind')
  await workspace.getByRole('button', { name: 'Confirm cancellation', exact: true }).click()
  await workspace.getByText('Order cancelled. Its history is retained.', { exact: true }).waitFor()
  await workspace.getByText('Cancelled orders', { exact: true }).waitFor()
  const finalIngredients = (await (await fetch(base + '/api/products', { headers })).json()).products
  assert.equal(finalIngredients.find(row => row.id === flour.id).stock, 10.3, 'refund and unprepared cancellation cannot alter consumed ingredients')
  const reports = await (await fetch(base + '/api/reports', { headers })).json()
  assert.equal(reports.profit.ingredientCost, 1.8)
  assert.equal(reports.profit.amount, -1.8)

  await page.setViewportSize({ width: 390, height: 844 })
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)
  await page.setViewportSize({ width: 1366, height: 900 })
  await page.getByRole('button', { name: 'Business settings', exact: true }).click()
  await page.getByRole('button', { name: 'Workspaces', exact: true }).click()
  await page.getByLabel('Payment screens', { exact: true }).selectOption('both')
  await page.getByRole('button', { name: 'Save payment screens', exact: true }).click()
  await page.getByText('Payment screens saved. Use Sync now to share this choice with your other devices.', { exact: true }).waitFor()
  await page.getByRole('button', { name: 'Stock & checkout', exact: true }).click()
  await page.getByRole('heading', { name: 'Basket', exact: true }).waitFor()
  assert.equal(await workspace.count(), 0, 'fast-food controls must not render inside retail checkout')
  await page.getByRole('button', { name: 'Fast food', exact: true }).click()
  await page.getByRole('button',{name:'Fast food',exact:true}).click()
  await workspace.getByRole('button', { name: 'Orders', exact: true }).click()
  await workspace.getByText('Collected orders (1)', { exact: true }).waitFor()
  assert.deepEqual(errors, [])
  console.log('PASS: isolated workspace, menu/options, draft reload, saved preparation stages, linked payment, stock, tax, discounts, correction, cancellation, refunds, recipes, ingredient costs and printing')
} finally {
  await browser?.close()
  if (child.exitCode === null) { child.kill(); await once(child, 'exit') }
  await new Promise(resolve => cloud.close(resolve))
  await rm(data, { recursive: true, force: true })
}
