import { chromium } from '@playwright/test'
import { spawn } from 'node:child_process'
import { mkdtemp, mkdir } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import assert from 'node:assert/strict'
import { normalizeShopProfile } from '../server/shop-profile.mjs'
import { createServer } from 'node:http'

const data = await mkdtemp(join(tmpdir(), 'stockroom-empty-screens-'))
const base = 'http://127.0.0.1:9577'
const cloud=createServer(async(request,response)=>{
  response.setHeader('Content-Type','application/json')
  if(request.url==='/v1/sync/capabilities') return response.end(JSON.stringify({capabilities:['counter-v3','restaurant-v1']}))
  if(request.url.startsWith('/v1/sync/pull')) return response.end(JSON.stringify({operations:[],cursor:''}))
  if(request.url.startsWith('/v1/sync/push')) { let raw='';for await(const chunk of request) raw+=chunk;return response.end(JSON.stringify({acceptedOperationIds:JSON.parse(raw).operations.map(row=>row.operationId),conflicts:[]})) }
  response.end(JSON.stringify({businessId:'empty-test',testMode:true}))
})
await new Promise(resolve=>cloud.listen(9579,'127.0.0.1',resolve))
const child = spawn(process.execPath, ['server/index.mjs'], { env: { ...process.env, PORT:'9577', CUSTOMER_DISPLAY_PORT:'9578', STOCKROOM_DATA_DIR:data, SYNC_CONFIG_PATH:join(data,'sync.json'), SYNC_API_URL:'http://127.0.0.1:9579', SYNC_DEVICE_TOKEN:'test', BUSINESS_ID:'empty-test', DEVICE_ID:'empty-device' }, stdio:'ignore', windowsHide:true })
let browser
try {
  for(let i=0;i<100;i++) { try { if((await fetch(base+'/api/health')).ok) break } catch {} await new Promise(resolve=>setTimeout(resolve,100)) }
  const account=await (await fetch(base+'/api/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({appName:'My new business',ownerName:'Owner',email:'empty@test.local',password:'long-test-password'})})).json()
  assert.ok(account.token)
  browser=await chromium.launch({channel:'msedge',headless:true})
  const page=await browser.newPage({viewport:{width:390,height:844}})
  const errors=[]; page.on('pageerror',error=>errors.push(error.message))
  await page.route('**/*',route=>route.request().url().startsWith(base)?route.continue():route.abort())
  await page.route('**/api/subscriptions/access',route=>route.fulfill({json:{testMode:true,blocked:false,status:'test'}}))
  await page.addInitScript(account=>{localStorage.setItem('stockroom-token',account.token);localStorage.setItem('stockroom-user',JSON.stringify(account.user));localStorage.setItem(`stockroom-active-screen:${account.user.organizationId}:${account.user.id}`,'Overview')},account)
  await mkdir('docs/screenshots',{recursive:true})
  async function screen(name,title) {
    await page.goto(base+'/?screen='+name)
    await page.getByRole('heading',{name:title,exact:true}).waitFor({timeout:30000})
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${name} overflows`)
  }
  await screen('Overview','Ready for your first transaction')
  assert.equal(await page.getByText('Inventory snapshot',{exact:true}).count(),0)
  await page.screenshot({path:'docs/screenshots/fresh-overview.png',fullPage:true})
  await screen('Inventory','No products yet')
  assert.equal(await page.getByRole('heading',{name:'Transfer stock between branches'}).count(),0)
  assert.equal(await page.getByRole('heading',{name:'Stock costs and expiry'}).count(),0)
  await page.screenshot({path:'docs/screenshots/fresh-inventory.png',fullPage:true})
  await page.getByLabel('Choose screen').selectOption('purchasing')
  await page.getByRole('heading',{name:'No supplies recorded'}).waitFor()
  await page.goBack()
  await page.getByRole('heading',{name:'No products yet'}).waitFor()
  await page.goForward()
  await page.getByRole('heading',{name:'No supplies recorded'}).waitFor()
  await page.reload()
  await page.getByRole('heading',{name:'No supplies recorded'}).waitFor()
  assert.equal(await page.getByRole('button',{name:'Add supplier',exact:true}).count(),0)
  await page.screenshot({path:'docs/screenshots/fresh-supplies.png',fullPage:true})
  await page.getByLabel('Supply screen').selectOption('suppliers')
  await page.getByRole('heading',{name:'No suppliers yet'}).waitFor()
  await page.getByRole('button',{name:'Add supplier',exact:true}).click()
  await page.getByLabel('Supplier name',{exact:true}).fill('First supplier')
  await page.getByLabel('Choose screen').selectOption('products')
  await page.getByRole('heading',{name:'No products yet'}).waitFor()
  await page.getByLabel('Choose screen').selectOption('purchasing')
  assert.equal(await page.getByLabel('Supplier name',{exact:true}).inputValue(),'First supplier')
  await page.getByRole('button',{name:'Add supplier',exact:true}).click()
  await page.getByLabel('Supply screen').selectOption('suppliers')
  await page.getByText('First supplier',{exact:true}).waitFor()
  await screen('Sales','No receipts yet')
  assert.equal(await page.getByRole('heading',{name:'Voided order items'}).count(),0)
  await page.screenshot({path:'docs/screenshots/fresh-receipts.png',fullPage:true})
  await screen('Wallet','No customers yet')
  assert.equal(await page.getByRole('button',{name:'Save birthday'}).count(),0)
  await page.getByRole('button',{name:'Add customer',exact:true}).click()
  await page.getByLabel('Customer name',{exact:true}).fill('First customer')
  await page.getByRole('button',{name:'Add customer',exact:true}).click()
  await page.getByLabel('Choose screen').selectOption('customers')
  await page.getByText('First customer',{exact:true}).first().waitFor()
  await screen('Reports','No sales to report yet')
  assert.equal(await page.getByRole('button',{name:'Save expense'}).count(),0)
  await page.getByLabel('Choose screen').selectOption('new-expense')
  await page.getByRole('button',{name:'Save expense'}).waitFor()
  await screen('Movements','No stock movements yet')
  await page.goto(base+'/?screen=Team')
  await page.getByRole('heading',{name:'Current team',exact:true}).waitFor()
  assert.equal(await page.getByRole('button',{name:/Create account/}).count(),0)
  await page.getByLabel('Choose screen').selectOption('team-add-staff')
  await page.getByRole('heading',{name:'Add team member',exact:true}).waitFor()
  assert.equal(await page.getByRole('heading',{name:'Current team',exact:true}).count(),0)
  await page.goto(base+'/?screen=Settings')
  await page.getByLabel('Choose screen').selectOption('payment-methods')
  assert.equal(await page.getByLabel('App name',{exact:false}).count(),0)
  assert.equal(await page.getByRole('heading',{name:'Shop branches',exact:true}).count(),0)
  await page.getByLabel('Choose screen').selectOption('identity')
  await page.getByRole('button',{name:/Save business settings/}).waitFor()
  const headers={'Content-Type':'application/json',Authorization:`Bearer ${account.token}`}
  const settings=await (await fetch(base+'/api/settings',{headers})).json()
  const savedProfile=await fetch(base+'/api/settings/shop-profile',{method:'PUT',headers,body:JSON.stringify({...normalizeShopProfile(settings.shopProfile),fastFood:true,restaurant:true})})
  assert.equal(savedProfile.ok,true,await savedProfile.text())
  await screen('Counter','Your menu is empty')
  assert.equal(await page.getByRole('button',{name:'Send for preparation',exact:true}).count(),0)
  await page.screenshot({path:'docs/screenshots/fresh-counter.png',fullPage:true})
  await page.getByLabel('Order screen').selectOption('Orders')
  await page.getByRole('heading',{name:'No open orders',exact:true}).waitFor()
  await page.getByLabel('Order screen').selectOption('Preparation')
  await page.getByRole('heading',{name:'Nothing waiting for preparation',exact:true}).waitFor()
  await screen('Restaurant','No tables or tabs yet')
  await page.screenshot({path:'docs/screenshots/fresh-tables.png',fullPage:true})
  await screen('Stocktake','No stock count started')
  await page.screenshot({path:'docs/screenshots/fresh-stock-count.png',fullPage:true})
  await page.getByRole('button',{name:'Open navigation menu'}).click()
  await page.waitForFunction(()=>document.querySelector('#business-navigation').getBoundingClientRect().right<=innerWidth+1)
  assert.equal(await page.locator('#business-navigation').evaluate(el=>el.getBoundingClientRect().right<=innerWidth+1),true)
  await page.screenshot({path:'docs/screenshots/navigation-menu.png',fullPage:true})
  await page.getByRole('button',{name:'Close navigation menu',exact:true}).first().click()
  await page.setViewportSize({width:1280,height:900})
  await screen('Inventory','No products yet')
  assert.equal(await page.locator('#business-navigation').getAttribute('inert'),null)
  assert.equal(await page.getByRole('button',{name:'Open navigation menu'}).isVisible(),false)
  await page.screenshot({path:'docs/screenshots/desktop-inventory.png',fullPage:true})
  const product=await fetch(base+'/api/products',{method:'POST',headers,body:JSON.stringify({name:'Orange juice',price:15,category:'Drinks',sku:'JUICE',stock:20,reorder:2,cost:3,unit:'piece'})})
  assert.equal(product.ok,true)
  await page.goto(base+'/?screen=Reports')
  await page.getByText('Stock valuation',{exact:true}).waitFor()
  assert.equal(await page.getByRole('heading',{name:'No sales to report yet'}).count(),0)
  await page.goto(base+'/?screen=POS')
  await page.getByRole('button',{name:/Add Orange juice/}).click()
  await page.getByRole('button',{name:/Take payment/}).click()
  const payment=page.locator('#pos-payment')
  await payment.getByLabel('Payment Method',{exact:true}).selectOption('cash')
  await payment.getByLabel('Cash received',{exact:true}).fill('20')
  await payment.getByText('Change to give: $5.00',{exact:true}).waitFor()
  const [saleResponse]=await Promise.all([
    page.waitForResponse(response=>response.url().endsWith('/api/sales') && response.request().method()==='POST'),
    payment.getByRole('button',{name:'Complete sale',exact:true}).click(),
  ])
  assert.equal(saleResponse.ok(),true,await saleResponse.text())
  await page.goto(base+'/?screen=Sales')
  await page.getByRole('button',{name:'Reprint receipt',exact:true}).waitFor()
  assert.equal(await page.getByRole('heading',{name:'No receipts yet'}).count(),0)
  const entry=await browser.newPage({viewport:{width:390,height:844}})
  await entry.route('**/*',route=>route.request().url().startsWith(base)?route.continue():route.abort())
  await entry.route('**/api/subscriptions/access',route=>route.fulfill({json:{testMode:true,blocked:false,status:'test'}}))
  await entry.goto(base)
  await entry.getByRole('button',{name:'Skip introduction',exact:true}).click()
  await entry.getByLabel('Owner email or staff username').fill('empty@test.local')
  await entry.getByLabel('Password',{exact:true}).fill('long-test-password')
  let branchFailures=1
  await entry.route('**/api/branches',route=>branchFailures-->0?route.fulfill({status:503,json:{error:'Branches temporarily unavailable'}}):route.continue())
  await entry.getByRole('button',{name:'Sign in',exact:true}).click()
  await entry.getByRole('heading',{name:'Choose your branch',exact:true}).waitFor()
  await entry.getByText('Branches temporarily unavailable',{exact:true}).waitFor()
  assert.equal(await entry.getByRole('button',{name:'Continue to your business'}).isDisabled(),true)
  await entry.getByRole('button',{name:'Retry loading branches'}).click()
  await entry.getByRole('button',{name:'Continue to your business'}).waitFor()
  await entry.waitForFunction(()=>!document.querySelector('.login-button')?.disabled)
  await entry.screenshot({path:'docs/screenshots/entry-branch.png',fullPage:true})
  await entry.getByRole('button',{name:'Continue to your business'}).click()
  await entry.locator('.app-shell').waitFor()
  const setup=await browser.newPage({viewport:{width:390,height:844}})
  await setup.route('**/*',route=>route.request().url().startsWith(base)?route.continue():route.abort())
  await setup.route('**/api/settings',route=>route.fulfill({json:{...settings,ownerConfigured:false,cloudConfigured:true,existingBusiness:false}}))
  await setup.goto(base)
  await setup.getByRole('button',{name:'Skip introduction',exact:true}).click()
  await setup.getByRole('button',{name:'Register a new business',exact:true}).click()
  await setup.getByRole('button',{name:'I already have a key',exact:true}).click()
  await setup.getByLabel('Business registration key').fill('SBIT-TEST')
  await setup.getByLabel('Owner name',{exact:true}).fill('New owner')
  await setup.getByRole('button',{name:'Continue',exact:true}).click()
  await setup.getByRole('heading',{name:'Your owner account',exact:true}).waitFor()
  await setup.getByLabel('Email',{exact:true}).fill('new@example.com')
  await setup.getByLabel('Password',{exact:true}).fill('a-long-new-password')
  await setup.getByLabel('Confirm password',{exact:true}).fill('a-long-new-password')
  await setup.getByRole('button',{name:'Continue',exact:true}).click()
  await setup.getByRole('heading',{name:'Ready to begin',exact:true}).waitFor()
  await setup.getByRole('button',{name:'Previous step',exact:true}).click()
  assert.equal(await setup.getByLabel('Email',{exact:true}).inputValue(),'new@example.com')
  assert.equal(await setup.getByLabel('Password',{exact:true}).inputValue(),'a-long-new-password')
  await setup.getByRole('button',{name:'Continue',exact:true}).click()
  assert.equal(await setup.locator('form').evaluate(form=>new FormData(form).get('registrationKey')),'SBIT-TEST')
  await setup.screenshot({path:'docs/screenshots/entry-review.png',fullPage:true})
  assert.deepEqual(errors,[])
  console.log('PASS: fresh business empty screens, isolated inventory/sales/customer/staff/settings/expense/order/table tasks, supplier/customer saves, mobile/desktop layout and drawer')
} finally { await browser?.close(); child.kill(); cloud.close() }
