import { createServer } from 'node:http'
﻿import { chromium } from '@playwright/test'
import { spawn } from 'node:child_process'
import { mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { once } from 'node:events'
import assert from 'node:assert/strict'
const data = await mkdtemp(join(tmpdir(), 'stockroom-desktop-pos-'))
const port = 9357
const base = `http://127.0.0.1:${port}`
const subscriptionServer = createServer((request, response) => { response.setHeader('Content-Type','application/json'); response.end(JSON.stringify({businessId:'service-test',testMode:true})) })
await new Promise(resolve => subscriptionServer.listen(9359,'127.0.0.1',resolve))
const child = spawn(process.execPath, ['server/index.mjs'], { env: { ...process.env, PORT:String(port), CUSTOMER_DISPLAY_PORT:'9358', STOCKROOM_DATA_DIR:data, SYNC_CONFIG_PATH:join(data,'sync.json'), SYNC_API_URL:'http://127.0.0.1:9359', SYNC_DEVICE_TOKEN:'test', BUSINESS_ID:'service-test', DEVICE_ID:'test-device' }, stdio:'ignore' })
let browser
try {
 for(let i=0;i<80;i++){try{if((await fetch(base+'/api/health')).ok)break}catch{};await new Promise(r=>setTimeout(r,100))}
 const account=await (await fetch(base+'/api/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({appName:'Corner Shop',ownerName:'Test Cashier',email:'desktop@test.local',password:'long-test-password'})})).json()
 assert.ok(account.token)
 const headers={'Content-Type':'application/json',Authorization:`Bearer ${account.token}`}
 for(const [name,price,category] of [['Orange juice',15,'Drinks'],['Wholemeal bread',10,'Bakery'],['Coffee',20,'Drinks']]) await fetch(base+'/api/products',{method:'POST',headers,body:JSON.stringify({name,price,category,sku:name,stock:20,reorder:2,cost:3,unit:'piece'})})
 browser=await chromium.launch({channel:'msedge',headless:true})
 const page=await browser.newPage({viewport:{width:1366,height:900}})
 page.on('dialog', async dialog => { console.log('Dialog:', dialog.message()); await dialog.dismiss() })
 const errors=[];page.on('pageerror',error=>errors.push(error.message))
 await page.route('**/*',route=>route.request().url().startsWith(base)?route.continue():route.abort())
 await page.route('**/api/subscriptions/access',route=>route.fulfill({json:{testMode:true,blocked:false,status:'test'}}))
 await page.addInitScript(account=>{localStorage.setItem('stockroom-token',account.token);localStorage.setItem('stockroom-user',JSON.stringify(account.user));const key=`stockroom-active-screen:${account.user.organizationId}:${account.user.id}`;if(!localStorage.getItem(key))localStorage.setItem(key,'POS')},account)
 await page.goto(base)
 await page.getByRole('heading',{name:'Basket',exact:true}).waitFor({timeout:30000})
 await page.getByRole('button', {name:'Payments & receipts',exact:true}).click()
 const service = page.locator('.service-payments')
 await service.getByRole('button',{name:'Church collections',exact:true}).click()
 await service.getByRole('heading',{name:'Church collections',exact:true}).waitFor()
 await service.getByRole('button',{name:'New payment',exact:true}).click()
 assert.equal(await service.getByRole('heading',{name:'Payment history',exact:true}).count(),0)
 assert.equal(await service.getByRole('button',{name:'Customize receipt',exact:true}).count(),0)
 await page.getByRole('button',{name:'Business settings',exact:true}).click()
 await page.getByRole('button',{name:'Receipts',exact:true}).click()
 await service.getByRole('button',{name:'Customize receipt',exact:true}).click()
 await service.getByLabel('Receipt footer',{exact:true}).fill('Thank you from our office.')
 await service.getByRole('button',{name:'Add saved service',exact:true}).click()
 await service.getByLabel('Service name',{exact:true}).fill('Reusable printing')
 await service.getByLabel('Service price',{exact:true}).fill('15')
 await service.getByRole('button',{name:'Save receipt settings',exact:true}).click()
 await service.getByText('Receipt settings saved.',{exact:true}).waitFor()
 await page.getByRole('button',{name:'Payments & receipts',exact:true}).click()
 assert.equal(await service.getByLabel('Receipt footer',{exact:true}).count(),0)
 assert.equal(await service.getByLabel(/SKU/).count(),0)
 assert.equal(await service.locator('.payment-summary').getByText(/Tax/).count(),0)
 const controls = await service.locator('input:not([type=checkbox]),select').evaluateAll(nodes => nodes.filter(node=>node.getBoundingClientRect().height>0).map(node=>({height:node.getBoundingClientRect().height,font:parseFloat(getComputedStyle(node).fontSize)})))
 assert.ok(controls.every(control=>control.height>=44 && control.font>=16))
 await service.getByLabel('Add saved service',{exact:true}).selectOption({label:'Reusable printing / $15.00'})
 assert.equal(await service.getByLabel('Unit price',{exact:true}).inputValue(),'15')
 await service.getByLabel('Payment for',{exact:true}).fill('A4 DI printing')
 assert.equal(await service.getByLabel('Customer name (optional)',{exact:true}).isVisible(),false)
 await service.getByText('Customer and receipt details (optional)',{exact:true}).click()
 await service.getByLabel('Customer name (optional)',{exact:true}).fill('Ada Customer')
 await service.getByLabel('Customer phone (optional)',{exact:true}).fill('08012345678')
 await service.getByLabel('Unit price',{exact:true}).fill('15')
 await page.getByRole('button', {name:'Product sales',exact:true}).click()
 await page.getByRole('heading',{name:'Basket',exact:true}).waitFor()
 assert.equal(await service.isVisible(),false)
 await page.getByRole('button', {name:'Payments & receipts',exact:true}).click()
 assert.equal(await service.getByLabel('Payment for',{exact:true}).inputValue(),'A4 DI printing')
 await page.reload()
 await service.getByLabel('Payment for',{exact:true}).waitFor()
 assert.equal(await service.getByLabel('Customer name (optional)',{exact:true}).inputValue(),'Ada Customer')
 assert.equal(await service.getByLabel('Unit price',{exact:true}).inputValue(),'15')
 await service.getByLabel('Cash received (optional)',{exact:true}).fill('20')
 await service.getByRole('button',{name:'Save payment',exact:true}).click()
 await service.getByRole('heading',{name:'Payment saved',exact:true}).waitFor()
 assert.equal(await service.getByLabel('Payment for',{exact:true}).inputValue(),'')
 const receipt = page.locator('.print-receipt')
 assert.match(await receipt.textContent(),/Ada Customer/)
 assert.match(await receipt.textContent(),/08012345678/)
 await page.evaluate(()=>{window.print=()=>{window.printedServiceReceipt=document.querySelector('.print-receipt').textContent}})
 await service.getByRole('button',{name:'Print receipt',exact:true}).click()
 await page.waitForFunction(()=>typeof window.printedServiceReceipt==='string')
 assert.match(await page.evaluate(()=>window.printedServiceReceipt),/Ada Customer/)
 await service.getByText('Digital receipt',{exact:true}).first().click()
 const download = page.waitForEvent('download')
 await service.getByRole('button',{name:'Download receipt',exact:true}).first().click()
 const downloaded = await download
 const { readFile } = await import('node:fs/promises')
 const content = await readFile(await downloaded.path(), 'utf8')
 assert.match(content,/Ada Customer/)
 assert.match(content,/08012345678/)
 assert.match(content,/A4 DI printing/)
 assert.doesNotMatch(content,/Tax \(/)
 assert.doesNotMatch(await receipt.textContent(),/Tax \(/)
 assert.ok(downloaded.suggestedFilename().startsWith('receipt-'))
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),true)
 const sales=await (await fetch(base+'/api/sales', {headers})).json()
 const sale=sales.sales.find(sale=>sale.items.some(item=>item.productName==='A4 DI printing'))
 assert.ok(sale, 'Service receipt was saved')
 assert.equal(sale.total,15)
 assert.equal(sale.items[0].quantity,1)
 assert.equal(sale.paymentDetails.servicePayment.customerPhone,'08012345678')
 const products=await (await fetch(base+'/api/products',{headers})).json()
 assert.ok(products.products.every(product=>product.stock===20), 'Services do not deduct inventory')
 assert.deepEqual(errors,[])
 await page.getByRole('button',{name:'Business settings',exact:true}).click()
 await page.getByRole('button',{name:'Workspaces',exact:true}).click()
 await page.getByLabel('Payment screens',{exact:true}).selectOption('payments')
 await page.getByRole('button',{name:'Save workspaces',exact:true}).click()
 await page.getByText('Workspaces saved. Use Sync now to share this choice with your other devices.',{exact:true}).waitFor()
 await page.getByRole('button',{name:'Payments & receipts',exact:true}).click()
 await page.reload()
 await service.getByRole('heading',{name:'Record a payment',exact:true}).waitFor()
 assert.equal(await page.getByRole('button',{name:'Product sales',exact:true}).count(),0)
 assert.equal(await page.getByRole('button',{name:'Inventory',exact:true}).count(),0)
 await service.getByLabel('Payment for',{exact:true}).fill('Hall rental')
 await service.getByLabel('Unit price',{exact:true}).fill('25')
 await service.getByLabel('Payment Method',{exact:true}).selectOption('bank-transfer')
 await service.getByLabel('Bank Transfer provider',{exact:true}).fill('Example Bank')
 await service.getByLabel('Payment reference',{exact:true}).fill('TRANSFER-123')
 await service.getByRole('button',{name:'Save payment',exact:true}).click()
 await service.getByRole('heading',{name:'Payment saved',exact:true}).waitFor()
 assert.match(await page.locator('.print-receipt').textContent(),/Bank Transfer/)
 assert.match(await page.locator('.print-receipt').textContent(),/TRANSFER-123/)
 await page.emulateMedia({media:'print'})
 for (const width of [58,80]) {
   await page.evaluate(width=>{document.body.dataset.printKind='receipt';document.documentElement.style.setProperty('--receipt-width',width+'mm')},width)
   assert.equal(await page.locator('.print-receipt').evaluate(element=>element.scrollWidth<=element.clientWidth),true,`Receipt must fit the ${width} mm roll`)
 }
 await page.evaluate(()=>{delete document.body.dataset.printKind})
 await page.emulateMedia({media:'screen'})

 assert.ok((await (await fetch(base+'/api/products',{headers})).json()).products.every(product=>product.stock===20))

 await service.getByRole('button',{name:'Jobs & invoices',exact:true}).click()
 await service.getByRole('button',{name:'New job / estimate',exact:true}).click()
 await service.getByLabel('Job description',{exact:true}).fill('Print 200 flyers')
 await service.getByLabel('Customer name',{exact:true}).fill('Ada Client')
 await service.getByLabel('Job item',{exact:true}).fill('Flyers')
 await service.getByLabel('Quantity',{exact:true}).fill('200')
 await service.getByLabel('Unit price',{exact:true}).fill('0.50')
 await service.getByRole('button',{name:'Save job',exact:true}).click()
 await service.getByRole('heading',{name:'Print 200 flyers',exact:true}).waitFor()
 await page.evaluate(()=>{window.print=()=>{window.jobPrint=document.querySelector('.print-order')?.textContent}})
 await service.getByRole('button',{name:'Print invoice',exact:true}).click()
 await page.waitForFunction(()=>window.jobPrint?.includes('INVOICE'))
 assert.match(await page.evaluate(()=>window.jobPrint),/Balance due:.*100/)
 assert.doesNotMatch(await page.evaluate(()=>window.jobPrint),/PAYMENT RECEIPT/)
 let paymentRequest
 page.on('request',request=>{if(request.url().endsWith('/api/pos/service-jobs/pay'))paymentRequest={input:request.postDataJSON(),headers:request.headers()}})
 await service.getByRole('button',{name:'Take payment',exact:true}).click()
 await service.getByLabel('Payment amount',{exact:true}).fill('30')
 await service.getByRole('button',{name:'Save invoice payment',exact:true}).click()
 await service.getByText('Payment saved: $30.00',{exact:true}).waitFor()
 const retry=await fetch(base+'/api/pos/service-jobs/pay',{method:'POST',headers:paymentRequest.headers,body:JSON.stringify(paymentRequest.input)})
 assert.equal(retry.status,200,'Retry the same deposit without recording it twice')
 const jobState=await (await fetch(base+'/api/pos/service-jobs',{headers})).json()
 const createdJob=jobState.jobs.find(job=>job.title==='Print 200 flyers')
 assert.equal(createdJob.payments.length,1)
 assert.equal(createdJob.balance.due,70)
 await service.getByRole('button',{name:'Print receipt',exact:true}).click()
 assert.match(await page.locator('.print-receipt').textContent(),/Balance due:.*70/)
 await page.reload()
 await page.getByRole('button',{name:'Payments & receipts',exact:true}).click()
 await service.getByRole('button',{name:'Jobs & invoices',exact:true}).click()
 await service.getByRole('heading',{name:'Print 200 flyers',exact:true}).waitFor()
 await service.getByRole('button',{name:'Take payment',exact:true}).click()
 assert.equal(await service.getByLabel('Payment amount',{exact:true}).inputValue(),'70')
 await service.getByLabel('Payment Method',{exact:true}).selectOption('multiple')
 await service.getByLabel('Part amount',{exact:true}).nth(0).fill('20')
 await service.getByLabel('Part amount',{exact:true}).nth(1).fill('50')
 await service.getByLabel('Bank Transfer provider',{exact:true}).fill('Example Bank')
 await service.getByLabel('Part reference',{exact:true}).fill('INVOICE-SPLIT')
 await service.getByRole('button',{name:'Save invoice payment',exact:true}).click()
 await service.getByText('Payment saved: $70.00',{exact:true}).waitFor()
 const completedJob=(await (await fetch(base+'/api/pos/service-jobs',{headers})).json()).jobs.find(job=>job.id===createdJob.id)
 assert.equal(completedJob.payments.length,2)
 assert.equal(completedJob.balance.due,0)
 assert.equal(completedJob.payments.reduce((sum,entry)=>sum+entry.sale.total,0),100)
 assert.ok((await (await fetch(base+'/api/products',{headers})).json()).products.every(product=>product.stock===20))
 // Refund an invoice payment through the same return engine; restore its balance.
 await service.locator('.service-jobs summary').filter({hasText:'Payment history'}).click()
 const depositRow=service.locator('.service-jobs .customer-row').filter({hasText:'$30.00'})
 await depositRow.getByRole('button',{name:'Refund payment',exact:true}).click()
 await service.getByLabel('Refund amount',{exact:true}).fill('10')
 await service.getByLabel('Refund reason',{exact:true}).fill('Deposit returned to customer')
 await service.getByRole('button',{name:'Save refund',exact:true}).click()
 await service.getByText('Refund recorded. The balance has been updated.',{exact:true}).waitFor()
 const refundedJob=(await (await fetch(base+'/api/pos/service-jobs',{headers})).json()).jobs.find(job=>job.id===createdJob.id)
 assert.equal(refundedJob.balance.refunded,10);assert.equal(refundedJob.balance.due,10)
 await service.getByRole('button',{name:'Take payment',exact:true}).click()
 await service.getByRole('button',{name:'Save invoice payment',exact:true}).click()
 await service.getByText('Payment saved: $10.00',{exact:true}).waitFor()
 assert.equal((await (await fetch(base+'/api/pos/service-jobs',{headers})).json()).jobs.find(job=>job.id===createdJob.id).balance.due,0)
 await service.getByLabel('Statement customer',{exact:true}).selectOption({index:1})
 await page.evaluate(()=>{window.print=()=>{window.jobPrint=document.querySelector('.print-order')?.textContent}})
 await service.getByRole('button',{name:'Print customer statement',exact:true}).click()
 await page.waitForFunction(()=>window.jobPrint?.includes('Invoice customer statement'))
 assert.match(await page.evaluate(()=>window.jobPrint),/Invoice customer statement/)
 await service.getByRole('button',{name:'New payment',exact:true}).click()
 await page.getByRole('button',{name:'Overview',exact:true}).click()
 await page.getByRole('heading',{name:"Start today's work",exact:true}).waitFor()
 assert.equal(await page.getByRole('button',{name:'Start a sale',exact:true}).count(),0)
 await page.getByRole('button',{name:'Record a payment',exact:true}).click()
 await service.getByRole('button',{name:'Payment history',exact:true}).click()
 await service.getByRole('heading',{name:'Payment history',exact:true}).waitFor()
 await service.locator('.customer-row').filter({hasText:'Hall rental'}).getByRole('button',{name:'Refund payment',exact:true}).click()
 await service.getByRole('heading',{name:'Refund payment',exact:true}).waitFor()
 await service.getByLabel('Refund quantity',{exact:true}).fill('0.5')
 await service.getByLabel('Refund reason',{exact:true}).fill('Part of hall rental cancelled')
 await service.getByRole('button',{name:'Save refund',exact:true}).click()
 await service.getByText('Refund recorded. The original receipt is kept.',{exact:true}).waitFor()
 const refundState=await (await fetch(base+'/api/pos',{headers})).json()
 assert.ok(refundState.returns.some(record=>record.reason==='Part of hall rental cancelled' && record.total===12.5))
 assert.ok((await (await fetch(base+'/api/products',{headers})).json()).products.every(product=>product.stock===20))
 await service.locator('.customer-row').filter({hasText:'Hall rental'}).getByRole('button',{name:'Refund payment',exact:true}).click()
 assert.equal(await service.getByLabel('Refund quantity',{exact:true}).getAttribute('max'),'0.5')
 await service.getByRole('button',{name:'Close refund',exact:true}).click()

 assert.equal(await service.getByLabel('Payment for',{exact:true}).count(),0)
 await service.getByRole('button',{name:'New payment',exact:true}).click()
 await service.getByLabel('Payment for',{exact:true}).waitFor()
 await page.getByRole('button',{name:'Sales history',exact:true}).click()
 assert.equal(await page.getByText('Product variants and extras',{exact:true}).count(),0)
 console.log('PASS: separate screens, draft switching/reload, customer receipt/download, cash payment, payments-only setup and unchanged inventory')
} finally {if(browser)await browser.close();child.kill();await once(child,'exit').catch(()=>{});await rm(data,{recursive:true,force:true}); subscriptionServer.close()}
