import { createServer } from 'node:http'
﻿import { chromium } from '@playwright/test'
import { spawn } from 'node:child_process'
import { mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { once } from 'node:events'
import assert from 'node:assert/strict'
const data = await mkdtemp(join(tmpdir(), 'stockroom-desktop-pos-'))
const port = 9357
const base = `http://127.0.0.1:${port}`
const subscriptionServer = createServer((request, response) => { response.setHeader('Content-Type','application/json'); response.end(JSON.stringify({businessId:'service-test',testMode:true})) })
await new Promise(resolve => subscriptionServer.listen(9359,'127.0.0.1',resolve))
const child = spawn(process.execPath, ['server/index.mjs'], { env: { ...process.env, PORT:String(port), CUSTOMER_DISPLAY_PORT:'9358', STOCKROOM_DATA_DIR:data, SYNC_CONFIG_PATH:join(data,'sync.json'), SYNC_API_URL:'http://127.0.0.1:9359', SYNC_DEVICE_TOKEN:'test', BUSINESS_ID:'service-test', DEVICE_ID:'test-device' }, stdio:'ignore' })
let browser
try {
 for(let i=0;i<80;i++){try{if((await fetch(base+'/api/health')).ok)break}catch{};await new Promise(r=>setTimeout(r,100))}
 const account=await (await fetch(base+'/api/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({appName:'Corner Shop',ownerName:'Test Cashier',email:'desktop@test.local',password:'long-test-password'})})).json()
 assert.ok(account.token)
 const headers={'Content-Type':'application/json',Authorization:`Bearer ${account.token}`}
 for(const [name,price,category] of [['Orange juice',15,'Drinks'],['Wholemeal bread',10,'Bakery'],['Coffee',20,'Drinks']]) await fetch(base+'/api/products',{method:'POST',headers,body:JSON.stringify({name,price,category,sku:name,stock:20,reorder:2,cost:3,unit:'piece'})})
 browser=await chromium.launch({channel:'msedge',headless:true})
 const page=await browser.newPage({viewport:{width:1366,height:900}})
 page.on('dialog', async dialog => { console.log('Dialog:', dialog.message()); await dialog.dismiss() })
 const errors=[];page.on('pageerror',error=>errors.push(error.message))
 await page.route('**/*',route=>route.request().url().startsWith(base)?route.continue():route.abort())
 await page.route('**/api/subscriptions/access',route=>route.fulfill({json:{testMode:true,blocked:false,status:'test'}}))
 await page.addInitScript(account=>{localStorage.setItem('stockroom-token',account.token);localStorage.setItem('stockroom-user',JSON.stringify(account.user));const key=`stockroom-active-screen:${account.user.organizationId}:${account.user.id}`;if(!localStorage.getItem(key))localStorage.setItem(key,'POS')},account)
 await page.goto(base)
 await page.getByRole('heading',{name:'Basket',exact:true}).waitFor({timeout:30000})
 await page.getByRole('button', {name:'Payments & receipts',exact:true}).click()
 const service = page.locator('.service-payments')
 assert.equal(await service.getByRole('heading',{name:'Payment history',exact:true}).count(),0)
 assert.equal(await service.getByRole('button',{name:'Customize receipt',exact:true}).count(),0)
 await page.getByRole('button',{name:'Business settings',exact:true}).click()
 await page.getByRole('button',{name:'Receipts',exact:true}).click()
 await service.getByRole('button',{name:'Customize receipt',exact:true}).click()
 await service.getByLabel('Receipt footer',{exact:true}).fill('Thank you from our office.')
 await service.getByRole('button',{name:'Save receipt settings',exact:true}).click()
 await service.getByText('Receipt settings saved.',{exact:true}).waitFor()
 await page.getByRole('button',{name:'Payments & receipts',exact:true}).click()
 assert.equal(await service.getByLabel('Receipt footer',{exact:true}).count(),0)
 assert.equal(await service.getByLabel(/SKU/).count(),0)
 assert.equal(await service.locator('.payment-summary').getByText(/Tax/).count(),0)
 const controls = await service.locator('input:not([type=checkbox]),select').evaluateAll(nodes => nodes.filter(node=>node.getBoundingClientRect().height>0).map(node=>({height:node.getBoundingClientRect().height,font:parseFloat(getComputedStyle(node).fontSize)})))
 assert.ok(controls.every(control=>control.height>=44 && control.font>=16))
 await service.getByLabel('Payment for',{exact:true}).fill('A4 DI printing')
 await service.getByLabel('Customer name (optional)',{exact:true}).fill('Ada Customer')
 await service.getByLabel('Customer phone (optional)',{exact:true}).fill('08012345678')
 await service.getByLabel('Unit price',{exact:true}).fill('15')
 await page.getByRole('button', {name:'Stock & checkout',exact:true}).click()
 await page.getByRole('heading',{name:'Basket',exact:true}).waitFor()
 assert.equal(await service.isVisible(),false)
 await page.getByRole('button', {name:'Payments & receipts',exact:true}).click()
 assert.equal(await service.getByLabel('Payment for',{exact:true}).inputValue(),'A4 DI printing')
 await page.reload()
 await service.getByLabel('Payment for',{exact:true}).waitFor()
 assert.equal(await service.getByLabel('Customer name (optional)',{exact:true}).inputValue(),'Ada Customer')
 assert.equal(await service.getByLabel('Unit price',{exact:true}).inputValue(),'15')
 await service.getByLabel('Cash received (optional)',{exact:true}).fill('20')
 await service.getByRole('button',{name:'Save payment',exact:true}).click()
 await service.getByRole('heading',{name:'Payment saved',exact:true}).waitFor()
 assert.equal(await service.getByLabel('Payment for',{exact:true}).inputValue(),'')
 const receipt = page.locator('.print-receipt')
 assert.match(await receipt.textContent(),/Ada Customer/)
 assert.match(await receipt.textContent(),/08012345678/)
 await page.evaluate(()=>{window.print=()=>{window.printedServiceReceipt=document.querySelector('.print-receipt').textContent}})
 await service.getByRole('button',{name:'Print receipt',exact:true}).click()
 await page.waitForFunction(()=>typeof window.printedServiceReceipt==='string')
 assert.match(await page.evaluate(()=>window.printedServiceReceipt),/Ada Customer/)
 await service.getByText('Digital receipt',{exact:true}).first().click()
 const download = page.waitForEvent('download')
 await service.getByRole('button',{name:'Download receipt',exact:true}).first().click()
 const downloaded = await download
 const { readFile } = await import('node:fs/promises')
 const content = await readFile(await downloaded.path(), 'utf8')
 assert.match(content,/Ada Customer/)
 assert.match(content,/08012345678/)
 assert.match(content,/A4 DI printing/)
 assert.doesNotMatch(content,/Tax \(/)
 assert.doesNotMatch(await receipt.textContent(),/Tax \(/)
 assert.ok(downloaded.suggestedFilename().startsWith('receipt-'))
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),true)
 const sales=await (await fetch(base+'/api/sales', {headers})).json()
 const sale=sales.sales.find(sale=>sale.items.some(item=>item.productName==='A4 DI printing'))
 assert.ok(sale, 'Service receipt was saved')
 assert.equal(sale.total,15)
 assert.equal(sale.items[0].quantity,1)
 assert.equal(sale.paymentDetails.servicePayment.customerPhone,'08012345678')
 const products=await (await fetch(base+'/api/products',{headers})).json()
 assert.ok(products.products.every(product=>product.stock===20), 'Services do not deduct inventory')
 assert.deepEqual(errors,[])
 await page.getByRole('button',{name:'Business settings',exact:true}).click()
 await page.getByRole('button',{name:'Workspaces',exact:true}).click()
 await page.getByLabel('Payment screens',{exact:true}).selectOption('payments')
 await page.getByRole('button',{name:'Save payment screens',exact:true}).click()
 await page.getByText('Payment screens saved. Use Sync now to share this choice with your other devices.',{exact:true}).waitFor()
 await page.getByRole('button',{name:'Payments & receipts',exact:true}).click()
 await page.reload()
 await service.getByRole('heading',{name:'Record a payment',exact:true}).waitFor()
 assert.equal(await page.getByRole('button',{name:'Stock & checkout',exact:true}).count(),0)
 assert.equal(await page.getByRole('button',{name:'Inventory',exact:true}).count(),0)
 await service.getByLabel('Payment for',{exact:true}).fill('Hall rental')
 await service.getByLabel('Unit price',{exact:true}).fill('25')
 await service.getByLabel('Payment method',{exact:true}).selectOption('bank-transfer')
 await service.getByLabel('Bank / provider',{exact:true}).fill('Example Bank')
 await service.getByLabel('Payment reference',{exact:true}).fill('TRANSFER-123')
 await service.getByRole('button',{name:'Save payment',exact:true}).click()
 await service.getByRole('heading',{name:'Payment saved',exact:true}).waitFor()
 assert.match(await page.locator('.print-receipt').textContent(),/Bank transfer/)
 assert.match(await page.locator('.print-receipt').textContent(),/TRANSFER-123/)
 assert.ok((await (await fetch(base+'/api/products',{headers})).json()).products.every(product=>product.stock===20))
 await page.getByRole('button',{name:'Overview',exact:true}).click()
 await page.getByRole('heading',{name:"Start today's work",exact:true}).waitFor()
 assert.equal(await page.getByRole('button',{name:'Start a sale',exact:true}).count(),0)
 await page.getByRole('button',{name:'Record a payment',exact:true}).click()
 await service.getByRole('button',{name:'Payment history',exact:true}).click()
 await service.getByRole('heading',{name:'Payment history',exact:true}).waitFor()
 assert.equal(await service.getByLabel('Payment for',{exact:true}).count(),0)
 await service.getByRole('button',{name:'New payment',exact:true}).click()
 await service.getByLabel('Payment for',{exact:true}).waitFor()
 await page.getByRole('button',{name:'Sales history',exact:true}).click()
 assert.equal(await page.getByText('Product variants and extras',{exact:true}).count(),0)
 console.log('PASS: separate screens, draft switching/reload, customer receipt/download, cash payment, payments-only setup and unchanged inventory')
} finally {if(browser)await browser.close();child.kill();await once(child,'exit').catch(()=>{});await rm(data,{recursive:true,force:true}); subscriptionServer.close()}
