import { createServer } from 'vite'
import { chromium } from '@playwright/test'
import assert from 'node:assert/strict'
const server = await createServer({ server: { port: 0, host: '127.0.0.1', hmr: false } })
await server.listen()
const browser = await chromium.launch({ channel: 'msedge', headless: true })
try {
  const page = await browser.newPage(); page.setDefaultTimeout(20000)
  const base = `http://127.0.0.1:${server.httpServer.address().port}`, requests = []
  await page.route(`${base}/recovery-harness`, route => route.fulfill({ contentType: 'text/html', body: '<div id="root"></div>' }))
  await page.route('**/api/till-recovery/register', route => route.fulfill({ json: { businessId: 'shop', tillId: 'new-till', deviceId: 'new-device' } }))
  await page.route('**/api/sync/now', route => route.fulfill({ json: { configured: true, pending: 0, conflicts: 0 } }))
  await page.route('**/api/sync/pull', route => route.fulfill({ json: { configured: true, pending: 0, conflicts: 0 } }))
  await page.route('**/v1/till-recovery/tills', route => route.fulfill({ json: { tills: [{ tillId: 'old-till', deviceId: 'old-device', deviceLabel: 'Lost checkout' }] } }))
  await page.route('**/v1/till-recovery/recover', route => {
    requests.push(route.request().postDataJSON())
    return requests.length === 1 ? route.fulfill({ status: 503, json: { error: 'Recovery reply interrupted' } }) : route.fulfill({ json: { tillId: 'old-till', deviceId: 'new-device' } })
  })
  await page.goto(`${base}/recovery-harness`, { waitUntil: 'domcontentloaded' })
  await page.evaluate(async () => {
    localStorage.setItem('stockroom-checkout-till-id', 'new-till')
    await import('/src/styles.css')
    const { React, createRoot } = await import('/test/shop-setup-harness.ts')
    const { TillRecovery } = await import('/src/TillRecovery.tsx')
    createRoot(document.getElementById('root')).render(React.createElement(TillRecovery, { businessId: 'shop', apiUrl: '', token: 'owner-token', headers: { Authorization: 'Bearer local-owner' }, onToken: () => {} }))
  })
  await page.getByRole('button', { name: 'Load recoverable tills' }).click()
  await page.getByLabel('Lost checkout').selectOption('old-till')
  await page.getByRole('button', { name: 'Recover checkout on this device' }).click()
  const modal = page.getByRole('alertdialog'), confirm = page.getByRole('button', { name: 'Confirm till recovery' })
  assert.equal(await confirm.isDisabled(), true)
  await modal.getByRole('button', { name: 'Cancel', exact: true }).click()
  assert.equal(requests.length, 0)
  await page.getByRole('button', { name: 'Recover checkout on this device' }).click()
  await page.getByLabel('Owner password').fill('owner-password')
  await page.getByLabel('The original device is stopped').check()
  await page.getByLabel('I reconciled unsynchronized').check()
  await page.getByLabel('Type RECOVER').fill('RECOVER')
  assert.equal(await confirm.evaluate(element => getComputedStyle(element).backgroundColor), 'rgb(180, 35, 24)')
  await confirm.click()
  await modal.getByRole('alert').waitFor()
  assert.equal(await page.getByLabel('Owner password').inputValue(), '')
  assert.equal(await page.evaluate(() => localStorage.getItem('stockroom-checkout-till-id')), 'new-till')
  await page.getByLabel('Owner password').fill('owner-password')
  await confirm.click()
  await page.waitForFunction(() => localStorage.getItem('stockroom-checkout-till-id') === 'old-till' && !localStorage.getItem('stockroom-till-recovery:shop'))
  assert.equal(requests.length, 2); assert.equal(requests[0].requestId, requests[1].requestId)
  assert.equal(requests[0].targetDeviceId, 'new-device'); assert.equal(requests[0].sourceDeviceId, 'old-device')
  console.log('Owner recovery warning, Cancel, red confirmation, interrupted reply/retry and identity restore passed.')
} finally { await browser.close(); await server.close() }
