import {createServer} from 'vite'
import {chromium} from '@playwright/test'
import assert from 'node:assert/strict'
import {mkdirSync} from 'node:fs'
const server=await createServer({server:{port:0,host:'127.0.0.1',hmr:false}});await server.listen()
const browser=await chromium.launch({channel:'msedge',headless:true})
try{
 const page=await browser.newPage({viewport:{width:1280,height:900}});page.setDefaultTimeout(60000);const errors=[];page.on('pageerror',error=>errors.push(error.message));const base=`http://127.0.0.1:${server.httpServer.address().port}`
 await page.route('**/*',route=>route.request().url().startsWith(base)?route.continue():route.abort())
 await page.route(base+'/ui-harness',async route=>route.fulfill({contentType:'text/html',body:await server.transformIndexHtml('/ui-harness','<div id="root"></div>')}))
 await page.goto(base+'/ui-harness')
 await page.evaluate(async()=>{const{React,createRoot}=await import('/test/shop-setup-harness.ts');await import('/src/styles.css');await import('/src/ui.css');const{UserGuide}=await import('/src/UserGuide.tsx');window.root=createRoot(document.getElementById('root'));window.root.render(React.createElement('div',{className:'app-shell'},React.createElement('main',{className:'main-content'},React.createElement(UserGuide,{role:'owner'}))))})
 const before=await page.locator('.guide-chapter h2').textContent();await page.getByRole('button',{name:'Next topic →',exact:true}).click();assert.notEqual(await page.locator('.guide-chapter h2').textContent(),before);await page.getByRole('button',{name:'← Previous topic',exact:true}).click();assert.equal(await page.locator('.guide-chapter h2').textContent(),before)
 await page.getByRole('searchbox',{name:'Search guide'}).fill('Choose staff access');await page.getByRole('button',{name:'Staff & access and Staff activity',exact:true}).click();assert.match(await page.locator('.guide-chapter').textContent(),/owner password/);assert.equal(await page.locator('select').count(),0)
 await page.evaluate(async()=>{const{React}=await import('/test/shop-setup-harness.ts');const{NavigationGroup}=await import('/src/NavigationGroup.tsx');const{ToolSearch}=await import('/src/ToolSearch.tsx');window.opened=0;window.root.render(React.createElement('div',{className:'app-shell'},React.createElement('aside',{className:'sidebar'},React.createElement(NavigationGroup,{title:'Staff & access'},React.createElement('button',{onClick:()=>window.opened++},'Access permissions'))),React.createElement('main',{className:'main-content'},React.createElement(ToolSearch,{tools:[{label:'Access permissions',open:()=>window.opened++}]}))))})
 await page.getByRole('button',{name:'Staff & access',exact:true}).click();assert.equal(await page.evaluate(()=>window.opened),0);await page.getByRole('button',{name:'Access permissions',exact:true}).click();assert.equal(await page.evaluate(()=>window.opened),1)
 await page.getByRole('searchbox',{name:'Find a tool'}).fill('permissions');await page.locator('.tool-search-results button').click();assert.equal(await page.evaluate(()=>window.opened),2)
 await page.evaluate(async()=>{const{React}=await import('/test/shop-setup-harness.ts');const{ReportCharts}=await import('/src/ReportCharts.tsx');window.root.render(React.createElement('div',{className:'app-shell'},React.createElement('main',{className:'main-content'},React.createElement(ReportCharts,{currency:'NGN',timeZone:'Africa/Lagos',data:{daily:[{label:'2026-10-01',value:100},{label:'2026-10-02',value:-10}],payments:[{label:'Cash',value:100},{label:'Split payment',value:50}],products:[{label:'Rice',value:2}],expenses:[]}}))))})
 await page.getByRole('heading',{name:'Daily sales',exact:true}).waitFor();await page.locator('.report-chart').first().getByText('View data table',{exact:true}).click();await page.locator('.report-chart').first().getByRole('cell',{name:'2026-10-01'}).waitFor()
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true)
 await page.evaluate(async()=>{const{React}=await import('/test/shop-setup-harness.ts');const{StaffPermissions}=await import('/src/StaffPermissions.tsx');window.root.render(React.createElement('div',{className:'app-shell'},React.createElement('main',{className:'main-content'},React.createElement('section',{className:'panel team-management'},React.createElement('h2',{},'Example staff access'),React.createElement(StaffPermissions,{member:{id:'example',role:'cashier',permissions:{productSales:true,register:true}},save:async()=>{}})))))})
 await page.getByText('Choose staff access',{exact:true}).click();await page.getByLabel('Product sales',{exact:true}).waitFor();mkdirSync('public/guide',{recursive:true});await page.locator('.team-management').screenshot({path:'public/guide/staff-access.png'})
 const themes=await page.evaluate(async()=>{const{applyLogoTheme}=await import('/src/lib/logoTheme.ts');const out=[];for(const color of ['#ffe500','#cc2255','#000000']){await applyLogoTheme('',color);out.push(getComputedStyle(document.documentElement).getPropertyValue('--brand-primary'))}return out});assert.ok(themes.every(Boolean));assert.equal(errors.length,0,errors.join('\n'))
 await page.evaluate(async()=>{const{React}=await import('/test/shop-setup-harness.ts');const{BrandAppearance}=await import('/src/BrandAppearance.tsx');const{normalizeShopProfile}=await import('/server/shop-profile.mjs');window.root.render(React.createElement(BrandAppearance,{profile:normalizeShopProfile({brandColor:'#cc2255'}),preview:()=>{},save:async profile=>{window.savedProfile=profile}}))})
 await page.getByRole('button',{name:'Save appearance',exact:true}).click();assert.equal((await page.evaluate(()=>window.savedProfile)).brandColor,'#cc2255')
 await page.getByLabel('Suggest colours from my logo',{exact:true}).check();await page.getByRole('button',{name:'Save appearance',exact:true}).click();assert.equal((await page.evaluate(()=>window.savedProfile)).brandColor,'')
 await page.evaluate(async()=>{const{React}=await import('/test/shop-setup-harness.ts');const{HelpMenu}=await import('/src/HelpMenu.tsx');window.root.render(React.createElement(HelpMenu,{}))})
 await page.getByText('Help & support',{exact:true}).click();assert.equal(await page.getByRole('heading',{name:'Contact Stockroom support'}).isVisible(),true);await page.keyboard.press('Escape');assert.equal(await page.getByRole('heading',{name:'Contact Stockroom support'}).isVisible(),false)
 assert.equal(await page.locator('.help-menu summary').evaluate(element=>element===document.activeElement),true)
 assert.equal(errors.length,0,errors.join('\n'))
 console.log('UI refactor browser checks passed: guide, nested menus, tool search, report charts, mobile width, owner palette.')
}finally{await browser.close();await server.close()}
