import {createServer} from 'vite'
import {chromium} from '@playwright/test'
import assert from 'node:assert/strict'
const server=await createServer({server:{port:0,host:'127.0.0.1',hmr:false}});await server.listen()
const browser=await chromium.launch({channel:'msedge',headless:true})
try{
 const page=await browser.newPage();page.setDefaultTimeout(20000);const errors=[];page.on('pageerror',error=>errors.push(error.message));const base=`http://127.0.0.1:${server.httpServer.address().port}`
 await page.route('**/*',route=>route.request().url().startsWith(base)?route.continue():route.abort())
 await page.route(base+'/controls-test',async route=>route.fulfill({contentType:'text/html',body:await server.transformIndexHtml('/controls-test','<div id="root"></div>')}));await page.goto(base+'/controls-test')
 await page.evaluate(async()=>{
  const {React,createRoot}=await import('/test/shop-setup-harness.ts');const {StaffPermissions}=await import('/src/StaffPermissions.tsx');const {CatalogueStarters}=await import('/src/CatalogueStarters.tsx')
  window.root=createRoot(document.getElementById('root'));window.savedAccess=null;window.starter=null
  window.root.render(React.createElement(React.Fragment,null,React.createElement(StaffPermissions,{member:{id:'cashier',role:'cashier',permissions:{productSales:true}},save:async(id,permissions)=>{window.savedAccess={id,permissions}}}),React.createElement(CatalogueStarters,{kind:'stock',industry:'liquids',existing:[{name:'Palm oil',price:99}],add:item=>{window.starter=item}})))
 });await page.getByText('Choose staff access',{exact:true}).click();await page.getByLabel('Jobs and invoices',{exact:true}).check();await page.getByLabel('Tables & tabs',{exact:true}).check();await page.getByRole('button',{name:'Save staff access'}).click()
 const access=await page.evaluate(()=>window.savedAccess);assert.equal(access.id,'cashier');assert.equal(access.permissions.serviceJobs,true);assert.equal(access.permissions.restaurant,true);assert.equal(access.permissions.inventory,undefined)
 await page.getByText('Preloaded catalogue starters',{exact:true}).click();const options=await page.getByLabel('Add catalogue starter').locator('option').allTextContents();assert.ok(!options.includes('Palm oil'));assert.ok(options.includes('Groundnut oil'));await page.getByLabel('Add catalogue starter').selectOption({label:'Groundnut oil'});assert.equal((await page.evaluate(()=>window.starter)).unit,'litre')
 const result=await page.evaluate(async()=>{
  const {withBrowserDatabase,openBrowserDatabase}=await import('/src/lib/browserDatabase.ts');const {handleBrowserApi}=await import('/src/lib/browserApi.ts')
  await withBrowserDatabase(async()=>{const db=await openBrowserDatabase();await db.run("INSERT INTO app_settings(id,app_name,currency,updated_at) VALUES(1,'Shop','NGN',?)",[new Date().toISOString()]);await db.run('INSERT INTO users(id,name,email,role,operational_access,permissions,created_at) VALUES(?,?,?,?,?,?,?)',['cashier','Cashier','staff@test.local','cashier',1,JSON.stringify({productSales:true,inventory:true}),new Date().toISOString()]);await db.run("INSERT INTO mobile_settings(key,value) VALUES('sessionUserId','cashier')");return new Response('{}')})
  const checks=[];for(const path of ['/api/reports','/api/pos/service-jobs','/api/pos/restaurant'])checks.push((await withBrowserDatabase(()=>handleBrowserApi(path))).status)
  const product=await withBrowserDatabase(()=>handleBrowserApi('/api/products',{method:'POST',body:JSON.stringify({name:'Rice',sku:'RICE',price:10,cost:4,stock:0,reorder:0,category:'Food',unit:'bag'})}));return {checks,product:product.status,error:await product.text()}
 });assert.deepEqual(result.checks,[403,403,403]);assert.equal(result.product,201,result.error);
 await page.evaluate(async(base)=>{
  const {React,createRoot}=await import('/test/shop-setup-harness.ts');const {withBrowserDatabase,openBrowserDatabase}=await import('/src/lib/browserDatabase.ts');const {handleBrowserApi}=await import('/src/lib/browserApi.ts')
  await withBrowserDatabase(async()=>{const db=await openBrowserDatabase();await db.run("UPDATE users SET role='owner' WHERE id='cashier'");await db.run("INSERT INTO customers(id,name,phone,balance) VALUES('ada','Ada','555',150)");await db.run('UPDATE app_settings SET payment_policy=? WHERE id=1',[JSON.stringify({allowWallet:true})]);for(const [key,value] of Object.entries({syncApiUrl:base+'/cloud',businessId:'controls',deviceId:'controls-device',deviceToken:'test',['subscription:'+base+'/cloud:controls']:JSON.stringify({businessId:'controls',testMode:true,checkedAt:Date.now()})}))await db.run('INSERT INTO mobile_settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value',[key,value]);return new Response('{}')})
  const original=window.fetch.bind(window);window.fetch=(path,init)=>typeof path==='string'&&path.startsWith('/api/')?withBrowserDatabase(()=>handleBrowserApi(path,init)):original(path,init)
  const created=await fetch('/api/pos/service-jobs',{method:'POST',headers:{'X-Stockroom-Till':'controls-till','Content-Type':'application/json'},body:JSON.stringify({id:'service-job:wallet-ui',commandId:'wallet-ui-create',expectedUpdatedAt:'',title:'Wallet printing job',customerId:'ada',customerName:'Ada',customerPhone:'555',lines:[{id:'printing',description:'Printing',quantity:1,price:100}]})});if(!created.ok)throw new Error(await created.text())
  const {ServiceJobs}=await import('/src/ServiceJobs.tsx');window.root.unmount();window.root=createRoot(document.getElementById('root'));window.root.render(React.createElement(ServiceJobs,{headers:{'X-Stockroom-Till':'controls-till'},storageKey:'wallet-invoice-ui',walletAllowed:true,providers:[],money:String,print:async()=>{},manager:true,enabled:true,beforeSend:async()=>{}}))
 },base)
 await page.getByRole('button').filter({hasText:'Wallet printing job'}).click();await page.getByRole('button',{name:'Take payment',exact:true}).click();await page.getByLabel('Payment amount',{exact:true}).fill('30');await page.getByLabel('Payment Method',{exact:true}).selectOption('wallet');await page.getByRole('button',{name:'Save invoice payment',exact:true}).click();await page.locator('.payment-summary').getByText(/Balance due:.*70/).waitFor()
 const wallet=await page.evaluate(async()=>{const response=await fetch('/api/customers');return (await response.json()).customers.find(row=>row.id==='ada').balance});assert.equal(wallet,120)
 const birthday=await page.evaluate(async()=>{const response=await fetch('/api/customers/ada/birthday',{method:'PUT',body:JSON.stringify({birthday:'10-07',birthdayReminders:true})});if(!response.ok)throw new Error(await response.text());const {React,createRoot}=await import('/test/shop-setup-harness.ts');const {CustomerBirthday,BirthdayReminders}=await import('/src/CustomerBirthdays.tsx');const customer=await response.json();window.root.unmount();window.root=createRoot(document.getElementById('root'));window.root.render(React.createElement(React.Fragment,null,React.createElement(CustomerBirthday,{customer,headers:{},saved:updated=>{window.updatedBirthday=updated}}),React.createElement(BirthdayReminders,{customers:[customer],timeZone:'UTC'})));return customer});assert.equal(birthday.balance,120);assert.equal(birthday.birthday,'10-07');await page.getByText('Birthday reminder',{exact:true}).click();await page.getByLabel('Birthday (MM-DD)').fill('12-25');await page.getByRole('button',{name:'Save birthday reminder'}).click();await page.waitForFunction(()=>window.updatedBirthday?.birthday==='12-25');assert.equal((await page.evaluate(()=>window.updatedBirthday)).balance,120)
 await page.evaluate(async()=>{const {React,createRoot}=await import('/test/shop-setup-harness.ts');const {ProductIntake}=await import('/src/ProductIntake.tsx');window.root.unmount();window.root=createRoot(document.getElementById('root'));window.root.render(React.createElement(ProductIntake,{businessId:'controls',products:[],defaultUnit:'piece',create:async()=>{throw new Error('Reference import must not create inventory.')},scan:async()=>undefined,openProduct:draft=>{window.referenceDraft=draft}}))});await page.getByText('Add products from a photo, barcode or file',{exact:true}).click();await page.getByLabel('CSV product file',{exact:true}).setInputFiles({name:'supplier.csv',mimeType:'text/csv',buffer:Buffer.from('name,barcode,price,cost,stock,unit\nAcme Soap,4006381333931,999,40,200,piece\nAcme Juice,1234567890128,500,10,500,bottle')});await page.getByRole('button',{name:'Save as offline reference catalogue'}).click();await page.getByText('Saved 2 barcode references',{exact:false}).waitFor();await page.getByLabel('Barcode',{exact:true}).fill('4006381333931');await page.getByRole('button',{name:'Find product details'}).click();await page.waitForFunction(()=>window.referenceDraft?.name==='Acme Soap');const reference=await page.evaluate(()=>window.referenceDraft);assert.equal(reference.price,undefined);assert.equal(reference.stock,undefined);assert.equal(reference.cost,undefined);assert.equal(reference.unit,'piece');await page.getByText('Search your offline reference catalogue',{exact:true}).click();await page.getByLabel('Product name begins with').fill('Acme');await page.getByRole('button',{name:'Search catalogue',exact:true}).click();await page.getByRole('button',{name:'Acme Juice / 1234567890128'}).click();await page.waitForFunction(()=>window.referenceDraft?.name==='Acme Juice')
 assert.deepEqual(errors,[]);console.log('PASS: owner checkbox selection, preserved catalogue entries, workspace starter units PWA API permissions, linked invoice-wallet payment, birthday editing and offline supplier reference import/search')
}finally{await browser.close();await server.close()}
