import { useEffect, useState } from 'react'
import { AsyncButton, AsyncForm, SubmitButton } from './AsyncControls'
import { checkoutTillId } from './lib/checkoutTill'
export function BusinessBackup({ headers }: { headers: Record<string, string> }) {
  const [password, setPassword] = useState(''), [ownerPassword, setOwnerPassword] = useState(''), [archive, setArchive] = useState<unknown>(null), [confirmation, setConfirmation] = useState(''), [open, setOpen] = useState(false), [message, setMessage] = useState('')
  const [scheduled,setScheduled]=useState<{enabled:boolean;directory?:string;lastAt?:string;lastError?:string}|null>(null)
  async function schedule(action:string) {
    const bridge=window.stockroomDesktop?.scheduledBackups;if(!bridge)throw new Error('Scheduled backups require the updated Windows app.')
    const result=await bridge({action,token:headers.Authorization.replace(/^Bearer /,''),password:action==='configure'?password:undefined,tillId:checkoutTillId()});setScheduled(result);if(action==='configure')setPassword('')
  }
  useEffect(()=>{
    const bridge=window.stockroomDesktop?.scheduledBackups;if(!bridge)return
    let active=true
    const refresh=()=>{void bridge({action:'status',token:headers.Authorization.replace(/^Bearer /,'')}).then(result=>{if(active)setScheduled(result)}).catch(error=>{if(active)setMessage(error.message)})}
    refresh();const timer=setInterval(refresh,30000);return()=>{active=false;clearInterval(timer)}
  },[headers.Authorization])
  async function request(path: string, body: unknown) {
    const response = await fetch(path, { method: 'POST', headers: { ...headers, 'Content-Type': 'application/json', 'X-Stockroom-Till': checkoutTillId() }, body: JSON.stringify(body) })
    const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Backup operation failed.'); return data
  }
  return <section className="panel settings-form"><h3>Business backup and restore</h3><p>Download a password-protected copy of this Windows checkout’s database to another drive or secure storage. Keep the password separately. A copy left on the same computer cannot protect against loss of that computer.</p><p>Restore replaces local records on this checkout. Use the same app database version. For lost hardware, first use lost-till recovery. Current staff access and sign-in credentials are preserved.</p><label>Backup file password (at least 12 characters)<input type="password" minLength={12} maxLength={256} value={password} onChange={e => setPassword(e.target.value)} autoComplete="new-password" /></label><AsyncButton className="primary-button" disabled={password.length < 12} onClick={async () => {
    const data = await request('/api/backups/download', { backupPassword: password }); const url = URL.createObjectURL(new Blob([JSON.stringify(data.archive)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = `stockroom-backup-${new Date().toISOString().slice(0,10)}.json`; link.click(); setTimeout(() => URL.revokeObjectURL(url),1000); setMessage('Encrypted backup downloaded. Store it outside this computer.'); setPassword('')
  }}>Download encrypted backup</AsyncButton>{window.stockroomDesktop?.scheduledBackups && <><h4>Daily scheduled backups</h4><p>Runs while the Windows app is open. Choose an external drive or a folder synchronized to secure storage; keep it available. Backups are retained until you remove them from that folder.</p><AsyncButton className="filter-button" disabled={password.length<12} onClick={()=>schedule('configure')}>Choose folder and enable daily backups</AsyncButton>{scheduled?.enabled && <><p>Folder: {scheduled.directory}</p><p>Last successful backup: {scheduled.lastAt?new Date(scheduled.lastAt).toLocaleString():'None yet'}</p><AsyncButton className="filter-button" onClick={()=>schedule('run')}>Back up now to selected folder</AsyncButton><AsyncButton className="filter-button" onClick={()=>schedule('disable')}>Disable scheduled backups</AsyncButton></>}{scheduled?.lastError&&<p role="alert">Backup needs attention: {scheduled.lastError}</p>}</>}<label>Choose backup to restore<input type="file" accept=".json" onChange={async e => { setArchive(null); setMessage(''); try { const file=e.target.files?.[0]; if (!file) return; if(file.size>50_000_000) throw new Error('Backup is too large.'); setArchive(JSON.parse(await file.text())) } catch(error) { setMessage(error instanceof Error ? error.message : 'Invalid backup.') } }} /></label><button type="button" className="filter-button" disabled={!archive} onClick={() => { setOpen(true); setOwnerPassword(''); setConfirmation('') }}>Review restore</button>{message && <p role="status">{message}</p>}
  {open && <div className="modal-backdrop"><AsyncForm role="alertdialog" aria-modal="true" aria-labelledby="backup-restore-title" className="modal settings-form" onSubmit={async () => { await request('/api/backups/restore', { archive, backupPassword: password, ownerPassword, confirmation }); setOpen(false); setPassword(''); setOwnerPassword(''); window.location.reload() }}><h3 id="backup-restore-title">Replace this checkout’s records?</h3><p>This replaces local records with the selected backup. Work saved after the backup may be lost unless it synchronized. Stop other staff using this checkout and synchronize first. A local safety copy is created before restoration. The app checks and upgrades supported older backup structures automatically. If this backup is not supported, your current records are kept and the app explains how to get help.</p><label>Password used for this backup<input required type="password" minLength={12} maxLength={256} value={password} onChange={e=>setPassword(e.target.value)} /></label><label>Current owner password<input required type="password" value={ownerPassword} onChange={e=>setOwnerPassword(e.target.value)} autoComplete="current-password" /></label><label>Type RESTORE<input required value={confirmation} onChange={e=>setConfirmation(e.target.value)} /></label><div className="closure-actions"><button type="button" className="filter-button" onClick={()=>{setOpen(false);setOwnerPassword('')}}>Cancel</button><SubmitButton className="closure-confirm" disabled={confirmation!=='RESTORE'||!password}>Confirm restore</SubmitButton></div></AsyncForm></div>}</section>
}
