import { catalogueStarters, missingStarters, type CatalogueStarter } from '../server/catalogue-starters.mjs'
import { useState } from 'react'
import { WorkspaceHelp } from './WorkspaceHelp'
export function CatalogueStarters({kind,industry='general',existing,add}:{kind:string;industry?:string;existing:Array<{name:string}>;add:(item:CatalogueStarter)=>void}){
 const [query,setQuery]=useState('')
 const choices=missingStarters(catalogueStarters(kind,industry),existing)
 const filtered=choices.filter(row=>`${row.name} ${row.category} ${row.unit}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()))
 return <details className="panel"><summary>Preloaded catalogue starters</summary><WorkspaceHelp title="Starter suggestions"><p>Choose a common name, then review and save it as your own catalogue entry. These are not supplier records: set the right product or menu name, category, unit, selling price, cost and opening stock. Barcode is optional; scan or enter one if you have it. Stockroom generates an SKU when you save a product with the SKU field blank. Starter suggestions do not include manufacturer barcodes, assumed prices or stock counts.</p></WorkspaceHelp>{choices.length>0?<><label htmlFor="catalogue-starter-search">Find a starter<input id="catalogue-starter-search" type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search names, categories or units" /></label><label>Add catalogue starter<select value="" disabled={!filtered.length} onChange={event=>{const item=filtered.find(row=>row.id===event.target.value);if(item)add(item)}}><option value="">{filtered.length?`Choose from ${filtered.length} suggestions`: 'No matching suggestions'}</option>{filtered.map(row=><option key={row.id} value={row.id}>{row.name} — {row.category} / {row.unit}</option>)}</select></label><p>{choices.length} starter suggestions available. Existing entries are left untouched.</p></>:<p>All starter suggestions are already in this catalogue. Add your own at any time.</p>}</details>
}
