import { useEffect, useState } from 'react'
import { createPortal, flushSync } from 'react-dom'
import { AsyncForm, AsyncButton, SubmitButton } from './AsyncControls'
import { posRequest, DigitalReceipt } from './PosTools'
import { SplitPaymentFields } from './SplitPaymentFields'
import { PosProviderSelect } from './PosProviderSelect'
import { CounterRefund } from './CounterService'
import { churchSummary } from '../server/church-ledger.mjs'
import { businessDate } from '../server/report-timezone.mjs'
import { printDocument } from './lib/printing'
import type { Sale } from './types'
const fresh=()=>({id:'service-job:'+crypto.randomUUID(),commandId:crypto.randomUUID(),expectedUpdatedAt:'',type:'pledge',fundId:'',donorId:'',title:'',amount:'',dueDate:''})
const csv=(value:unknown)=>{let text=String(value??'');if(/^\s*[=+@-]/.test(text))text="'"+text;return '"'+text.replaceAll('"','""')+'"'}
export function ChurchCollections({headers,storageKey,manager,providers,print,beforeSend}:{headers:Record<string,string>;storageKey:string;manager:boolean;providers:string[];print:(sale:Sale)=>Promise<void>;beforeSend:()=>Promise<void>}) {
  const key=storageKey+':church'
  const [restored]=useState(()=>{try{return JSON.parse(localStorage.getItem(key)||'{}')}catch{return {}}})
  const [draft,setDraft]=useState(()=>({...fresh(),...restored.draft})),[creating,setCreating]=useState(Boolean(restored.creating)),[selected,setSelected]=useState(restored.selected||''),[pay,setPay]=useState<any>(restored.pay||null),[identity,setIdentity]=useState<any>(restored.identity||null)
  const [data,setData]=useState<any>({jobs:[],funds:[],donors:[],returns:[],timeZone:'UTC'}),[message,setMessage]=useState(''),[error,setError]=useState(''),[receipt,setReceipt]=useState<Sale|null>(null),[refund,setRefund]=useState<Sale|null>(null)
  const [search,setSearch]=useState(''),[filter,setFilter]=useState('all')
  const [donorId,setDonorId]=useState(''),[fundId,setFundId]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[statementPrint,setStatementPrint]=useState(false),[cancel,setCancel]=useState<any>(null)
  const job=data.jobs.find((row:any)=>row.id===selected),summary=churchSummary(data.jobs,data.returns,{donorId,fundId,from,to,timeZone:data.timeZone}),today=businessDate(new Date().toISOString(),data.timeZone)
  const money=(amount:number,currency:string)=>new Intl.NumberFormat(undefined,{style:'currency',currency}).format(amount)
  async function reload(){const result=await posRequest('/api/pos/church',headers);setData(result);return result}
  useEffect(()=>{let active=true;const load=()=>{void posRequest('/api/pos/church',headers).then(result=>{if(active){setData(result);setError('')}}).catch(e=>{if(active)setError(e.message)})};load();const timer=setInterval(load,10000);window.addEventListener('stockroom-data-refreshed',load);return()=>{active=false;clearInterval(timer);window.removeEventListener('stockroom-data-refreshed',load)}},[headers.Authorization,headers['X-Stockroom-Branch']])
  useEffect(()=>{try{localStorage.setItem(key,JSON.stringify({draft,creating,selected,pay,identity}))}catch{setError('This collection draft could not be saved. Keep this screen open.')}},[key,draft,creating,selected,pay,identity])
  async function send(path:string,input:any){const result=await posRequest(path,headers,input);await reload();window.dispatchEvent(new Event('stockroom-data-refreshed'));return result}
  const balance=(row:any)=>{const paid=row.payments.reduce((total:number,entry:any)=>total+Math.round(entry.sale.total*100),0);const refunded=data.returns.filter((record:any)=>row.payments.some((entry:any)=>entry.sale.id===record.saleId)).reduce((total:number,record:any)=>total+Math.round(record.total*100),0);return {net:(paid-refunded)/100,due:row.status==='cancelled'?0:Math.max(0,Math.round(row.pricing.total*100)-paid+refunded)/100}}
  function beginPayment(){setReceipt(null);setPay({id:job.id,commandId:crypto.randomUUID(),expectedUpdatedAt:job.updatedAt,amount:String(balance(job).due),method:'cash',cash:'',provider:'',reference:'',parts:[{method:'cash',amount:'',provider:'',reference:''},{method:'bank-transfer',amount:'',provider:'',reference:''}]})}
  function exportStatement(){if(from&&to&&from>to){setError('Choose a date range with the start before the end.');return}const rows=[['Date','Entry','Donor','Fund','Currency','Amount','Receipt/reference','Pledge'],...summary.rows.map(row=>[row.date,row.kind,row.donor,row.fund,row.currency,row.amount,row.reference,row.pledgeId])];const url=URL.createObjectURL(new Blob([rows.map(row=>row.map(csv).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='donor-statement-'+today+'.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  const statement=<><h2>Donation statement</h2><p>{donorId?data.donors.find((row:any)=>row.id===donorId)?.name:'All donors'} / {fundId?data.funds.find((row:any)=>row.id===fundId)?.name:'All funds'}</p><p>{from||'Beginning'} to {to||today} / {data.timeZone} / This branch only</p>{summary.rows.map(row=><p key={row.id}>{row.date} / {row.kind} / {row.donor} / {row.fund} / {money(row.amount,row.currency)} / {row.reference}</p>)}{summary.funds.map(row=><p key={row.fundId+row.currency}>{row.fund}: received {money(row.received,row.currency)}, refunded {money(row.refunded,row.currency)}, net {money(row.net,row.currency)}</p>)}<p>Accounting record of received contributions and refunds. Not a tax certificate. Pledges are commitments, not money received.</p></>
  return <section className="church-collections"><section className="panel"><h2>Church collections</h2><p>Track funds, registered donors and pledges. A saved pledge or prepared donation records no money until payment is saved. Confirm bank transfers or terminal payments externally.</p><div className="report-actions"><button type="button" className="primary-button" disabled={Boolean(pay)} onClick={()=>{if(!creating)setDraft(fresh());setCreating(true);setSelected('');setPay(null)}}>New pledge / donation</button><AsyncButton className="filter-button" onClick={reload}>Refresh collections</AsyncButton>{manager&&['church-fund','church-donor'].map(kind=><button type="button" className="filter-button" key={kind} onClick={()=>setIdentity({kind,id:kind+':'+crypto.randomUUID(),action:'create',commandId:crypto.randomUUID(),expectedUpdatedAt:'',name:'',phone:''})}>{kind==='church-fund'?'Add fund':'Add donor'}</button>)}</div>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</section>
    {identity&&manager&&<AsyncForm className="panel settings-form" onSubmit={async()=>{await send('/api/pos/church',identity);setIdentity(null);setMessage('Fund or donor saved. History is preserved.')}}><h3>{identity.action==='archive'?'Archive record':identity.kind==='church-fund'?'New fund':'New donor'}</h3>{identity.action==='create'?<><label>{identity.kind==='church-fund'?'Fund name':'Donor name'}<input required maxLength={200} value={identity.name} onChange={e=>setIdentity({...identity,name:e.target.value})}/></label>{identity.kind==='church-donor'&&<label>Donor phone<input maxLength={80} value={identity.phone} onChange={e=>setIdentity({...identity,phone:e.target.value})}/></label>}</>:<p>{identity.name} will be unavailable for new commitments. Existing commitments, receipts and statements remain.</p>}<SubmitButton className={identity.action==='archive'?'closure-confirm':'primary-button'}>Confirm fund or donor</SubmitButton><button type="button" className="filter-button" onClick={()=>setIdentity(null)}>Cancel</button></AsyncForm>}
    {creating&&<AsyncForm className="panel settings-form" onSubmit={async()=>{if(!/^\d+(?:\.\d{1,2})?$/.test(draft.amount)||Number(draft.amount)<=0)throw new Error('Enter a positive amount with up to two decimals.');const result=await send('/api/pos/service-jobs',{id:draft.id,commandId:draft.commandId,expectedUpdatedAt:'',title:draft.title,customerName:'Church donor',customerPhone:'',note:'',dueDate:draft.type==='pledge'?draft.dueDate:'',church:{type:draft.type,fundId:draft.fundId,donorId:draft.donorId},lines:[{id:'contribution',description:draft.title,quantity:1,price:Number(draft.amount)}]});setSelected(result.job.id);setCreating(false);setDraft(fresh());setMessage('Commitment saved. No payment was recorded.')} }><h3>New pledge / donation</h3><label>Collection type<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value})}><option value="pledge">Pledge - track outstanding commitment</option><option value="donation">One-off donation - prepare receipt</option></select></label><label>Collection fund<select required value={draft.fundId} onChange={e=>setDraft({...draft,fundId:e.target.value})}><option value="">Choose fund</option>{data.funds.filter((row:any)=>row.status==='active').map((row:any)=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label>Collection donor<select required={draft.type==='pledge'} value={draft.donorId} onChange={e=>setDraft({...draft,donorId:e.target.value})}><option value="">Anonymous (one-off donations only)</option>{data.donors.filter((row:any)=>row.status==='active').map((row:any)=><option key={row.id} value={row.id}>{row.name} / {row.phone} / {row.id.slice(-8)}</option>)}</select></label><label>Collection purpose<input required maxLength={150} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Commitment amount<input required type="number" min="0.01" step="0.01" value={draft.amount} onChange={e=>setDraft({...draft,amount:e.target.value})}/></label>{draft.type==='pledge'&&<label>Pledge due date<input type="date" value={draft.dueDate} onChange={e=>setDraft({...draft,dueDate:e.target.value})}/></label>}<SubmitButton className="primary-button">Save commitment</SubmitButton><button type="button" className="filter-button" onClick={()=>setCreating(false)}>Cancel</button></AsyncForm>}
    {job&&!creating&&<section className="panel"><h3>{job.title}</h3><p>{job.church.type==='pledge'?'Pledge':'One-off donation'} / {job.church.donorName} / {job.church.fundName} / {job.status==='cancelled'?'Cancelled':'Active'}</p><p>Commitment: {money(job.pricing.total,job.currency)} / Net received: {money(balance(job).net,job.currency)} / {job.church.type==='pledge'?'Outstanding':'Amount remaining to collect'}: {money(balance(job).due,job.currency)}</p>{job.dueDate&&<p>Due {job.dueDate}{job.dueDate<today&&balance(job).due>0?' / Overdue':''}</p>}{balance(job).due>0&&!pay&&<button type="button" className="primary-button" onClick={beginPayment}>Receive contribution</button>}{manager&&job.status!=='cancelled'&&<button type="button" className="filter-button" onClick={()=>setCancel({id:job.id,commandId:crypto.randomUUID(),expectedUpdatedAt:job.updatedAt,status:'cancelled'})}>Cancel commitment</button>}{cancel&&<AsyncForm onSubmit={async()=>{await send('/api/pos/service-jobs/status',cancel);setCancel(null);setPay(null)}}><p>Refund all retained contributions before cancelling. Cancellation preserves records.</p><SubmitButton className="closure-confirm">Confirm commitment cancellation</SubmitButton><button type="button" className="filter-button" onClick={()=>setCancel(null)}>Cancel</button></AsyncForm>}
      {pay&&<AsyncForm className="settings-form" onSubmit={async()=>{const result=await send('/api/pos/service-jobs/pay',pay);setReceipt(result.sale);setPay(null);setMessage('Contribution saved. One receipt records the payment.')}}><label>Contribution amount<input required type="number" min="0.01" step="0.01" value={pay.amount} onChange={e=>setPay({...pay,amount:e.target.value})}/></label><label>Contribution method<select value={pay.method} onChange={e=>setPay({...pay,method:e.target.value})}><option value="cash">Cash</option><option value="bank-transfer">Bank transfer</option><option value="external-pos">External POS</option><option value="multiple">Cash / card / transfer together</option></select></label>{pay.method==='multiple'?<SplitPaymentFields parts={pay.parts} total={Number(pay.amount)} onChange={parts=>setPay({...pay,parts})} providers={providers} money={amount=>money(amount,job.currency)}/>:pay.method==='cash'?<label>Contribution cash received<input type="number" min="0" step="0.01" value={pay.cash} onChange={e=>setPay({...pay,cash:e.target.value})}/></label>:<>{pay.method==='bank-transfer'?<label>Contribution bank<input required value={pay.provider} onChange={e=>setPay({...pay,provider:e.target.value})}/></label>:<PosProviderSelect providers={providers} value={pay.provider} onChange={provider=>setPay({...pay,provider})}/>}<label>Contribution reference<input required value={pay.reference} onChange={e=>setPay({...pay,reference:e.target.value})}/></label></>}{pay.expectedUpdatedAt!==job.updatedAt&&<><p role="alert">The commitment changed. Retry an interrupted payment using its original entry, or review the current balance before starting a new payment.</p><button type="button" className="filter-button" onClick={()=>setPay({...pay,commandId:crypto.randomUUID(),expectedUpdatedAt:job.updatedAt,amount:String(balance(job).due)})}>Review current contribution balance</button></>}<SubmitButton className="primary-button">Save contribution</SubmitButton><button type="button" className="filter-button" onClick={()=>setPay(null)}>Cancel</button></AsyncForm>}
      {job.payments.map((entry:any)=><div className="customer-row" key={entry.sale.id}><p>{entry.sale.paymentDetails.receipt.number} / {money(entry.sale.total,job.currency)}</p><AsyncButton className="filter-button" onClick={()=>print(entry.sale)}>Print contribution receipt</AsyncButton><DigitalReceipt sale={entry.sale} headers={headers} beforeSend={beforeSend}/>{manager&&<button type="button" className="filter-button" onClick={()=>setRefund(entry.sale)}>Refund contribution</button>}</div>)}{receipt&&<p role="status">Receipt {receipt.paymentDetails?.receipt?.number} saved.</p>}
    </section>}
    {!creating&&<section className="panel"><h3>Pledges and prepared donations</h3><label>Find commitment<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Donor, phone, fund or purpose"/></label><label>Show commitments<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All commitments</option><option value="pledges">Pledges</option><option value="unpaid">Outstanding commitments</option><option value="overdue">Overdue pledges</option></select></label>{data.jobs.filter((row:any)=>[row.title,row.church.donorName,row.church.donorPhone,row.church.fundName,row.id].join(' ').toLowerCase().includes(search.toLowerCase())&&(filter==='all'||filter==='pledges'&&row.church.type==='pledge'||filter==='unpaid'&&balance(row).due>0||filter==='overdue'&&row.church.type==='pledge'&&row.dueDate&&row.dueDate<today&&balance(row).due>0)).map((row:any)=><button type="button" className="filter-button job-list-item" key={row.id} disabled={Boolean(pay)} onClick={()=>{setSelected(row.id);setPay(null)}}>{row.title} / {row.church.donorName} / {row.church.fundName} / {row.church.type==='pledge'?'Outstanding':'To collect'} {money(balance(row).due,row.currency)}{row.status==='cancelled'?' / Cancelled':''}{row.dueDate<today&&row.dueDate&&balance(row).due>0?' / Overdue':''}</button>)}</section>}
    {manager&&<section className="panel"><h3>Fund contribution totals and donor statements</h3><label>Statement donor<select value={donorId} onChange={e=>setDonorId(e.target.value)}><option value="">All donors, including anonymous</option>{data.donors.map((row:any)=><option key={row.id} value={row.id}>{row.name} / {row.phone} / {row.id.slice(-8)}</option>)}</select></label><label>Statement fund<select value={fundId} onChange={e=>setFundId(e.target.value)}><option value="">All funds</option>{data.funds.map((row:any)=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label>Statement from<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Statement to<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label>{statement}<button type="button" className="filter-button" onClick={exportStatement}>Export donor statement</button><AsyncButton className="filter-button" onClick={async()=>{if(from&&to&&from>to)throw new Error('Choose a valid date range.');flushSync(()=>setStatementPrint(true));try{await printDocument('order')}finally{setStatementPrint(false)}}}>Print donor statement</AsyncButton><p>Outstanding pledges (all dates):</p>{summary.pledges.map(row=><p key={row.id}>{row.donor} / {row.title} / {money(row.outstanding,row.currency)}{row.dueDate?' / Due '+row.dueDate:''}</p>)}<details><summary>Archive funds and donors</summary>{[...data.funds,...data.donors].filter((row:any)=>row.status==='active').map((row:any)=><button type="button" className="filter-button" key={row.id} onClick={()=>setIdentity({kind:row.kind,id:row.id,name:row.name,action:'archive',commandId:crypto.randomUUID(),expectedUpdatedAt:row.updatedAt})}>Archive {row.name}</button>)}</details></section>}
    {refund&&manager&&<CounterRefund title="Refund contribution" sale={refund} returns={data.returns} money={amount=>money(amount,refund.currency||'USD')} close={()=>setRefund(null)} save={async input=>{await send('/api/pos/returns',input);setRefund(null);setMessage('Refund saved. Fund totals and pledge balance reflect it.')}}/>}
    {statementPrint&&createPortal(<div className="print-order thermal-document">{statement}</div>,document.body)}
  </section>
}
