import { WorkspaceHelp } from './WorkspaceHelp'
import { useId, useState } from 'react'
import { AsyncForm, SubmitButton } from './AsyncControls'
import { posRequest } from './PosTools'
import { businessModes, productCatalogueOptions, type BusinessMode, type CatalogueWorkspace } from '../server/shop-profile.mjs'
import type { Product } from './types'

export type RecipeIngredient = { productId: string; quantity: number }
export type RecipeMenuItem = { id: string; name: string; type: 'prepared' | 'stock'; recipe?: RecipeIngredient[]; options: Array<{ id: string; name: string; recipe?: RecipeIngredient[] }> }

export function CounterRecipes({ items, menuUpdatedAt, products, headers, money, save, refresh, industry = 'food-service', catalogueUnits, catalogueWorkspace = 'order-counter' }: {
  items: RecipeMenuItem[]; menuUpdatedAt: string; products: Product[]; headers: Record<string,string>; money: (value: number) => string;
  industry?: BusinessMode;
  catalogueUnits?: string[];
  catalogueWorkspace?: CatalogueWorkspace;
  save: (id: string, recipe: RecipeIngredient[], extras: Record<string, RecipeIngredient[]>, expectedUpdatedAt: string) => Promise<void>; refresh: () => Promise<void>
}) {
  const [revision, setRevision] = useState('')
  const [selected, setSelected] = useState('')
  const [recipe, setRecipe] = useState<RecipeIngredient[]>([])
  const [extras, setExtras] = useState<Record<string, RecipeIngredient[]>>({})
  const [message, setMessage] = useState('')
  const [addedUnits, setAddedUnits] = useState<string[]>([])
  const units = [...new Set([businessModes[industry].unit, ...(catalogueUnits?.length ? catalogueUnits : productCatalogueOptions(industry).units), ...addedUnits])]
  const [ingredientUnit, setIngredientUnit] = useState(businessModes[industry].unit)
  const item = items.find(item => item.id === selected)
  const cost = (rows: RecipeIngredient[]) => rows.reduce((sum, row) => sum + row.quantity * (products.find(product => product.id === row.productId)?.cost || 0), 0)
  return <section className="panel"><h2>Recipes and ingredients</h2><WorkspaceHelp title="Recipes"><p>A recipe lists the ingredients for one portion, in each stock product's unit. For example, if flour is stocked in kg, enter 0.125 for 125 grams. Extras add their own ingredients. Save the recipe before taking new orders.</p></WorkspaceHelp>
    <label htmlFor="counter-recipe-item">Prepared menu item</label><select id="counter-recipe-item" value={selected} onChange={event => { const item = items.find(item => item.id === event.target.value); setSelected(event.target.value); setRevision(menuUpdatedAt); setRecipe(structuredClone(item?.recipe || [])); setExtras(Object.fromEntries((item?.options || []).map(option => [option.id, structuredClone(option.recipe || [])]))); setMessage('') }}><option value="">Choose a prepared item</option>{items.filter(item => item.type === 'prepared').map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select>
    {item && <AsyncForm onSubmit={async () => { await save(item.id, recipe, extras, revision); setSelected(''); setMessage('Recipe saved. Existing orders keep their original ingredients.') }}><h3>{item.name}: one portion</h3><IngredientRows rows={recipe} products={products} change={setRecipe} /><p>Estimated ingredient cost per portion: {money(cost(recipe))}. Actual preparation cost uses the stock batches consumed.</p>{item.options.map(option => <details key={option.id}><summary>{option.name}: extra ingredients</summary><IngredientRows rows={extras[option.id] || []} products={products} change={rows => setExtras({ ...extras, [option.id]: rows })} /><p>Extra ingredient cost: {money(cost(extras[option.id] || []))}</p></details>)}<SubmitButton className="primary-button">Save recipe</SubmitButton></AsyncForm>}
    {message && <p role="status">{message}</p>}
    <details><summary>Ingredient stock</summary><WorkspaceHelp title="Recipes"><p>Use one stock unit consistently for purchases, restocking and recipes. Current recipes consume stock when preparation starts, on the original order till. Refunds do not restore cooked ingredients.</p></WorkspaceHelp>
      <AsyncForm className="settings-form" onSubmit={async event => { const element = event.currentTarget; const form = new FormData(element); const unit = String(form.get('unit') || ''); await posRequest('/api/products', headers, { name: form.get('name'), sku: 'ING-' + crypto.randomUUID(), category: 'Ingredients', unit, cost: Number(form.get('cost')), price: 0, stock: Number(form.get('stock')), reorder: Number(form.get('reorder')) }); let optionMessage = ''; if (ingredientUnit === '__custom__' && unit) { setAddedUnits(current => current.some(value => value.toLocaleLowerCase() === unit.toLocaleLowerCase()) ? current : [...current, unit]); try { const response = await fetch('/api/settings/shop-profile/options', { method: 'POST', headers: { 'Content-Type': 'application/json', ...headers }, body: JSON.stringify({ workspace: catalogueWorkspace, field: 'units', value: unit }) }); const result = await response.json().catch(() => ({})); if (!response.ok) optionMessage = result.error || 'The ingredient was saved, but its unit was not added to workspace choices.' } catch { optionMessage = 'The ingredient was saved. Its new unit is available here but could not be saved to workspace settings.' } } element.reset(); setIngredientUnit(businessModes[industry].unit); await refresh(); setMessage(optionMessage || 'Ingredient saved. Add it to a recipe.') }}><h3>Add ingredient</h3><label>Ingredient name<input name="name" required maxLength={100} /></label><label htmlFor="counter-ingredient-unit">Stock unit for {businessModes[industry].label}</label><select id="counter-ingredient-unit" value={ingredientUnit === '__custom__' ? '' : ingredientUnit} onChange={event => setIngredientUnit(event.target.value)}><option value="">Choose a unit</option>{units.map(unit => <option key={unit} value={unit}>{unit}</option>)}<option value="__custom__">Other (please specify)</option></select>{ingredientUnit === '__custom__' ? <input aria-label="Specify ingredient stock unit" name="unit" required maxLength={30} placeholder="Enter stock unit" /> : <input type="hidden" name="unit" value={ingredientUnit} />}<label>Purchase cost per stock unit<input name="cost" type="number" min="0" step="0.01" required /></label><label>Opening ingredient stock<input name="stock" type="number" min="0" step="0.001" required /></label><label>Low-stock level<input name="reorder" type="number" min="0" step="0.001" defaultValue="0" required /></label><SubmitButton className="primary-button">Add ingredient</SubmitButton></AsyncForm>
      {products.filter(product => product.category === 'Ingredients' || items.some(item => [...(item.recipe || []), ...item.options.flatMap(option => option.recipe || [])].some(row => row.productId === product.id))).map(product => <AsyncForm className="customer-row" key={product.id} onSubmit={async event => { const element = event.currentTarget; const form = new FormData(element); await posRequest('/api/products/' + encodeURIComponent(product.id) + '/stock', headers, { amount: Number(form.get('amount')), reason: 'Ingredient restock' }); element.reset(); await refresh(); setMessage('Ingredient stock updated.') }}><strong>{product.name}: {product.stock} {product.unit} available</strong><label>Restock {product.name} ({product.unit})<input name="amount" type="number" min="0.001" step="0.001" required /></label><SubmitButton className="filter-button">Restock ingredient</SubmitButton></AsyncForm>)}<WorkspaceHelp title="Recipes"><p>Restocking here adds stock at its saved purchase cost. Use Purchasing for supplier invoices, new batch costs and expiry dates. Record spoilage through stock wastage, not a sale refund.</p></WorkspaceHelp>
    </details>
  </section>
}

function IngredientRows({ rows, products, change }: { rows: RecipeIngredient[]; products: Product[]; change: (rows: RecipeIngredient[]) => void }) {
  const prefix = useId()
  return <>{rows.map((row, index) => <div className="form-grid" key={index}><label htmlFor={prefix + index}>Ingredient</label><select id={prefix + index} required value={row.productId} onChange={event => change(rows.map((row, i) => i === index ? { ...row, productId: event.target.value } : row))}><option value="">Choose stock ingredient</option>{products.map(product => <option key={product.id} value={product.id}>{product.name} ({product.unit})</option>)}</select><label>Quantity per portion<input type="number" min="0.001" step="0.001" required value={row.quantity || ''} onChange={event => change(rows.map((row, i) => i === index ? { ...row, quantity: Number(event.target.value) } : row))} /></label><button className="filter-button" type="button" onClick={() => change(rows.filter((_, i) => i !== index))}>Remove ingredient</button></div>)}<button className="filter-button" type="button" disabled={rows.length >= 50} onClick={() => change([...rows, { productId: '', quantity: 0 }])}>Add recipe ingredient</button></>
}
