import { useState } from 'react'
import { AsyncButton } from './AsyncControls'
import { posRequest } from './PosTools'
import { copyMenuItems, menuCopyCandidates } from '../server/menu-copy.mjs'
type Item = {id:string;name:string;price:number;recipe?:Array<{productId:string;quantity:number}>;options:Array<{id:string;name:string;price:number;recipe?:Array<{productId:string;quantity:number}>}>;copiedFrom?:{menuId:string;itemId:string}}
export function MenuCopy<T extends Item>({items,restaurant,headers,money,onCopy,products}:{items:T[];restaurant:boolean;headers:Record<string,string>;money:(value:number)=>string;onCopy:(items:T[])=>void;products:Array<{id:string;name:string;unit:string}>}) {
 const [source,setSource]=useState<{id:string;items:T[]}|null>(null),[selected,setSelected]=useState<string[]>([]),[message,setMessage]=useState('')
 const ingredients=(rows:Item['recipe'])=>(rows||[]).map(row=>{const product=products.find(product=>product.id===row.productId);return (product?.name||row.productId)+' '+row.quantity+' '+(product?.unit||'stock units')}).join('; ')||'None'
 const from=restaurant?'takeaway':'restaurant', candidates=source?menuCopyCandidates(source,items):[]
 return <details className="panel"><summary>Copy menu items from {from}</summary><p>Synchronize first to load the other workspace's saved menu. Copy prices, availability, stock links, extras and recipes into this draft. Existing items are kept; the source menu and submitted orders stay unchanged. Save menu after reviewing. Copied items can be edited independently.</p>
 <AsyncButton className="filter-button" onClick={async()=>{const result=await posRequest(restaurant?'/api/pos/counter':'/api/pos/restaurant/counter',headers) as {menu:{id:string;items:T[]}};setSource(result.menu);setSelected([]);setMessage('')}}>Preview {from} menu</AsyncButton>
 {source&&<><p>{candidates.length} source items. Items with the same name or already copied from this source cannot be added again.</p>{candidates.map(({item,exists})=><div key={item.id}><label><input type="checkbox" disabled={exists} checked={!exists&&selected.includes(item.id)} onChange={event=>setSelected(current=>event.target.checked?[...current,item.id]:current.filter(id=>id!==item.id))}/>{item.name} / {money(item.price)}{exists?' / Already in this menu':''}</label><p>Recipe: {ingredients(item.recipe)}. Extras: {item.options.map(option=>option.name+' ('+money(option.price)+', '+ingredients(option.recipe)+')').join('; ')||'None'}.</p></div>)}<AsyncButton className="primary-button" disabled={!selected.length} onClick={()=>{const next=copyMenuItems(source,items,selected,restaurant);onCopy(next);setSelected([]);setMessage('Copied to your draft. Review prices, stock links and recipes, then Save menu.')}}>Add selected items to menu draft</AsyncButton><button type="button" className="filter-button" onClick={()=>{setSource(null);setSelected([]);setMessage('')}}>Cancel copy preview</button></>}{message&&<p role="status">{message}</p>}
 </details>
}
