import { useEffect, useState } from 'react'
import { AsyncForm, SubmitButton, AsyncButton } from './AsyncControls'
import { posRequest } from './PosTools'
import { WorkspaceHelp } from './WorkspaceHelp'
import type { Product, Customer } from './types'

export function OilPricing({headers,products,customers,storageKey,refresh,oil=true}:{headers:Record<string,string>;products:Product[];customers:Customer[];storageKey:string;refresh:()=>Promise<void>;oil?:boolean}) {
  const [records,setRecords]=useState<any[]>([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[loaded,setLoaded]=useState(false)
  const [draft,setDraft]=useState<any>(()=>{try{return JSON.parse(localStorage.getItem(storageKey)||'null')}catch{return null}})
  async function load(){const result=await posRequest('/api/pos',headers);setRecords(result.products);setLoaded(true)}
  useEffect(()=>{void load().catch(e=>setError(e.message))},[headers.Authorization,headers['X-Stockroom-Branch']])
  useEffect(()=>{try{if(draft)localStorage.setItem(storageKey,JSON.stringify(draft));else localStorage.removeItem(storageKey)}catch{setError('Pricing draft could not be saved. Keep this screen open.')}},[draft,storageKey])
  const product=products.find(row=>row.id===draft?.productId)
  function choose(productId:string){const saved=records.find(row=>row.productId===productId);setDraft(productId?{productId,commandId:crypto.randomUUID(),expectedUpdatedAt:saved?.updatedAt||'',bulk:(saved?.oilPricing?.bulk||[]).map((row:any)=>({minimum:String(row.minimum),price:String(row.price)})),customers:(saved?.oilPricing?.customers||[]).map((row:any)=>({...row,price:String(row.price)}))}:null)}
  return <section className="panel full-panel inventory-pricing-screen">
    <header className="inventory-pricing-heading"><div><h2>{oil?'Oil price tiers':'Product price tiers'}</h2><p>Set optional quantity and customer rates.</p></div><WorkspaceHelp inline title={oil?'About oil price tiers':'About product price tiers'}><p>Start with the saved product price. A qualifying bulk rate or a customer rate can replace it; a price entered manually on a sale takes priority over both.</p>{oil&&<p>Oil bulk quantities combine measured units and configured containers in the same basket.</p>}<p>Rates are saved per stock unit. Existing receipts keep their original prices.</p></WorkspaceHelp></header>
    {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
    <div className="inventory-pricing-select"><label>{oil?'Choose oil':'Choose product'}<select disabled={!loaded} value={draft?.productId||''} onChange={e=>choose(e.target.value)}><option value="">Select a product</option>{products.map(row=><option key={row.id} value={row.id}>{row.name} / {row.unit}</option>)}</select></label><AsyncButton className="filter-button" onClick={async()=>{await load();await refresh();setMessage('Prices refreshed. Your draft was kept.')}}>{oil?'Refresh oil prices':'Refresh product prices'}</AsyncButton></div>
    {!draft&&<div className="inventory-pricing-empty"><strong>Choose a product to manage its rates.</strong></div>}
    {draft&&<AsyncForm className="settings-form inventory-pricing-form" onSubmit={async()=>{const number=(value:string)=>{if(!/^\d+(?:\.\d{1,2})?$/.test(value))throw new Error('Enter prices with up to two decimals.');return Number(value)};await posRequest('/api/pos/oil-pricing',headers,{productId:draft.productId,commandId:draft.commandId,expectedUpdatedAt:draft.expectedUpdatedAt,value:{bulk:draft.bulk.map((row:any)=>({minimum:Number(row.minimum),price:number(row.price)})),customers:draft.customers.map((row:any)=>({customerId:row.customerId,price:number(row.price)}))}});await load();await refresh();setDraft(null);setMessage('Price tiers saved. Existing receipts keep their original prices.')}}>
      <section className="inventory-rate-group"><header><div><h3>Quantity rates</h3><p>Apply a lower price from a minimum quantity.</p></div><span>Per {product?.unit||'stock unit'}</span></header>{draft.bulk.map((row:any,index:number)=><fieldset key={index}><label>Minimum quantity<input required type="number" min="0.001" step="0.001" value={row.minimum} onChange={e=>setDraft({...draft,bulk:draft.bulk.map((item:any,i:number)=>i===index?{...item,minimum:e.target.value}:item)})}/></label><label>Unit price<input required type="number" min="0" step="0.01" value={row.price} onChange={e=>setDraft({...draft,bulk:draft.bulk.map((item:any,i:number)=>i===index?{...item,price:e.target.value}:item)})}/></label><button type="button" className="filter-button" onClick={()=>setDraft({...draft,bulk:draft.bulk.filter((_:any,i:number)=>i!==index)})}>Remove</button></fieldset>)}<button type="button" className="filter-button" disabled={draft.bulk.length>=30} onClick={()=>setDraft({...draft,bulk:[...draft.bulk,{minimum:'',price:''}]})}>Add quantity rate</button></section>
      <section className="inventory-rate-group"><header><div><h3>Customer rates</h3><p>Set a price for a specific customer.</p></div><span>Per {product?.unit||'stock unit'}</span></header>{draft.customers.map((row:any,index:number)=><fieldset key={index}><label>Customer<select required value={row.customerId} onChange={e=>setDraft({...draft,customers:draft.customers.map((item:any,i:number)=>i===index?{...item,customerId:e.target.value}:item)})}><option value="">Choose customer</option>{customers.map(customer=><option key={customer.id} value={customer.id}>{customer.name}{customer.phone&&` / ${customer.phone}`}</option>)}</select></label><label>Unit price<input required type="number" min="0" step="0.01" value={row.price} onChange={e=>setDraft({...draft,customers:draft.customers.map((item:any,i:number)=>i===index?{...item,price:e.target.value}:item)})}/></label><button type="button" className="filter-button" onClick={()=>setDraft({...draft,customers:draft.customers.filter((_:any,i:number)=>i!==index)})}>Remove</button></fieldset>)}<button type="button" className="filter-button" disabled={draft.customers.length>=200} onClick={()=>setDraft({...draft,customers:[...draft.customers,{customerId:'',price:''}]})}>Add customer rate</button></section>
      {draft.expectedUpdatedAt!==(records.find(row=>row.productId===draft.productId)?.updatedAt||'')&&<div className="inventory-pricing-conflict"><p role="alert">Saved product options changed. Review the current rates before replacing them.</p><button type="button" className="filter-button" onClick={()=>setDraft({...draft,expectedUpdatedAt:records.find(row=>row.productId===draft.productId)?.updatedAt||'',commandId:crypto.randomUUID()})}>Use reviewed product revision</button></div>}
      <footer className="inventory-pricing-actions"><button type="button" className="filter-button" onClick={()=>setDraft(null)}>Cancel</button><SubmitButton className="primary-button">{oil?'Save oil price tiers':'Save product price tiers'}</SubmitButton></footer>
    </AsyncForm>}
  </section>
}
