import { useEffect, useState } from 'react'
import { AsyncForm, SubmitButton, AsyncButton } from './AsyncControls'
import { posRequest } from './PosTools'
import type { Product, Customer } from './types'
export function OilPricing({headers,products,customers,storageKey,refresh,oil=true}:{headers:Record<string,string>;products:Product[];customers:Customer[];storageKey:string;refresh:()=>Promise<void>;oil?:boolean}) {
  const [records,setRecords]=useState<any[]>([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[loaded,setLoaded]=useState(false)
  const [draft,setDraft]=useState<any>(()=>{try{return JSON.parse(localStorage.getItem(storageKey)||'null')}catch{return null}})
  async function load(){const result=await posRequest('/api/pos',headers);setRecords(result.products);setLoaded(true)}
  useEffect(()=>{void load().catch(e=>setError(e.message))},[headers.Authorization,headers['X-Stockroom-Branch']])
  useEffect(()=>{try{if(draft)localStorage.setItem(storageKey,JSON.stringify(draft));else localStorage.removeItem(storageKey)}catch{setError('Pricing draft could not be saved. Keep this screen open.')}},[draft,storageKey])
  const product=products.find(row=>row.id===draft?.productId)
  function choose(productId:string){const saved=records.find(row=>row.productId===productId);setDraft(productId?{productId,commandId:crypto.randomUUID(),expectedUpdatedAt:saved?.updatedAt||'',bulk:(saved?.oilPricing?.bulk||[]).map((row:any)=>({minimum:String(row.minimum),price:String(row.price)})),customers:(saved?.oilPricing?.customers||[]).map((row:any)=>({...row,price:String(row.price)}))}:null)}
  return <section className="panel full-panel"><h2>{oil?'Oil price tiers':'Product price tiers'}</h2><p>{oil?'Retail uses the product or container price. Bulk thresholds count all measured units and configured containers of the same oil in this basket.':'Retail uses the saved product price. Bulk thresholds count the combined stock-unit quantity of the same product in this basket.'} Rates below are per stock unit; customer rates take priority over bulk rates. Explicit manual prices take priority over these rates.</p>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<label>{oil?'Oil pricing product':'Pricing product'}<select disabled={!loaded} value={draft?.productId||''} onChange={e=>choose(e.target.value)}><option value="">{oil?'Choose oil':'Choose product'}</option>{products.map(row=><option key={row.id} value={row.id}>{row.name} / {row.unit}</option>)}</select></label><AsyncButton className="filter-button" onClick={async()=>{await load();await refresh();setMessage('Prices refreshed. Your draft was kept.')}}>{oil?'Refresh oil prices':'Refresh product prices'}</AsyncButton>
    {draft&&<AsyncForm className="settings-form" onSubmit={async()=>{const number=(value:string)=>{if(!/^\d+(?:\.\d{1,2})?$/.test(value))throw new Error('Enter prices with up to two decimals.');return Number(value)};await posRequest('/api/pos/oil-pricing',headers,{productId:draft.productId,commandId:draft.commandId,expectedUpdatedAt:draft.expectedUpdatedAt,value:{bulk:draft.bulk.map((row:any)=>({minimum:Number(row.minimum),price:number(row.price)})),customers:draft.customers.map((row:any)=>({customerId:row.customerId,price:number(row.price)}))}});await load();await refresh();setDraft(null);setMessage('Price tiers saved. Existing receipts keep their original prices.')}}>
      <h3>Bulk prices per {product?.unit||'stock unit'}</h3>{draft.bulk.map((row:any,index:number)=><fieldset key={index}><label>Bulk minimum quantity<input required type="number" min="0.001" step="0.001" value={row.minimum} onChange={e=>setDraft({...draft,bulk:draft.bulk.map((item:any,i:number)=>i===index?{...item,minimum:e.target.value}:item)})}/></label><label>Bulk unit price<input required type="number" min="0" step="0.01" value={row.price} onChange={e=>setDraft({...draft,bulk:draft.bulk.map((item:any,i:number)=>i===index?{...item,price:e.target.value}:item)})}/></label><button type="button" className="filter-button" onClick={()=>setDraft({...draft,bulk:draft.bulk.filter((_:any,i:number)=>i!==index)})}>Remove bulk rate</button></fieldset>)}<button type="button" className="filter-button" disabled={draft.bulk.length>=30} onClick={()=>setDraft({...draft,bulk:[...draft.bulk,{minimum:'',price:''}]})}>Add bulk rate</button>
      <h3>Customer prices per {product?.unit||'stock unit'}</h3>{draft.customers.map((row:any,index:number)=><fieldset key={index}><label>Pricing customer<select required value={row.customerId} onChange={e=>setDraft({...draft,customers:draft.customers.map((item:any,i:number)=>i===index?{...item,customerId:e.target.value}:item)})}><option value="">Choose customer</option>{customers.map(customer=><option key={customer.id} value={customer.id}>{customer.name} / {customer.phone}</option>)}</select></label><label>Customer unit price<input required type="number" min="0" step="0.01" value={row.price} onChange={e=>setDraft({...draft,customers:draft.customers.map((item:any,i:number)=>i===index?{...item,price:e.target.value}:item)})}/></label><button type="button" className="filter-button" onClick={()=>setDraft({...draft,customers:draft.customers.filter((_:any,i:number)=>i!==index)})}>Remove customer rate</button></fieldset>)}<button type="button" className="filter-button" disabled={draft.customers.length>=200} onClick={()=>setDraft({...draft,customers:[...draft.customers,{customerId:'',price:''}]})}>Add customer rate</button>
      {draft.expectedUpdatedAt!==(records.find(row=>row.productId===draft.productId)?.updatedAt||'')&&<><p role="alert">Saved product options changed. Retry an interrupted save with its original command, or review the current saved rates before replacing them.</p><button type="button" className="filter-button" onClick={()=>setDraft({...draft,expectedUpdatedAt:records.find(row=>row.productId===draft.productId)?.updatedAt||'',commandId:crypto.randomUUID()})}>Use reviewed product revision</button></>}<SubmitButton className="primary-button">{oil?'Save oil price tiers':'Save product price tiers'}</SubmitButton><button type="button" className="filter-button" onClick={()=>setDraft(null)}>Cancel</button>
    </AsyncForm>}
  </section>
}
