export type PrintableOrder = { billSummary?: { subtotal: number; discount: number; addedTax: number; includedTax: number }; bill?: boolean; preparation?: boolean; customerName?: string; note?: string; amountPaid?: number; balanceDue?: number; id: string; businessName: string; currency: string; createdAt: string; items: Array<{ productId: string; productName: string; quantity: number; price: number }>; total: number }
export function OrderDocument({ order }: { order: PrintableOrder }) {
  const money = (amount: number) => new Intl.NumberFormat(undefined, { style: 'currency', currency: order.currency }).format(amount)
  return <div className="print-order thermal-document"><h2>{order.businessName}</h2><h1>{order.bill ? 'ITEMIZED BILL' : order.preparation ? 'PREPARATION TICKET' : 'ORDER REVIEW'}</h1><p>{order.bill ? 'Bill' : 'Order'}: {order.id}<br />{new Date(order.createdAt).toLocaleString()}</p>{order.customerName && <p>{order.bill ? 'Table / tab' : 'Customer / table'}: {order.customerName}</p>}{order.note && <p className="receipt-multiline">{order.note}</p>}
    <div className="thermal-lines">{order.items.map((item, index) => <div className="thermal-line" key={index}><strong>{item.productName}</strong><div className="thermal-line-amount"><span>{order.preparation ? `Qty: ${item.quantity}` : `${item.quantity} x ${money(item.price)}`}</span>{!order.preparation && <span>{money(Math.round(item.price * item.quantity * 100) / 100)}</span>}</div></div>)}</div>
    {!order.preparation && <section>{order.billSummary && <><p>Subtotal: {money(order.billSummary.subtotal)}</p>{order.billSummary.discount > 0 && <p>Discount: {money(order.billSummary.discount)}</p>}{order.billSummary.addedTax > 0 && <p>Tax added: {money(order.billSummary.addedTax)}</p>}{order.billSummary.includedTax > 0 && <p>Tax included: {money(order.billSummary.includedTax)}</p>}</>}<strong>{order.bill ? 'Bill total' : 'Total due'}: {money(order.total)}</strong>{order.bill && order.amountPaid != null && <p>Paid: {money(order.amountPaid)}</p>}{order.bill && order.balanceDue != null && <p><strong>Balance due: {money(order.balanceDue)}</strong></p>}</section>}
    <footer>{order.preparation ? 'For preparation only - not a payment receipt.' : order.bill ? order.balanceDue === 0 ? 'Paid bill - keep your payment receipt.' : (order.amountPaid || 0) > 0 ? 'Partially paid bill - not a payment receipt.' : 'This is an unpaid bill - not a payment receipt.' : 'Payment not recorded - please review with the cashier.'}</footer>
  </div>
}
