import type { Product } from './types'
import { customerOrderSettings } from '../server/customer-order-settings.mjs'
import { WorkspaceHelp } from './WorkspaceHelp'
import { useState } from 'react'
import { extraReasons, type PaymentPolicy } from '../server/payment.mjs'
export function PaymentPolicySettings({ products = [], value, onChange }: { products?: Product[]; value: PaymentPolicy; onChange: (policy: PaymentPolicy) => void }) {
  const [newProvider, setNewProvider] = useState('')
  const defaults = ['OPay', 'PalmPay', 'Moniepoint', 'Paga', 'Kuda', 'Access Bank', 'FirstBank', 'GTBank', 'UBA', 'Zenith Bank']
  const providers = [...new Set([...defaults, ...value.providers])]
  const addProvider = () => {
    const provider = newProvider.trim().replace(/\s+/g, ' ')
    if (!provider || value.providers.some(item => item.toLowerCase() === provider.toLowerCase())) return
    onChange({ ...value, providers: [...value.providers, provider] })
    setNewProvider('')
  }
  const ordering = { ...customerOrderSettings(value.customerOrdering), deliveryZones: value.customerOrdering?.deliveryZones || [] }
  const setOrdering = (patch: Partial<typeof ordering>) => onChange({ ...value, customerOrdering: { ...ordering, ...patch } })
  return <section><h3>Customer ordering</h3><p>These details are displayed publicly on your QR ordering page. Save business settings, then synchronize to publish them.</p>
    <label><input type="checkbox" checked={ordering.retailEnabled} onChange={e=>setOrdering({retailEnabled:e.target.checked})}/>Enable online retail ordering</label>{ordering.retailEnabled && <details><summary>Choose products to publish ({ordering.retailProductIds.length})</summary><p>Choose up to 2,000 products. Only selected products appear publicly, at their current retail price. Stock availability is confirmed by staff; an online request does not reserve goods.</p>{products.map(product=><label key={product.id}><input type="checkbox" disabled={!ordering.retailProductIds.includes(product.id)&&ordering.retailProductIds.length>=2000} checked={ordering.retailProductIds.includes(product.id)} onChange={e=>setOrdering({retailProductIds:e.target.checked?[...ordering.retailProductIds,product.id]:ordering.retailProductIds.filter(id=>id!==product.id)})}/>{product.name}</label>)}</details>}<label>Bank name<input maxLength={100} value={ordering.bankName} onChange={e => setOrdering({ bankName: e.target.value })} /></label>
    <label>Account name<input maxLength={120} value={ordering.accountName} onChange={e => setOrdering({ accountName: e.target.value })} /></label>
    <label>Account number<input maxLength={40} value={ordering.accountNumber} onChange={e => setOrdering({ accountNumber: e.target.value })} /></label>
    <label>Transfer instructions<textarea maxLength={300} value={ordering.transferInstructions} onChange={e => setOrdering({ transferInstructions: e.target.value })} /></label>
    <label><input type="checkbox" checked={ordering.deliveryEnabled} onChange={e => setOrdering({ deliveryEnabled: e.target.checked })} />Offer delivery on takeaway and retail QR orders</label>
    {ordering.deliveryEnabled && <label>Fixed delivery charge (before tax)<input type="number" min="0" max="1000000" step="0.01" value={ordering.deliveryFee} onChange={e => setOrdering({ deliveryFee: Number(e.target.value) })} /></label>}
    {ordering.deliveryEnabled && <section><h4>Delivery areas and charges</h4><p>Leave this list empty to use the fixed charge. Otherwise customers must choose one of these areas. Existing orders retain their original charge.</p>{ordering.deliveryZones.map(zone => <div key={zone.id}><label>Area name<input maxLength={100} value={zone.name} onChange={e => setOrdering({deliveryZones:ordering.deliveryZones.map(row=>row.id===zone.id?{...row,name:e.target.value}:row)})}/></label><label>Charge before tax<input type="number" min="0" max="1000000" step="0.01" value={zone.fee} onChange={e => setOrdering({deliveryZones:ordering.deliveryZones.map(row=>row.id===zone.id?{...row,fee:Number(e.target.value)}:row)})}/></label><button type="button" className="filter-button" onClick={()=>setOrdering({deliveryZones:ordering.deliveryZones.filter(row=>row.id!==zone.id)})}>Remove area</button></div>)}<button type="button" className="filter-button" disabled={ordering.deliveryZones.length>=50} onClick={()=>setOrdering({deliveryZones:[...ordering.deliveryZones,{id:crypto.randomUUID(),name:'New delivery area',fee:ordering.deliveryFee}]})}>Add delivery area</button></section>}
    <h3>Wallet payments</h3>
    <label className="checkbox-label"><input type="checkbox" checked={value.allowWallet} onChange={e => onChange({ ...value, allowWallet: e.target.checked })} />Enable customer wallet payments</label>
    <label className="checkbox-label"><input type="checkbox" checked={value.allowWalletCredit} disabled={!value.allowWallet} onChange={e => onChange({ ...value, allowWalletCredit: e.target.checked })} />Allow owner-approved purchases on credit</label><WorkspaceHelp><p>Prepaid funds are used first. Only an owner can approve a sale that creates debt. Repayments reduce the amount owed. Save business settings to apply these options.</p></WorkspaceHelp>
    <h3>Extra-payment rules</h3><WorkspaceHelp><p>Saved with business settings. Extra amounts are kept separate from sales revenue. Internal payment records are retained regardless of receipt visibility.</p></WorkspaceHelp>
    <label className="checkbox-label"><input type="checkbox" checked={value.allowExtras} onChange={e => onChange({ ...value, allowExtras: e.target.checked })} />Allow staff to record extra money retained</label>
    <label className="checkbox-label"><input type="checkbox" checked={value.reasonForChange} onChange={e => onChange({ ...value, reasonForChange: e.target.checked })} />Require staff to confirm bank-transfer overpayments returned to the customer</label>
    <label className="checkbox-label"><input type="checkbox" checked={value.printExtraDetails} onChange={e => onChange({ ...value, printExtraDetails: e.target.checked })} />Print extra amount, reason and explanation on customer receipts</label>
    {value.allowExtras && <><p>Allowed reasons (a reason is always required for retained extras):</p>{Object.entries(extraReasons).map(([key, label]) => <label key={key} className="checkbox-label"><input type="checkbox" checked={value.reasons.includes(key)} onChange={e => onChange({ ...value, reasons: e.target.checked ? [...value.reasons, key] : value.reasons.filter(r => r !== key) })} />{label}</label>)}</>}
    <h3>POS terminals</h3><WorkspaceHelp><p>Select the names your staff use for payments. The first option you select is used automatically at checkout from your saved selections. If you uncheck it, the next selected option takes its place.</p></WorkspaceHelp>{value.providers[0] && <p>Selected automatically: <strong>{value.providers[0]}</strong></p>}{providers.map(provider => <label key={provider} className="checkbox-label"><input type="checkbox" checked={value.providers.includes(provider)} onChange={e => onChange({ ...value, providers: e.target.checked ? [...value.providers, provider] : value.providers.filter(item => item !== provider) })} />{provider}</label>)}<div className="provider-add"><input value={newProvider} onChange={event => setNewProvider(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') { event.preventDefault(); addProvider() } }} placeholder="Add another POS provider" maxLength={100} /><button type="button" className="filter-button" onClick={addProvider}>Add name</button></div>
  </section>
}
