import { useState } from 'react'
import { Search, ScanLine } from 'lucide-react'
import { AsyncButton } from './AsyncControls'
import type { Product } from './types'
import type { ProductDraft } from './lib/productIntake'
import { lookupProductBarcode, validGtin } from './lib/productIntake'

export function ProductSearch({products,add,open,scan,openStarters,lookupApiUrl=''}:{products:Product[];add:(draft?:ProductDraft)=>void;open:(product:Product)=>void;scan:()=>Promise<string|undefined>;openStarters:()=>void;lookupApiUrl?:string}) {
  const [query,setQuery]=useState('')
  const [missing,setMissing]=useState<ProductDraft|null>(null)
  const matches=query.trim()?products.filter(product=>[product.name,product.barcode,product.sku].some(value=>value?.toLowerCase().includes(query.trim().toLowerCase()))).slice(0,30):[]
  return <section className="panel product-search"><h2>Add or search product</h2><label><Search size={18}/><span className="sr-only">Search products to add or edit</span><input type="search" value={query} placeholder="Product name or barcode" onChange={event=>setQuery(event.target.value)}/></label>{matches.map(product=><button type="button" className="product-search-result" key={product.id} onClick={()=>open(product)}>{product.name}<small>{product.barcode || product.sku}</small></button>)}{query.trim()&&!matches.length&&<p role="status">No matching product</p>}<div className="product-search-actions"><button type="button" className="primary-button" onClick={()=>add(query.trim()?{name:query.trim()}:undefined)}>Add product</button><AsyncButton className="filter-button" onClick={async()=>{const code=await scan();if(!code)return;const found=products.find(product=>product.barcode===code||product.sku===code);if(found){open(found);return}let draft:ProductDraft={name:'',barcode:code};if(validGtin(code)){try{draft=await lookupProductBarcode(code,lookupApiUrl)||draft}catch{}}setMissing(draft)}}><ScanLine size={20}/>Scan barcode</AsyncButton><button type="button" className="filter-button" onClick={openStarters}>Browse starter products</button></div>{missing&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="missing-product-title"><h2 id="missing-product-title">Add product</h2>{missing.name?<p>{missing.catalogueSource || 'Product catalogue'} suggests <strong>{missing.name}</strong>. Check the exact product and pack size. Price, cost and stock still come from your business.</p>:<p>No available catalogue had a name for this barcode. You can still add it; the barcode is already filled in.</p>}<div className="product-search-actions"><button type="button" className="filter-button" onClick={()=>setMissing(null)}>Dismiss</button><button type="button" className="primary-button" onClick={()=>{add(missing);setMissing(null)}}>Review product details</button></div></section></div>}</section>
}
