import { EmptyScreen, ScreenPicker } from './EmptyScreen'
import { WorkspaceHelp } from './WorkspaceHelp'
import { useEffect, useState } from 'react'
import type { Product } from './types'
import { posRequest } from './PosTools'
import { AsyncForm, SubmitButton, AsyncButton } from './AsyncControls'

type Line = { productId: string; quantity: string; unitCost: string; conversionId: string; batchNumber: string; expiry: string }
const blank = (): Line => ({ productId: '', quantity: '1', unitCost: '0', conversionId: '', batchNumber: '', expiry: '' })
export function Purchasing({ headers, products, branchId, businessId, refresh, oil = false }: { businessId: string; headers: Record<string, string>; products: Product[]; branchId: string; refresh: () => Promise<void>; oil?: boolean }) {
  const [view,setView]=useState('history')
  const [accounts,setAccounts]=useState<any[]>([])
  const [paidInFull,setPaidInFull]=useState(true)
  const [paidAmount,setPaidAmount]=useState('0')
  const [sellInPos,setSellInPos]=useState(false)
  const [records, setRecords] = useState<any[]>([])
  const [error, setError] = useState('')
  const [kind, setKind] = useState('receipt')
  const [supplierId, setSupplierId] = useState('')
  const [orderId, setOrderId] = useState('')
  const [receiptId, setReceiptId] = useState('')
  const [lines, setLines] = useState<Line[]>([blank()])
  const pendingKey = `stockroom-purchasing-pending:${businessId}:${branchId}`
  const [request, setRequest] = useState<any>(null)
  function remember(value: any) { if (value) localStorage.setItem(pendingKey, JSON.stringify(value)); else localStorage.removeItem(pendingKey); setRequest(value) }
  async function reload() { const result = await posRequest('/api/retail', headers); setRecords(result.records);setAccounts(result.accounts||[]) }
  useEffect(() => { setRecords([]); try { setRequest(JSON.parse(localStorage.getItem(pendingKey) || 'null')) } catch { setError('Could not read the pending delivery. Check history before entering it again.') }; setLines([blank()]); setSupplierId(''); setOrderId(''); setReceiptId(''); void reload().catch(caught => setError(caught.message)) }, [businessId, branchId, headers.Authorization])
  async function submit(input: any) {
    setError('')
    // Keep the same ID and payload if a response is lost. Editing/retrying is explicit.
    const pending = request || { ...input, id: crypto.randomUUID() }
    remember(pending)
    try {
      const response = await fetch('/api/retail', { method: 'POST', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify(pending) })
      const result = await response.json()
      if (!response.ok) { if(response.status<500) remember(null); throw new Error(result.error || 'Could not save purchasing changes.') }
      remember(null); setLines([blank()]); await reload(); await refresh(); if(pending.kind==='supplier')setView('suppliers'); else if(pending.kind==='receipt')setView('history') }
    catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not save purchasing changes.'); throw caught }
  }
  const suppliers = records.filter(row => row.kind === 'supplier')
  const conversions = records.filter(row => row.kind === 'conversion')
  const orders = records.filter(row => row.kind === 'order' && row.supplierId === supplierId)
  const chosenOrder = orders.find(row => row.id === orderId)
  const received = (id: string, productId: string) => records.filter(row => row.kind === 'receipt' && row.orderId === id).flatMap(row => row.lines).filter(row => row.productId === productId).reduce((sum, row) => sum + row.units, 0)
  function editLine(index: number, values: Partial<Line>) { setLines(current => current.map((line, i) => i === index ? { ...line, ...values } : line)) }
  return <section id="inventory-purchasing" className={`panel full-panel purchasing-screen${view==='suppliers'&&suppliers.length===0?' purchasing-empty-suppliers':''}`}><ScreenPicker value={view} change={setView} label="Supply screen" options={[{id:"history",label:"Supply records"},{id:"delivery",label:"New supply / stock operation"},{id:"suppliers",label:"Suppliers"},{id:"new-supplier",label:"New supplier"},{id:"balances",label:"Supplier balances & payments"},{id:"packs",label:"Pack conversions"}]} /><WorkspaceHelp title="Receiving stock"><p>Receive stock in its selling unit or a configured pack. Delivery costs are saved as purchase history; the existing catalogue cost is unchanged.</p></WorkspaceHelp>
    {error && <p role="alert">{error}</p>}
    {request && <div role="status"><WorkspaceHelp title="Supplies and supplier accounts"><p>A save is unresolved. Retry the same details before creating another delivery. Check history after refreshing if the connection was interrupted.</p></WorkspaceHelp><AsyncButton className="filter-button" busyLabel="Retrying..." onClick={() => submit(request)}>Retry save</AsyncButton><button type="button" className="text-button" onClick={() => { if (window.confirm('Discard this pending request? If the save reached another device, check synchronized history before entering it again.')) remember(null) }}>Discard pending request</button></div>}
    {view==='balances' && <details open><summary>Supplier balances and payments</summary><WorkspaceHelp title="Supplies and supplier accounts"><p>Positive balance is owed to the supplier; negative balance is supplier credit. Payments settle stock purchases and are not running expenses. Cash payments/refunds join your open register automatically; without an open register, cash is recorded on the supplier account only.</p></WorkspaceHelp>{accounts.map(account=><details key={account.id}><summary>{account.name}: {account.balance.toFixed(2)} {account.balance<0?'credit':'owed'}</summary>{account.legacyDeliveries>0 && <p>{account.legacyDeliveries} older deliveries have unknown payment status. Enter their actual outstanding balance once as an opening balance.</p>}<AsyncForm busyLabel="Saving supplier account..." onSubmit={event=>{const form=new FormData(event.currentTarget);return submit({kind:form.get('kind'),supplierId:account.id,amount:form.get('amount'),reference:form.get('reference'),method:form.get('method')})}}><label>Account operation<select name="kind"><option value="supplier-payment">Pay supplier / advance</option><option value="supplier-refund">Refund received from supplier</option>{!account.ledger.some((row:any)=>row.kind==='supplier-opening') && <option value="supplier-opening">Opening amount owed / credit</option>}</select></label><label>Amount<input name="amount" type="number" step="0.01" required/></label><small>Use a negative opening amount only for an existing supplier credit.</small><label>Method<select name="method"><option value="bank-transfer">Bank transfer</option><option value="cash">Cash</option></select></label><label>Reference / reason<input name="reference" required maxLength={200}/></label><SubmitButton className="filter-button" disabled={Boolean(request)}>Save supplier account entry</SubmitButton></AsyncForm><div className="table-wrap"><table><thead><tr><th>Date</th><th>Entry</th><th>Reference</th><th>Change</th><th>Balance</th></tr></thead><tbody>{account.ledger.map((row:any)=><tr key={row.id}><td>{new Date(row.createdAt).toLocaleDateString()}</td><td>{row.kind}</td><td>{row.reference}</td><td>{row.accountAmount.toFixed(2)}</td><td>{row.balance.toFixed(2)}</td></tr>)}</tbody></table></div></details>)}</details>}
    {['suppliers','new-supplier'].includes(view) && <section><h2>{view==='suppliers'?'Suppliers':'New supplier'}</h2>{view==='new-supplier' && <AsyncForm busyLabel="Saving supplier..." onSubmit={event => { const form = new FormData(event.currentTarget); return submit({ kind: 'supplier', name: form.get('name'), phone: form.get('phone') }) }}><label>Supplier name<input name="name" required maxLength={200} disabled={Boolean(request)} /></label><label>Phone<input name="phone" maxLength={100} disabled={Boolean(request)} /></label><SubmitButton className="filter-button" disabled={Boolean(request)}>Add supplier</SubmitButton></AsyncForm>}{view==='suppliers' && (suppliers.length===0?<EmptyScreen title="No suppliers yet" description="Add a supplier to record deliveries and track what you owe." action={<button type="button" className="primary-button" onClick={()=>setView('new-supplier')}>Add supplier</button>} />:suppliers.map(row => <p key={row.id}>{row.name} {row.phone}</p>))}</section>}
    {view==='packs' && <details open><summary>Pack conversions</summary><WorkspaceHelp title="Pack conversions"><p>{oil ? 'Define stock units per container for each oil product, then optionally make that container available in Oil sales. Selling a container deducts its full quantity from the oil stock.' : 'Define stock units per pack for receiving, and optionally offer the pack in Product sales. Selling a pack deducts its full base-unit quantity.'}</p></WorkspaceHelp><AsyncForm busyLabel="Saving conversion..." onSubmit={event => { const form = new FormData(event.currentTarget); return submit({ kind: 'conversion', productId: form.get('productId'), label: form.get('label'), factor: form.get('factor'), sellInPos: sellInPos, salePrice: form.get('salePrice') }) }}><label>Product<select aria-label="Product" name="productId" required disabled={Boolean(request)}><option value="">Choose product</option>{products.map(product => <option key={product.id} value={product.id}>{product.name} ({product.unit})</option>)}</select></label><label>Container or pack name<input name="label" required maxLength={200} placeholder={oil ? 'e.g. 25 L container' : 'e.g. Case of 12'} disabled={Boolean(request)} /></label><label>Stock units per pack<input name="factor" type="number" min="0.001" step="0.001" required disabled={Boolean(request)} /></label>{<><label className="checkbox-label"><input type="checkbox" checked={sellInPos} onChange={event=>setSellInPos(event.target.checked)} disabled={Boolean(request)}/>{oil?'Offer this container in oil sales':'Offer this pack in product sales'}</label>{sellInPos&&<label>{oil?'Price per container':'Price per pack'}<input name="salePrice" type="number" min="0" step="0.01" required disabled={Boolean(request)}/></label>}</>}<SubmitButton className="filter-button" disabled={Boolean(request)}>Add conversion</SubmitButton></AsyncForm>{conversions.map(row => <p key={row.id}>{products.find(product => product.id === row.productId)?.name}: {row.label} = {row.factor} selling units{row.sellInPos ? ` · checkout pack price ${row.salePrice}` : ''}</p>)}</details>}
    {view==='delivery' && <AsyncForm className="settings-form" busyLabel="Saving stock operation..." onSubmit={event => { const form = new FormData(event.currentTarget); return submit({ kind, supplierId, orderId: kind === 'receipt' ? orderId : '', receiptId: kind === 'supplier-return' ? receiptId : '', reference: form.get('reference'), reason: form.get('reason'), amountPaid:kind==='receipt'?(paidInFull?Math.round(lines.reduce((sum,line)=>sum+Number(line.quantity)*Number(line.unitCost),0)*100)/100:Number(paidAmount)):undefined, paymentMethod:form.get('paymentMethod'),paymentReference:form.get('paymentReference'), lines }) }}>
      <fieldset disabled={Boolean(request)} style={{ border: 0, padding: 0 }}><legend>Record stock operation</legend><label>Operation<select value={kind} onChange={event => setKind(event.target.value)}><option value="receipt">Receive supplier delivery</option><option value="order">Create purchase order</option><option value="waste">Record wastage</option><option value="supplier-return">Return stock to supplier</option></select></label>
      {kind !== 'waste' ? <><label>Supplier<select aria-label="Supplier" required value={supplierId} onChange={event => { setSupplierId(event.target.value); setOrderId(''); setReceiptId('') }}><option value="">Choose supplier</option>{suppliers.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label>Order / delivery reference<input name="reference" required maxLength={200} /></label>{kind === 'supplier-return' && <label>Original delivery<select aria-label="Original delivery" required value={receiptId} onChange={event => setReceiptId(event.target.value)}><option value="">Choose delivery</option>{records.filter(row => row.kind === 'receipt' && row.supplierId === supplierId).map(row => <option key={row.id} value={row.id}>{row.reference}</option>)}</select></label>}{kind === 'receipt' && <label>Purchase order (optional)<select value={orderId} onChange={event => setOrderId(event.target.value)}><option value="">Delivery without an order</option>{orders.map(row => <option key={row.id} value={row.id}>{row.reference}</option>)}</select></label>}</> : <label>Wastage reason<input name="reason" required maxLength={200} placeholder="Expired, damaged, or missing" /></label>}
      {chosenOrder && kind === 'receipt' && <p>{chosenOrder.lines.map((line: any) => `${line.productName}: ${Math.max(0, line.units - received(chosenOrder.id, line.productId))} ${line.unit} outstanding`).join('; ')}</p>}
      {kind==='receipt' && <details><summary>{paidInFull?'Payment: paid in full (change details)':'Payment: unpaid / part paid'}</summary><label><input type="checkbox" checked={paidInFull} onChange={event=>setPaidInFull(event.target.checked)}/>Delivery paid in full</label>{!paidInFull && <label>Amount paid now<input type="number" min="0" step="0.01" value={paidAmount} onChange={event=>setPaidAmount(event.target.value)}/></label>}<label>Payment method<select name="paymentMethod"><option value="bank-transfer">Bank transfer</option><option value="cash">Cash</option></select></label><label>Payment reference (optional)<input name="paymentReference" maxLength={200}/></label></details>}
      {lines.map((line, index) => <div key={index} className="form-grid"><label>Product<select aria-label="Product" required value={line.productId} onChange={event => editLine(index, { productId: event.target.value, conversionId: '', batchNumber: '', expiry: '' })}><option value="">Choose product</option>{products.map(product => <option key={product.id} value={product.id}>{product.name}</option>)}</select></label><label>Receiving unit<select aria-label="Receiving unit" value={line.conversionId} onChange={event => editLine(index, { conversionId: event.target.value })}><option value="">Selling unit ({products.find(product => product.id === line.productId)?.unit || 'unit'})</option>{conversions.filter(row => row.productId === line.productId).map(row => <option key={row.id} value={row.id}>{row.label} ({row.factor} units)</option>)}</select></label><label>Quantity<input type="number" required min="0.001" step="0.001" value={line.quantity} onChange={event => editLine(index, { quantity: event.target.value })} /></label>{kind === 'receipt' && <details><summary>Expiry / batch (optional)</summary><WorkspaceHelp title="Supplies and supplier accounts"><p>Leave these blank for ordinary stock. Add an expiry date when you want alerts for this delivery.</p></WorkspaceHelp><label>Batch number<input maxLength={100} value={line.batchNumber} onChange={event=>editLine(index,{batchNumber:event.target.value})}/></label><label>Expiry date<input type="date" value={line.expiry} onChange={event=>editLine(index,{expiry:event.target.value})}/></label></details>}{['receipt', 'order'].includes(kind) && <label>Cost per selected unit / pack<input type="number" required min="0" step="0.01" value={line.unitCost} onChange={event => editLine(index, { unitCost: event.target.value })} /></label>}{lines.length > 1 && <button type="button" className="text-button" onClick={() => setLines(current => current.filter((_, i) => i !== index))}>Remove line</button>}</div>)}
      <button type="button" className="filter-button" disabled={lines.length >= 100} onClick={() => setLines(current => [...current, blank()])}>Add another product</button><SubmitButton className="primary-button">Save {kind === 'receipt' ? 'delivery' : kind === 'order' ? 'order' : kind === 'supplier-return' ? 'supplier return' : 'wastage'}</SubmitButton></fieldset>
    </AsyncForm>}{view==='history' && <section><h2>Supply records</h2>{!records.some(row=>['order','receipt','waste','supplier-return'].includes(row.kind)) && <EmptyScreen title="No supplies recorded" description="Receive a delivery or record a stock operation. Its products, quantities and costs will appear here." action={<button type="button" className="primary-button" onClick={()=>setView('delivery')}>New supply</button>} />}{records.filter(row => ['order','receipt','waste','supplier-return'].includes(row.kind)).map(row => <article key={row.id}><strong>{row.kind}: {row.reference || row.reason}</strong><p>{new Date(row.createdAt).toLocaleString()} ? {row.staffName} ? {suppliers.find(supplier => supplier.id === row.supplierId)?.name}</p>{row.lines.map((line: any) => <p key={line.productId}>{line.productName}: {line.quantity} {line.pack} = {line.units} {line.unit}{row.kind !== 'waste' && ` ? purchase cost ${new Intl.NumberFormat(undefined, { style: 'currency', currency: row.currency || 'USD' }).format(line.units * line.unitCost)}`}{row.kind === 'order' && ` ? outstanding ${Math.max(0, line.units - received(row.id, line.productId))}`}</p>)}</article>)}</section>}
  </section>
}
