import type { Sale } from './types'

export function Receipt({ sale, fallbackName, fallbackCurrency }: { sale: Sale; fallbackName: string; fallbackCurrency: string }) {
  const details = sale.paymentDetails
  const receipt = details?.receipt
  const pricing = details?.pos?.pricing
  const money = (value: number) => new Intl.NumberFormat(undefined, { style: 'currency', currency: sale.currency || fallbackCurrency }).format(value)
  const date = new Date(sale.createdAt)
  const method = sale.paymentMethod === 'external-pos' ? receipt?.cardType || 'POS Terminal' : { cash: 'Cash', 'bank-transfer': 'Bank Transfer', wallet: 'Customer wallet', multiple: 'Split payment' }[sale.paymentMethod]
  return <div className="print-receipt thermal-document"><h1>PAYMENT RECEIPT</h1><h2>{sale.businessName || fallbackName}</h2>{receipt?.address && <p className="receipt-multiline">{receipt.address}</p>}{receipt?.phone && <p>Phone: {receipt.phone}</p>}{receipt?.email && <p>Email: {receipt.email}</p>}
    <section><h3>Transaction details</h3><p>Receipt: {receipt?.number || sale.id}</p>{receipt?.number && <small>Transaction ID: {sale.id}</small>}{details?.counterOrder && <p>Order: {details.counterOrder.id.slice(0,8).toUpperCase()}</p>}{details?.counterOrder?.diningOption && <p>Order type: {details.counterOrder.diningOption}</p>}<p>Date: {date.toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })}<br />Time: {date.toLocaleTimeString()}</p><p>Transaction type: {receipt?.transactionType || (details?.counterOrder?.tableService ? 'Restaurant / bar order' : details?.counterOrder ? 'Order counter order' : details?.servicePayment ? 'Payment' : 'In-store shopping')}</p><p>Cashier: {sale.staffName || sale.staffId || 'Not recorded'}</p>{details?.servicePayment?.customerName && <p>Customer: {details.servicePayment.customerName}</p>}{details?.servicePayment?.customerPhone && <p>Phone: {details.servicePayment.customerPhone}</p>}{details?.pos?.customerName && <p>Customer: {details.pos.customerName}</p>}</section>
    {details?.serviceJob?.church && <p>Fund: {details.serviceJob.church.fundName}<br />Donor: {details.serviceJob.church.donorName}{details.serviceJob.church.type==='pledge'&&<><br />Pledge: {details.serviceJob.title}<br />Commitment: {money(details.serviceJob.invoiceTotal)}<br />Remaining at this payment: {money(details.serviceJob.balanceDue)}</>}</p>}
    {details?.serviceJob && !details.serviceJob.church && <p>Invoice: #{details.serviceJob.number}<br />{details.serviceJob.title}<br />Invoice total: {money(details.serviceJob.invoiceTotal)}<br /><strong>Balance due: {money(details.serviceJob.balanceDue)}</strong></p>}
    <div className="receipt-items thermal-lines">{sale.items.map((item,index) => <div className="thermal-line" key={index}><strong>{item.productName || item.productId}</strong><div className="thermal-line-amount"><span>{item.quantity} x {money(item.price)}</span><span>{money(details?.restaurantBill && pricing?.lines[index] ? pricing.lines[index].subtotal : Math.round(item.quantity * item.price * 100) / 100)}</span></div></div>)}</div>
    <section><h3>Financial summary</h3><p>Subtotal: {money(pricing?.subtotal ?? sale.items.reduce((sum,item) => sum + item.quantity * item.price,0))}</p>{Boolean(pricing?.discount) && <p>Discount: {money(pricing!.discount)}</p>}{!details?.restaurantBill && pricing?.taxSettings.taxEnabled && <p>{pricing?.taxSettings.taxLabel || 'Tax'} ({pricing?.taxSettings.taxEnabled ? pricing.taxSettings.taxRate : 0}%{pricing?.taxSettings.taxIncluded ? ', included' : ''}): {money(pricing?.tax || 0)}</p>}{Boolean(details?.pos?.loyaltyRedeemed) && <p>Rewards spent (included in discount): {money(details!.pos!.loyaltyRedeemed!)}</p>}{details?.restaurantBill && Number(pricing?.addedTax)>0 && <p>Tax added: {money(pricing!.addedTax!)}</p>}{details?.restaurantBill && Number(pricing?.includedTax)>0 && <p>Tax included in prices: {money(pricing!.includedTax!)}</p>}<strong>GRAND TOTAL: {money(sale.total)}</strong></section>
    {details?.restaurantBill && <p>Table / tab: {details.restaurantBill.name} / Bill {details.restaurantBill.sessionId.slice(0,8).toUpperCase()}</p>}{details?.counterOrder?.tableService && <p>Table / tab: {details.counterOrder.tableService.name}{details.counterOrder.tableService.seat ? ` / Seat ${details.counterOrder.tableService.seat}` : ''}</p>}<section><h3>Payment information</h3><p>Payment Method: {method}</p><p>Amount paid: {money(details?.amountReceived ?? sale.cashReceived ?? sale.total)}</p>{sale.paymentMethod === 'cash' && sale.cashReceived != null && <p>Cash received: {money(sale.cashReceived)}</p>}<p>Change given: {money(details?.changeGiven ?? sale.changeGiven ?? 0)}</p>{details?.allocations?.map((part,index)=><p key={index}>{part.method==='cash'?'Cash':part.method==='bank-transfer'?'Bank Transfer':'POS Terminal'}: {money(part.amount)} {part.provider} {part.reference}</p>)}{sale.terminalProvider && <p>Provider: {sale.terminalProvider}</p>}{sale.paymentReference && <p>Reference: {sale.paymentReference}</p>}{details?.printExtraDetails && details.extraKept > 0 && <p>Extra retained: {money(details.extraKept)} ({details.reason}){details.note ? ` - ${details.note}` : ''}</p>}</section>
    {details?.pos?.note && <p>{details.pos.note}</p>}{(!sale.currency || !sale.businessName) && <small>Historical currency/business identity unavailable; current settings used.</small>}{(receipt?.footer ?? 'Thank you for your business!') && <footer className="receipt-multiline">{receipt?.footer ?? 'Thank you for your business!'}</footer>}
  </div>
}
