export type ChartRow={label:string;value:number}
export type ReportChartData={daily:ChartRow[];payments:ChartRow[];products:ChartRow[];expenses:ChartRow[]}
const colors=['var(--brand-primary, #176b73)','#7256b8','#d68130','#34865e','#c15379','#487cb8']
function Chart({title,rows,format,pie=false,note}:{title:string;rows:ChartRow[];format:(value:number)=>string;pie?:boolean;note:string}){
 const usable=rows.filter(row=>Number.isFinite(row.value)),positive=usable.filter(row=>row.value>0),total=positive.reduce((sum,row)=>sum+row.value,0),max=Math.max(1,...usable.map(row=>Math.abs(row.value)))
 let end=0
 const slices=positive.map((row,index)=>{const start=end;end+=row.value/total*360;return `${colors[index%colors.length]} ${start}deg ${end}deg`})
 return <section className="panel report-chart"><h3>{title}</h3><p>{note}</p>{!usable.length||usable.every(row=>row.value===0)?<p className="empty-state">No activity for this period.</p>:pie?<div className="chart-pie-layout"><div className="chart-doughnut" role="img" aria-label={`${title}. ${positive.map(row=>`${row.label}: ${format(row.value)}`).join('; ')}`} style={{background:`conic-gradient(${slices.join(',')})`}}><span>{positive.length} methods</span></div><ul>{positive.map((row,index)=><li key={row.label}><i style={{background:colors[index%colors.length]}} aria-hidden="true"/><span>{row.label}</span><strong>{format(row.value)} <small>({(row.value/total*100).toFixed(1)}%)</small></strong></li>)}</ul></div>:<div className="chart-bars" role="img" aria-label={`${title}. ${usable.map(row=>`${row.label}: ${format(row.value)}`).join('; ')}`}>{usable.map((row,index)=><div className="chart-bar-row" key={row.label}><span>{row.label}</span><div className="chart-bar-track"><i style={{width:`${Math.abs(row.value)/max*100}%`,background:row.value<0?'#b94040':colors[index%colors.length]}}/></div><strong>{format(row.value)}</strong></div>)}</div>}<details className="chart-data"><summary>View data table</summary><div className="table-wrap"><table><thead><tr><th>Label</th><th>Value</th>{pie&&<th>Share</th>}</tr></thead><tbody>{usable.map(row=><tr key={row.label}><td>{row.label}</td><td>{format(row.value)}</td>{pie&&<td>{total>0&&row.value>0?`${(row.value/total*100).toFixed(1)}%`:'—'}</td>}</tr>)}</tbody></table></div></details></section>
}
export function ReportCharts({data,currency,timeZone}:{data?:ReportChartData;currency:string;timeZone:string}){
 const money=(value:number)=>new Intl.NumberFormat(undefined,{style:'currency',currency}).format(value)
 return <section className="report-visuals" aria-label="Report charts"><div className="chart-heading"><h2>This month at a glance</h2><p>Month to date · {timeZone} · {currency}. Includes records saved on this device.</p></div>{!data?<p>Refresh reports to load chart data.</p>:<div className="chart-grid"><Chart title="Daily sales" rows={data.daily} format={money} note="Receipt totals less refunds on the day recorded. Red bars indicate negative totals."/><Chart title="Payment methods" rows={data.payments} format={money} pie note="Completed receipt totals before refunds, grouped by checkout method. Split payments appear as one method; this is not bank reconciliation."/><Chart title="Top-selling products" rows={data.products} format={value=>`${value.toLocaleString()} units`} note="Quantities sold less returned quantities. Product units may differ."/><Chart title="Expenses by category" rows={data.expenses} format={money} note="Recorded expenses grouped by category and date incurred."/></div>}</section>
}
