import { useEffect, useState } from 'react'
import { CounterService, type CounterOrder } from './CounterService'
import { AsyncButton, AsyncForm, SubmitButton } from './AsyncControls'
import { posRequest } from './PosTools'
import { checkoutTillId } from './lib/checkoutTill'
import { tableTabId, restaurantBillFingerprint } from '../server/restaurant-service.mjs'
export type RestaurantTab = { id:string; updatedAt:string; sessionId:string; name:string; tableId:string; guests:number; tillId:string; status:'open'|'closed'; openedAt:string; currency:string; businessName:string; history?:RestaurantTab[] }
type Table = { id:string; name:string; seats:number }
type Data = { layout:{id:string; updatedAt:string; tables:Table[]}; tabs:RestaurantTab[]; orders:CounterOrder[] }
type Props = Parameters<typeof CounterService>[0] & { printBill?: (tab:RestaurantTab,orders:CounterOrder[])=>Promise<void> }
export function RestaurantService(props:Props) {
  return props.restaurant ? <TablesWorkspace {...props}/> : <CounterService {...props}/>
}
function TablesWorkspace(props:Props) {
  const [data,setData] = useState<Data>({layout:{id:'',updatedAt:'',tables:[]},tabs:[],orders:[]})
  const selectionKey=props.storageKey+':restaurant-selection'
  const [selected,setSelected] = useState<{id:string;sessionId:string}|null>(()=>{try{const saved=JSON.parse(localStorage.getItem(selectionKey)||'null');return typeof saved?.id==='string' && typeof saved?.sessionId==='string' ? saved : null}catch{return null}})
  useEffect(()=>{try{localStorage.setItem(selectionKey,JSON.stringify(selected))}catch{setMessage('The selected bill could not be remembered on this device. Saved orders and receipts are still available.')}},[selectionKey,selected])
  const [layout,setLayout] = useState<Data['layout'] | null>(null)
  const [open,setOpen] = useState<{tableId:string; name:string; guests:string} | null>(null)
  const [error,setError] = useState('')
  const [message,setMessage] = useState('')
  const [settle,setSettle] = useState(false)
  const [entryBill,setEntryBill] = useState('')
  const [method,setMethod] = useState<'cash'|'bank-transfer'|'external-pos'>('cash')
  const [cash,setCash] = useState('')
  const [provider,setProvider] = useState('')
  const [reference,setReference] = useState('')
  const token=props.headers.Authorization, branch=props.headers['X-Stockroom-Branch'] || 'main'
  async function reload() { const next = await posRequest('/api/pos/restaurant',props.headers); setData(next); return next as Data }
  useEffect(()=>{ let live=true; const refresh=async()=>{try{const next=await posRequest('/api/pos/restaurant',props.headers);if(live){setData(next);setError('')}}catch(caught){if(live)setError(caught instanceof Error?caught.message:'Tables could not load.')}};void refresh();const timer=setInterval(refresh,5000);return()=>{live=false;clearInterval(timer)} },[token,branch])
  const current=data.tabs.find(tab=>tab.id===selected?.id && tab.sessionId===selected.sessionId && tab.status==='open')
  const billMoney=(amount:number)=>current ? new Intl.NumberFormat(undefined,{style:'currency',currency:current.currency}).format(amount) : props.money(amount)
  const orders=data.orders.filter(order=>current && order.tableService?.tabId===current.id && order.tableService.sessionId===current.sessionId)
  const bill=orders.filter(order=>order.status!=='cancelled')
  const total=Math.round(bill.reduce((sum,order)=>sum+order.total,0)*100)/100
  const due=Math.round(bill.filter(order=>!order.receiptId).reduce((sum,order)=>sum+order.total,0)*100)/100
  async function command(path:string,input:any) { const result=await posRequest('/api/pos/restaurant/'+path,props.headers,{...input,commandId:crypto.randomUUID()});await reload();return result as RestaurantTab }
  return <section className="restaurant-workspace">
    <section className="panel"><h2>Restaurant &amp; bar</h2><p>Open a table or named bar tab, add food and drinks, serve orders and settle the bill.</p><div className="report-actions"><button type="button" className="primary-button" onClick={()=>{setOpen({tableId:'',name:'',guests:'1'});setMessage('')}}>Open bar tab</button>{props.manager && <button type="button" className="filter-button" onClick={()=>setLayout(structuredClone(data.layout))}>Set up tables and seats</button>}<button type="button" className="filter-button" onClick={()=>{setSelected(null);setSettle(false)}}>Menu and all orders</button><AsyncButton className="filter-button" onClick={async()=>{await props.synchronize();await reload();setMessage('Tables and bills synchronized.')}}>Sync tables and bills</AsyncButton></div>{error && <p role="alert">{error}</p>}{message && <p role="status">{message}</p>}</section>
    {layout && props.manager && <AsyncForm className="panel" onSubmit={async()=>{await command('layout',{id:layout.id,expectedUpdatedAt:layout.updatedAt,tables:layout.tables});setLayout(null);setMessage('Table setup saved.')}}><h3>Tables and seats</h3>{layout.tables.map(table=><fieldset key={table.id}><legend>{table.name || 'New table'}</legend><div className="form-grid"><label>Table name<input required maxLength={60} value={table.name} onChange={event=>setLayout({...layout,tables:layout.tables.map(row=>row.id===table.id?{...row,name:event.target.value}:row)})}/></label><label>Number of seats<input required type="number" min="1" max="100" step="1" value={table.seats} onChange={event=>setLayout({...layout,tables:layout.tables.map(row=>row.id===table.id?{...row,seats:Number(event.target.value)}:row)})}/></label></div><button type="button" className="filter-button" onClick={()=>setLayout({...layout,tables:layout.tables.filter(row=>row.id!==table.id)})}>Remove table</button></fieldset>)}<button type="button" className="filter-button" disabled={layout.tables.length>=100} onClick={()=>setLayout({...layout,tables:[...layout.tables,{id:crypto.randomUUID(),name:'',seats:4}]})}>Add table</button><SubmitButton className="primary-button">Save tables</SubmitButton><button type="button" className="filter-button" onClick={()=>setLayout(null)}>Discard changes</button></AsyncForm>}
    <section className="panel"><h3>Tables</h3>{!data.layout.tables.length && <p>{props.manager?'Set up your tables and seats, or open a named bar tab.':'Ask the owner to set up tables, or open a named bar tab.'}</p>}<div className="restaurant-table-grid">{data.layout.tables.map(table=>{const tab=data.tabs.find(tab=>tab.tableId===table.id && tab.status==='open');return <button type="button" key={table.id} className={tab && selected?.id===tab.id && selected.sessionId===tab.sessionId?'primary-button':'filter-button'} onClick={()=>{setSettle(false);tab?setSelected({id:tab.id,sessionId:tab.sessionId}):setOpen({tableId:table.id,name:table.name,guests:String(table.seats)})}}><strong>{table.name}</strong><span>{table.seats} seats - {tab?`${tab.guests} guests - Open bill`:'Free'}</span></button>})}</div><h3>Open bar tabs</h3><div className="restaurant-table-grid">{data.tabs.filter(tab=>!tab.tableId && tab.status==='open').map(tab=><button type="button" key={tab.id} className={selected?.id===tab.id && selected.sessionId===tab.sessionId?'primary-button':'filter-button'} onClick={()=>{setSelected({id:tab.id,sessionId:tab.sessionId});setSettle(false)}}><strong>{tab.name}</strong><span>{tab.guests} guests - Open bill</span></button>)}</div></section>
    {open && <AsyncForm className="panel" onSubmit={async()=>{const id=open.tableId?tableTabId(branch,open.tableId):`restaurant-tab:${branch}:${crypto.randomUUID()}`;const previous=data.tabs.find(tab=>tab.id===id);const saved=await command('open',{id,expectedUpdatedAt:previous?.updatedAt||'',tableId:open.tableId,name:open.name,guests:Number(open.guests),sessionId:crypto.randomUUID()});setSelected({id:saved.id,sessionId:saved.sessionId});setOpen(null);setSettle(false)}}><h3>{open.tableId?`Open ${open.name}`:'Open a bar tab'}</h3>{!open.tableId && <label>Tab name<input required maxLength={100} value={open.name} onChange={event=>setOpen({...open,name:event.target.value})} placeholder="Customer name or group"/></label>}<label>Number of guests<input required type="number" min="1" max={data.layout.tables.find(table=>table.id===open.tableId)?.seats||100} step="1" value={open.guests} onChange={event=>setOpen({...open,guests:event.target.value})}/></label><SubmitButton className="primary-button">Open bill</SubmitButton><button type="button" className="filter-button" onClick={()=>setOpen(null)}>Cancel</button></AsyncForm>}
    {current && <section className="panel restaurant-bill"><h3>Bill for {current.name}</h3><p>{current.guests} guests - Bill {current.sessionId.slice(0,8).toUpperCase()}</p>{bill.length?<div className="table-scroll"><table><thead><tr><th>Description</th><th>Seat</th><th>Qty</th><th>Unit price</th><th>Total</th><th>Payment</th></tr></thead><tbody>{bill.flatMap(order=>order.lines.map(line=><tr key={order.id+line.id}><td>{[line.name,...line.options.map(option=>option.name)].join(' / ')}</td><td>{order.tableService?.seat || 'Shared'}</td><td>{line.quantity}</td><td>{billMoney(line.price)}</td><td>{billMoney(line.quantity*line.price)}</td><td>{order.receiptId?'Paid':'Unpaid'}</td></tr>))}</tbody></table></div>:<p>No orders yet. Add the first round below.</p>}<p>Bill total: <strong>{billMoney(total)}</strong></p><p>Paid: {billMoney(total-due)}</p><p>Amount due: <strong>{billMoney(due)}</strong></p><p>Order totals retain their saved taxes and discounts.</p><div className="report-actions"><AsyncButton className="filter-button" disabled={!bill.length} onClick={async()=>{if(!props.printBill)throw new Error('Bill printing is unavailable.');await props.printBill(current,bill)}}>Print itemized bill</AsyncButton><button type="button" className="primary-button" disabled={!due || current.tillId!==checkoutTillId()} onClick={()=>{setEntryBill(restaurantBillFingerprint(current,orders));setSettle(true);setCash('');setMethod('cash');setProvider('');setReference('')}}>Settle remaining bill</button><AsyncButton className="filter-button" disabled={due>0 || orders.some(order=>!['collected','cancelled'].includes(order.status)) || current.tillId!==checkoutTillId()} onClick={async()=>{await command('close',{id:current.id,expectedUpdatedAt:current.updatedAt});setSelected(null);setMessage('Bill closed. The table is free.')}}>Close bill and free table</AsyncButton></div><p>Use Take payment on an individual order below when guests pay separately by round. Orders and payments stay on the till that opened the bill.</p></section>}
    {settle && current && due>0 && <AsyncForm className="panel" onSubmit={async()=>{
      const latest=await reload();const unpaid=latest.orders.filter(order=>order.tableService?.tabId===current.id && order.tableService.sessionId===current.sessionId && order.status!=='cancelled' && !order.receiptId)
      const latestTab=latest.tabs.find(tab=>tab.id===current.id && tab.sessionId===current.sessionId && tab.status==='open')
      if(!latestTab || restaurantBillFingerprint(latestTab,latest.orders)!==entryBill) throw new Error('This bill changed. Cancel payment entry, review the bill and start payment again.')
      const amount=Math.round(unpaid.reduce((sum,order)=>sum+order.total,0)*100)/100
      if(!unpaid.length)throw new Error('This bill is already paid. Refresh its receipts.')
      if(unpaid.some(order=>order.tillId!==checkoutTillId()))throw new Error('Settle orders on their original till.')
      const received=method==='cash'?Number(cash||amount):amount
      if(!Number.isFinite(received)||received<amount||Math.abs(received*100-Math.round(received*100))>0.000001)throw new Error('Enter cash covering the remaining bill, with at most two decimals.')
      if(method!=='cash' && (!provider.trim()||!reference.trim()))throw new Error('Record a provider and successful payment reference.')
      let completed=0
      try { for(const [index,order] of unpaid.entries()) { await props.pay(order,{method,cash:String(order.total+(index===unpaid.length-1?Math.round((received-amount)*100)/100:0)),provider,reference});completed++ } }
      catch(error){setSettle(false);setCash('');setMessage(`${completed} order payments saved. Refresh the bill and settle only its remaining unpaid orders.`);throw error}
      finally{await reload()}
      setSettle(false);setMessage('Bill payments saved. Print the itemized bill or individual receipts, then close the bill when every order is served.')
    }}><h3>Settle bill</h3><p>Remaining: {billMoney(due)}. Each order keeps its own payment receipt.</p><label htmlFor="restaurant-bill-payment-method">Bill payment method</label><select id="restaurant-bill-payment-method" value={method} onChange={event=>setMethod(event.target.value as typeof method)}><option value="cash">Cash</option><option value="bank-transfer">Bank transfer</option><option value="external-pos">Payment terminal</option></select>{method==='cash'?<label>Bill cash received<input type="number" min={due} step="0.01" value={cash} placeholder={String(due)} onChange={event=>setCash(event.target.value)}/></label>:<><label>Bill payment provider<input required value={provider} onChange={event=>setProvider(event.target.value)}/></label><label>Bill payment reference<input required value={reference} onChange={event=>setReference(event.target.value)}/></label><p>Confirm the payment succeeded outside this app before recording it.</p></>}<SubmitButton className="primary-button">Save bill payments</SubmitButton><button type="button" className="filter-button" onClick={()=>setSettle(false)}>Cancel payment entry</button></AsyncForm>}
    <CounterService {...props} money={billMoney} key={current?.sessionId || 'restaurant-setup'} restaurant tableSession={current} storageKey={props.storageKey+':'+(current?.sessionId||'setup')} onOrdersChanged={async()=>{await reload()}}/>
    <details className="panel"><summary>Closed bills</summary>{data.tabs.flatMap(tab=>[...(tab.history||[]),...(tab.status==='closed'?[tab]:[])]).map(tab=><div className="customer-row" key={tab.sessionId}><span>{tab.name} - {tab.sessionId.slice(0,8).toUpperCase()}</span><AsyncButton className="filter-button" onClick={async()=>{if(props.printBill)await props.printBill(tab,data.orders.filter(order=>order.tableService?.tabId===tab.id && order.tableService.sessionId===tab.sessionId && order.status!=='cancelled'))}}>Reprint bill</AsyncButton></div>)}</details>
  </section>
}
