import { billContains,billSeat } from '../server/restaurant-floor.mjs'
import { RestaurantPayment, type BillPaymentDraft } from './RestaurantPayment'
import { restaurantBillLines } from '../server/restaurant-payments.mjs'
import { DigitalReceipt } from './PosTools'
import type { Sale } from './types'
import { useEffect, useRef, useState } from 'react'
import { CounterService, type CounterOrder, CounterRefund } from './CounterService'
import { AsyncButton, AsyncForm, SubmitButton } from './AsyncControls'
import { posRequest } from './PosTools'
import { checkoutTillId } from './lib/checkoutTill'
import { tableTabId } from '../server/restaurant-service.mjs'
export type RestaurantTab = { branchId:string; displayTableId?:string; billMembers?:any[]; mergedInto?:{tabId:string;sessionId:string}; id:string; updatedAt:string; sessionId:string; name:string; tableId:string; guests:number; tillId:string; status:'open'|'closed'; openedAt:string; currency:string; businessName:string; history?:RestaurantTab[] }
type Table = { id:string; name:string; seats:number }
type Data = { floor:{id:string;updatedAt:string};layout:{id:string; updatedAt:string; tables:Table[]}; tabs:RestaurantTab[]; orders:CounterOrder[];receipts:Sale[];ledgers:Array<{sessionId:string;updatedAt:string}>;returns:any[] }
type Props = Parameters<typeof CounterService>[0] & { payBill?:(draft:BillPaymentDraft)=>Promise<Sale>; printBill?: (tab:RestaurantTab,orders:CounterOrder[])=>Promise<void> }
export function RestaurantService(props:Props) {
  return props.restaurant ? <TablesWorkspace {...props}/> : <CounterService {...props}/>
}
function TablesWorkspace(props:Props) {
  const [data,setData] = useState<Data>({floor:{id:'',updatedAt:''},layout:{id:'',updatedAt:'',tables:[]},tabs:[],orders:[],receipts:[],ledgers:[],returns:[]})
  const selectionKey=props.storageKey+':restaurant-selection'
  const [selected,setSelected] = useState<{id:string;sessionId:string}|null>(()=>{try{const saved=JSON.parse(localStorage.getItem(selectionKey)||'null');return typeof saved?.id==='string' && typeof saved?.sessionId==='string' ? saved : null}catch{return null}})
  useEffect(()=>{try{localStorage.setItem(selectionKey,JSON.stringify(selected))}catch{setMessage('The selected bill could not be remembered on this device. Saved orders and receipts are still available.')}},[selectionKey,selected])
  const [view,setView]=useState<'tables'|'orders'|'preparation'|'setup'|'history'>(props.configuration?'setup':'tables')
  const [layout,setLayout] = useState<Data['layout'] | null>(null)
  const [open,setOpen] = useState<{tableId:string; name:string; guests:string} | null>(null)
  const [error,setError] = useState('')
  const [message,setMessage] = useState('')
  const [settle,setSettle] = useState(false)
  const [arrange,setArrange]=useState<'move'|'merge'|''>('')
  const [destination,setDestination]=useState('')
  const [savedPayment,setSavedPayment]=useState<Sale|null>(null)
  const [refundReceipt,setRefundReceipt]=useState<Sale|null>(null)
  const [paymentOrder,setPaymentOrder]=useState('')
  const token=props.headers.Authorization, branch=props.headers['X-Stockroom-Branch'] || 'main'
  async function reload() { const next = await posRequest('/api/pos/restaurant',props.headers); setData(next); return next as Data }
  useEffect(()=>{ let live=true; const refresh=async()=>{try{const next=await posRequest('/api/pos/restaurant',props.headers);if(live){setData(next);setError('')}}catch(caught){if(live)setError(caught instanceof Error?caught.message:'Tables could not load.')}};void refresh();const timer=setInterval(refresh,5000);return()=>{live=false;clearInterval(timer)} },[token,branch])
  const current=view==='tables' ? data.tabs.find(tab=>tab.id===selected?.id && tab.sessionId===selected.sessionId && tab.status==='open' && !tab.mergedInto) : undefined
  const billMoney=(amount:number)=>current ? new Intl.NumberFormat(undefined,{style:'currency',currency:current.currency}).format(amount) : props.money(amount)
  const orders=data.orders.filter(order=>current && billContains(current,order))
  const bill=orders.filter(order=>order.status!=='cancelled')
  const total=Math.round(bill.reduce((sum,order)=>sum+order.total,0)*100)/100
  const unpaidLines=current ? restaurantBillLines(current,data.orders,data.receipts) : []
  const due=Math.round(unpaidLines.reduce((sum,line)=>sum+line.remainingAmount,0)*100)/100
  const paymentKey=props.storageKey+':restaurant-payment'
  const restoredSession=useRef('')
  useEffect(()=>{try{const draft=JSON.parse(localStorage.getItem(paymentKey)||'null');const receipt=data.receipts.find(sale=>sale.id===draft?.id);if(receipt){setSavedPayment(receipt);setSettle(false);localStorage.removeItem(paymentKey)}else if(draft?.sessionId===current?.sessionId && restoredSession.current!==current?.sessionId)setSettle(true);restoredSession.current=current?.sessionId||''}catch{}},[data.receipts,current?.sessionId,paymentKey])
  async function command(path:string,input:any) { const result=await posRequest('/api/pos/restaurant/'+path,props.headers,{...input,commandId:crypto.randomUUID()});await reload();return result as RestaurantTab }
  return <section className="restaurant-workspace">
    <section className="panel"><h2>Restaurant &amp; bar</h2><p>{props.configuration?'Configure tables, seats and the restaurant menu here. Serve customers in Restaurant & bar.':current?`Serving ${current.name}. Add an order or take payment for this bill.`:'Choose a table or open a bar tab to start a transaction.'}</p><nav className="counter-tabs" aria-label="Restaurant workspace screens">{((props.configuration?['setup']:['tables','orders','preparation','history']) as Array<'tables'|'orders'|'preparation'|'history'|'setup'>).map(screen=><button type="button" key={screen} className={view===screen?'primary-button':'filter-button'} aria-pressed={view===screen} onClick={()=>{setView(screen as typeof view);setSettle(false);if(screen==='tables')setSelected(null)}}>{{tables:'Tables and tabs',orders:'Live orders',preparation:'Preparation',history:'History',setup:'Setup'}[screen]}</button>)}</nav><div className="report-actions">{view==='tables'&&<button type="button" className="primary-button" onClick={()=>{setSelected(null);setSettle(false);setOpen({tableId:'',name:'',guests:'1'});setMessage('')}}>Open bar tab</button>}{view==='setup'&&props.manager&&<button type="button" className="filter-button" onClick={()=>setLayout(structuredClone(data.layout))}>Set up tables and seats</button>}<AsyncButton className="filter-button" onClick={async()=>{await props.synchronize();await reload();setMessage('Tables and bills synchronized.')}}>Sync tables and bills</AsyncButton></div>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</section>
    {view==='setup' && layout && props.manager && <AsyncForm className="panel" onSubmit={async()=>{await command('layout',{id:layout.id,expectedUpdatedAt:layout.updatedAt,tables:layout.tables});setLayout(null);setMessage('Table setup saved.')}}><h3>Tables and seats</h3>{layout.tables.map(table=><fieldset key={table.id}><legend>{table.name || 'New table'}</legend><div className="form-grid"><label>Table name<input required maxLength={60} value={table.name} onChange={event=>setLayout({...layout,tables:layout.tables.map(row=>row.id===table.id?{...row,name:event.target.value}:row)})}/></label><label>Number of seats<input required type="number" min="1" max="100" step="1" value={table.seats} onChange={event=>setLayout({...layout,tables:layout.tables.map(row=>row.id===table.id?{...row,seats:Number(event.target.value)}:row)})}/></label></div><button type="button" className="filter-button" onClick={()=>setLayout({...layout,tables:layout.tables.filter(row=>row.id!==table.id)})}>Remove table</button></fieldset>)}<button type="button" className="filter-button" disabled={layout.tables.length>=100} onClick={()=>setLayout({...layout,tables:[...layout.tables,{id:crypto.randomUUID(),name:'',seats:4}]})}>Add table</button><SubmitButton className="primary-button">Save tables</SubmitButton><button type="button" className="filter-button" onClick={()=>setLayout(null)}>Discard changes</button></AsyncForm>}
    {view==='tables' && !current && <section className="panel"><h3>Tables</h3>{!data.layout.tables.length && <p>{props.manager?'Set up your tables and seats, or open a named bar tab.':'Ask the owner to set up tables, or open a named bar tab.'}</p>}<div className="restaurant-table-grid">{data.layout.tables.map(table=>{const tab=data.tabs.find(tab=>(tab.displayTableId??tab.tableId)===table.id && tab.status==='open' && !tab.mergedInto);return <button type="button" key={table.id} className={tab && selected?.id===tab.id && selected.sessionId===tab.sessionId?'primary-button':'filter-button'} onClick={()=>{setSettle(false);tab?setSelected({id:tab.id,sessionId:tab.sessionId}):setOpen({tableId:table.id,name:table.name,guests:String(table.seats)})}}><strong>{table.name}</strong><span>{table.seats} seats - {tab?`${tab.guests} guests - Open bill`:'Free'}</span></button>})}</div><h3>Open bar tabs</h3><div className="restaurant-table-grid">{data.tabs.filter(tab=>!(tab.displayTableId??tab.tableId) && tab.status==='open' && !tab.mergedInto).map(tab=><button type="button" key={tab.id} className={selected?.id===tab.id && selected.sessionId===tab.sessionId?'primary-button':'filter-button'} onClick={()=>{setSelected({id:tab.id,sessionId:tab.sessionId});setSettle(false)}}><strong>{tab.name}</strong><span>{tab.guests} guests - Open bill</span></button>)}</div></section>}
    {open && <AsyncForm className="panel" onSubmit={async()=>{const canonical=open.tableId?tableTabId(branch,open.tableId):'';const id=canonical && !data.tabs.some(tab=>tab.id===canonical && tab.status==='open')?canonical:`restaurant-tab:${branch}:${crypto.randomUUID()}`;const previous=data.tabs.find(tab=>tab.id===id);const saved=await command('open',{id,expectedUpdatedAt:previous?.updatedAt||'',tableId:open.tableId,name:open.name,guests:Number(open.guests),sessionId:crypto.randomUUID()});setView('tables');setSelected({id:saved.id,sessionId:saved.sessionId});setOpen(null);setSettle(false)}}><h3>{open.tableId?`Open ${open.name}`:'Open a bar tab'}</h3>{!open.tableId && <label>Tab name<input required maxLength={100} value={open.name} onChange={event=>setOpen({...open,name:event.target.value})} placeholder="Customer name or group"/></label>}<label>Number of guests<input required type="number" min="1" max={data.layout.tables.find(table=>table.id===open.tableId)?.seats||100} step="1" value={open.guests} onChange={event=>setOpen({...open,guests:event.target.value})}/></label><SubmitButton className="primary-button">Open bill</SubmitButton><button type="button" className="filter-button" onClick={()=>setOpen(null)}>Cancel</button></AsyncForm>}
    {current && <section className="panel restaurant-bill"><h3>Bill for {current.name}</h3><p>{current.guests} guests - Bill {current.sessionId.slice(0,8).toUpperCase()}</p><button type="button" className="primary-button" disabled={!due||current.tillId!==checkoutTillId()} onClick={()=>{setPaymentOrder('');setSettle(true)}}>Take payment - {billMoney(due)}</button>{bill.length?<div className="table-scroll"><table><thead><tr><th>Description</th><th>Seat</th><th>Qty</th><th>Unit price</th><th>Total</th><th>Payment</th></tr></thead><tbody>{bill.flatMap(order=>order.lines.map(line=><tr key={order.id+line.id}><td>{[line.name,...line.options.map(option=>option.name)].join(' / ')}</td><td>{billSeat(current,order) || 'Shared'}</td><td>{line.quantity}</td><td>{billMoney(line.price)}</td><td>{billMoney(line.quantity*line.price)}</td><td>{order.receiptId?'Paid':order.paymentStarted?'Part paid':'Unpaid'}</td></tr>))}</tbody></table></div>:<p>No orders yet. Add the first round below.</p>}<p>Bill total: <strong>{billMoney(total)}</strong></p><p>Paid: {billMoney(total-due)}</p><p>Amount due: <strong>{billMoney(due)}</strong></p><p>Order totals retain their saved taxes and discounts.</p><div className="report-actions"><AsyncButton className="filter-button" disabled={!bill.length} onClick={async()=>{if(!props.printBill)throw new Error('Bill printing is unavailable.');await props.printBill(current,bill.map(order=>({...order,tableService:{...order.tableService!,name:current.name,seat:billSeat(current,order)}})))}}>Print itemized bill</AsyncButton><button type="button" className="primary-button" disabled={!due || current.tillId!==checkoutTillId()} onClick={()=>{setPaymentOrder('');setSettle(true)}}>Settle remaining bill</button><AsyncButton className="filter-button" disabled={due>0 || orders.some(order=>!['collected','cancelled'].includes(order.status)) || current.tillId!==checkoutTillId()} onClick={async()=>{await command('close',{id:current.id,expectedUpdatedAt:current.updatedAt});setSelected(null);setMessage('Bill closed. The table is free.')}}>Close bill and free table</AsyncButton></div><div className="report-actions"><button type="button" className="filter-button" disabled={current.tillId!==checkoutTillId()} onClick={()=>{setArrange('move');setDestination('')}}>Move to another table</button><button type="button" className="filter-button" disabled={current.tillId!==checkoutTillId()} onClick={()=>{setArrange('merge');setDestination('')}}>Merge into another bill</button></div><p>Choose a whole bill, one seat, selected items or an equal share in payment entry. Orders and payments stay on the till that opened the bill.</p></section>}
    {arrange && current && <AsyncForm className="panel" onSubmit={async()=>{const target=data.tabs.find(tab=>tab.id===destination);await command('arrange',{expectedUpdatedAt:data.floor.updatedAt,action:arrange,tabId:current.id,sessionId:current.sessionId,...(arrange==='move'?{tableId:destination}:{targetId:target?.id,targetSessionId:target?.sessionId})});if(target && arrange==='merge')setSelected({id:target.id,sessionId:target.sessionId});setArrange('');setMessage(arrange==='move'?'Bill moved. Saved orders and receipts are preserved.':'Bills combined. The source table is free.')}}><h3>{arrange==='move'?'Move this bill':'Merge this bill into another'}</h3><label htmlFor="restaurant-destination">Destination</label><select id="restaurant-destination" required value={destination} onChange={event=>setDestination(event.target.value)}><option value="">Choose destination</option>{arrange==='move'?data.layout.tables.filter(table=>!data.tabs.some(tab=>tab.status==='open'&&!tab.mergedInto&&(tab.displayTableId??tab.tableId)===table.id)).map(table=><option key={table.id} value={table.id}>{table.name} - {table.seats} seats</option>):data.tabs.filter(tab=>tab.status==='open'&&!tab.mergedInto&&tab.id!==current.id&&tab.tillId===current.tillId).map(tab=><option key={tab.id} value={tab.id}>{tab.name}</option>)}</select>{arrange==='merge'&&<p>Merge this source bill before taking its payment. Items keep their original prices and seats are added after the destination's seats.</p>}<SubmitButton className="primary-button">{arrange==='move'?'Confirm table move':'Confirm bill merge'}</SubmitButton><button type="button" className="filter-button" onClick={()=>setArrange('')}>Cancel</button></AsyncForm>}
    {settle && current && due>0 && <RestaurantPayment key={'payment:'+current.sessionId+paymentOrder} tab={current} orders={data.orders} receipts={data.receipts} revision={data.ledgers.find(ledger=>ledger.sessionId===current.sessionId)?.updatedAt||''} storageKey={paymentKey} money={billMoney} initialOrder={paymentOrder} close={()=>setSettle(false)} save={async draft=>{if(!props.payBill)throw new Error('Bill payment is unavailable.');try{const receipt=await props.payBill(draft);setSavedPayment(receipt);setSettle(false);localStorage.removeItem(paymentKey);setMessage('Bill payment saved. One receipt covers the selected items.')}finally{await reload()}}}/>}
    {view==='tables' && current && savedPayment?.paymentDetails?.restaurantBill?.sessionId===current.sessionId && <section className="panel" role="status"><h3>Bill payment saved</h3><p>{savedPayment.id} - {new Intl.NumberFormat(undefined,{style:'currency',currency:savedPayment.currency||'USD'}).format(savedPayment.total)}</p><AsyncButton className="primary-button" onClick={()=>props.print(savedPayment)}>Print payment receipt</AsyncButton><DigitalReceipt sale={savedPayment} headers={props.headers} beforeSend={props.synchronize}/></section>}
    {(current || ['orders','preparation','setup'].includes(view)) && <CounterService {...props} orderLabel={order=>{const tab=data.tabs.find(tab=>!tab.mergedInto&&billContains(tab,order));return tab?tab.name+(billSeat(tab,order)?' / Seat '+billSeat(tab,order):' / Shared'):order.tableService?.name||''}} receipts={data.receipts} allowSetup={view==='setup'} initialTab={view==='setup'?'Menu':view==='preparation'?'Preparation':current?'New order':'Orders'} onTakePayment={order=>{const tab=data.tabs.find(tab=>tab.status==='open'&&!tab.mergedInto&&billContains(tab,order));if(tab){setView('tables');setSelected({id:tab.id,sessionId:tab.sessionId});setPaymentOrder(order.id);setSettle(true)}}} money={billMoney} key={'orders:'+view+':'+(current?.sessionId || 'restaurant-home')} restaurant billMembers={current?.billMembers} printTicket={order=>props.printTicket({...order,tableService:order.tableService&&{...order.tableService,name:data.tabs.find(tab=>tab.status==='open'&&!tab.mergedInto&&billContains(tab,order))?.name||order.tableService.name}})} tableSession={current} storageKey={props.storageKey+':'+(current?.sessionId||'setup')} onOrdersChanged={async()=>{await reload()}}/>}
    {refundReceipt && <CounterRefund sale={refundReceipt} returns={data.returns} money={amount=>new Intl.NumberFormat(undefined,{style:'currency',currency:refundReceipt.currency||'USD'}).format(amount)} close={()=>setRefundReceipt(null)} save={async input=>{await posRequest('/api/pos/returns',props.headers,input);setRefundReceipt(null);await reload();await props.refreshStock()}}/>}
    {view==='history' && <details open className="panel"><summary>Restaurant payment receipts</summary>{data.receipts.map(receipt=><div className="customer-row" key={receipt.id}><span>{receipt.id} - {new Intl.NumberFormat(undefined,{style:'currency',currency:receipt.currency||'USD'}).format(receipt.total)}</span><AsyncButton className="filter-button" onClick={()=>props.print(receipt)}>Reprint receipt</AsyncButton>{props.manager && <button type="button" className="filter-button" onClick={()=>setRefundReceipt(receipt)}>Refund receipt</button>}</div>)}</details>}
    {view==='history' && <details open className="panel"><summary>Closed bills</summary>{data.tabs.flatMap(tab=>[...(tab.history||[]),...(tab.status==='closed'?[tab]:[])]).map(tab=><div className="customer-row" key={tab.sessionId}><span>{tab.name} - {tab.sessionId.slice(0,8).toUpperCase()}</span><AsyncButton className="filter-button" onClick={async()=>{if(props.printBill)await props.printBill(tab,data.orders.filter(order=>billContains(tab,order) && order.status!=='cancelled').map(order=>({...order,tableService:{...order.tableService!,name:tab.name,seat:billSeat(tab,order)}})))}}>Reprint bill</AsyncButton></div>)}</details>}
  </section>
}
