import { PosProviderSelect } from './PosProviderSelect'
import { useEffect, useState } from 'react'
import { AsyncForm, SubmitButton } from './AsyncControls'
import { restaurantPortion, restaurantBillLines } from '../server/restaurant-payments.mjs'
import { restaurantBillFingerprint } from '../server/restaurant-service.mjs'
import type { CounterOrder } from './CounterService'
import type { RestaurantTab } from './RestaurantService'
import type { Sale } from './types'
export type BillPaymentDraft={contextOrder?:string;id:string;tabId:string;sessionId:string;expectedUpdatedAt:string;billFingerprint:string;selections:Array<{orderId:string;lineId:string;quantity:number}>;method:'cash'|'bank-transfer'|'external-pos'|'multiple';cash:string;provider:string;reference:string;cashReceived:string;allocations:Array<{method:'cash'|'bank-transfer'|'external-pos';amount:string;provider:string;reference:string}>}
export function RestaurantPayment({providers = [],tab,orders,receipts,revision,storageKey,money,initialOrder,save,close}:{providers?:string[];tab:RestaurantTab;orders:CounterOrder[];receipts:Sale[];revision:string;storageKey:string;money:(n:number)=>string;initialOrder?:string;save:(draft:BillPaymentDraft)=>Promise<void>;close:()=>void}) {
  const available=restaurantBillLines(tab,orders,receipts)
  const chooseAll=()=>available.filter(line=>line.remaining>0 && (!initialOrder || line.orderId===initialOrder)).map(line=>({orderId:line.orderId,lineId:line.lineId,quantity:line.remaining}))
  const fresh=():BillPaymentDraft=>({contextOrder:initialOrder||'',id:'restaurant-payment:'+crypto.randomUUID(),tabId:tab.id,sessionId:tab.sessionId,expectedUpdatedAt:revision,billFingerprint:restaurantBillFingerprint(tab,orders),selections:chooseAll(),method:'cash',cash:'',provider:'',reference:'',cashReceived:'',allocations:[{method:'cash',amount:'',provider:'',reference:''},{method:'external-pos',amount:'',provider:'',reference:''}]})
  const [draft,setDraft]=useState<BillPaymentDraft>(()=>{try{const saved=JSON.parse(localStorage.getItem(storageKey)||'null');return saved?.tabId===tab.id && saved?.sessionId===tab.sessionId && (saved.contextOrder||'')===(initialOrder||'') && Array.isArray(saved.selections) ? saved : fresh()}catch{return fresh()}})
  const [mode,setMode]=useState(()=>{try{return JSON.parse(localStorage.getItem(storageKey+':options')||'{}').mode||'whole'}catch{return 'whole'}}),[seat,setSeat]=useState(()=>{try{return JSON.parse(localStorage.getItem(storageKey+':options')||'{}').seat||'0'}catch{return '0'}}),[people,setPeople]=useState(()=>{try{return JSON.parse(localStorage.getItem(storageKey+':options')||'{}').people||'2'}catch{return '2'}}),[storageError,setStorageError]=useState('')
  useEffect(()=>{try{localStorage.setItem(storageKey,JSON.stringify(draft));localStorage.setItem(storageKey+':options',JSON.stringify({mode,seat,people}));setStorageError('')}catch{setStorageError('This payment entry could not be saved on this device. Keep it open until payment is recorded.')}},[draft,storageKey,mode,seat,people])
  let portion:any=null,pricingError=''
  try{portion=restaurantPortion(tab,orders,receipts,draft.selections)}catch(error){pricingError=error instanceof Error?error.message:'Review the selected items.'}
  const changed=draft.billFingerprint!==restaurantBillFingerprint(tab,orders) || draft.expectedUpdatedAt!==revision
  const total=portion?.pricing.total||0
  function selection(mode:string,value=seat,count=people) {
    setMode(mode)
    const lines=available.filter(line=>line.remaining>0 && (!initialOrder || line.orderId===initialOrder) && (mode!=='seat' || line.seat===Number(value)))
    const selected=lines.map(line=>({orderId:line.orderId,lineId:line.lineId,quantity:mode==='equal'?Math.max(1,Math.floor(line.remaining*1000/Math.max(2,Number(count)||2)))/1000:line.remaining}))
    setDraft({...draft,selections:selected})
  }
  return <AsyncForm className="panel restaurant-payment" busyLabel="Recording bill payment..." onSubmit={async()=>{await save(draft)}}>
    <h3>Pay bill</h3><p>One receipt covers all selected items. Choose how much of the bill this customer is paying.</p>
    {changed && <p role="alert">This bill changed. Review the remaining items and use Refresh payment entry before paying.</p>}
    <label htmlFor="restaurant-payment-split">Items to pay for</label><select id="restaurant-payment-split" value={mode} onChange={event=>selection(event.target.value)}><option value="whole">All remaining items</option><option value="seat">One seat</option><option value="items">Choose items and quantities</option><option value="equal">Equal share of the remaining bill</option></select>
    {mode==='seat' && <><label htmlFor="restaurant-payment-seat">Pay for seat</label><select id="restaurant-payment-seat" value={seat} onChange={event=>{setSeat(event.target.value);selection('seat',event.target.value)}}><option value="0">Shared items</option>{Array.from({length:tab.guests},(_,index)=><option key={index} value={index+1}>Seat {index+1}</option>)}</select></>}
    {mode==='equal' && <><label>Number of people sharing the remainder<input type="number" min="2" max="20" step="1" value={people} onChange={event=>{setPeople(event.target.value);selection('equal',seat,event.target.value)}}/></label><p>Record this person's share now. The remaining quantities and any rounding cents stay on the bill for the next payment.</p></>}
    <div className="table-scroll"><table><thead><tr><th>Item</th><th>Seat</th><th>Unpaid qty</th><th>Pay qty</th></tr></thead><tbody>{available.filter(line=>line.remaining>0 && (!initialOrder||line.orderId===initialOrder)).map(line=>{const selected=draft.selections.find(part=>part.orderId===line.orderId&&part.lineId===line.lineId);return <tr key={line.orderId+line.lineId}><td>{line.description}</td><td>{line.seat||'Shared'}</td><td>{line.remaining}</td><td>{mode==='items'?<input aria-label={'Pay quantity for '+line.description} type="number" min="0" max={line.remaining} step="0.001" value={selected?.quantity||0} onChange={event=>{const quantity=Number(event.target.value);setDraft({...draft,selections:[...draft.selections.filter(part=>part.orderId!==line.orderId||part.lineId!==line.lineId),...(quantity>0?[{orderId:line.orderId,lineId:line.lineId,quantity}]:[])]})}}/>:selected?.quantity||0}</td></tr>})}</tbody></table></div>
    <p>Payment total: <strong>{money(total)}</strong></p>{pricingError && <p role="alert">{pricingError}</p>}
    <label htmlFor="restaurant-bill-payment-method">Payment Method</label><select id="restaurant-bill-payment-method" value={draft.method} onChange={event=>setDraft({...draft,method:event.target.value as BillPaymentDraft['method']})}><option value="cash">Cash</option><option value="bank-transfer">Bank Transfer</option><option value="external-pos">POS Terminal</option><option value="multiple">Cash / card / transfer together</option></select>
    {draft.method==='cash'?<><label>Bill cash received<input type="number" min={total} step="0.01" value={draft.cash} placeholder={String(total)} onChange={event=>setDraft({...draft,cash:event.target.value})}/></label><p>Change: {money(Math.max(0,Number(draft.cash||total)-total))}</p></>:draft.method==='multiple'?<><p>Payment parts must equal {money(total)}.</p>{draft.allocations.map((part,index)=><fieldset key={index}><legend>Payment part {index+1}</legend><label>Part method<select value={part.method} onChange={event=>setDraft({...draft,allocations:draft.allocations.map((row,i)=>i===index?{...row,method:event.target.value as typeof part.method}:row)})}><option value="cash">Cash</option><option value="external-pos">POS Terminal</option><option value="bank-transfer">Bank Transfer</option></select></label><label>Part amount<input required type="number" min="0.01" step="0.01" value={part.amount} onChange={event=>setDraft({...draft,allocations:draft.allocations.map((row,i)=>i===index?{...row,amount:event.target.value}:row)})}/></label>{part.method!=='cash' && <>{part.method === 'external-pos' ? <PosProviderSelect providers={providers} value={part.provider} onChange={provider=>setDraft({...draft,allocations:draft.allocations.map((row,i)=>i===index?{...row,provider}:row)})} /> : <label>Bank Transfer provider<input required value={part.provider} onChange={event=>setDraft({...draft,allocations:draft.allocations.map((row,i)=>i===index?{...row,provider:event.target.value}:row)})}/></label>}<label>Part reference<input required value={part.reference} onChange={event=>setDraft({...draft,allocations:draft.allocations.map((row,i)=>i===index?{...row,reference:event.target.value}:row)})}/></label></>}<button type="button" className="filter-button" disabled={draft.allocations.length<=2} onClick={()=>setDraft({...draft,allocations:draft.allocations.filter((_,i)=>i!==index)})}>Remove payment part</button></fieldset>)}<button type="button" className="filter-button" disabled={draft.allocations.length>=10} onClick={()=>setDraft({...draft,allocations:[...draft.allocations,{method:'bank-transfer',amount:'',provider:'',reference:''}]})}>Add payment part</button><label>Cash handed over for the cash parts (optional)<input type="number" min="0" step="0.01" value={draft.cashReceived} onChange={event=>setDraft({...draft,cashReceived:event.target.value})}/></label><p>Confirm all card and transfer parts succeeded before saving.</p></>:<>{draft.method === 'external-pos' ? <PosProviderSelect providers={providers} value={draft.provider} onChange={provider => setDraft({...draft,provider})} /> : <label>Bank Transfer provider<input required value={draft.provider} onChange={event=>setDraft({...draft,provider:event.target.value})}/></label>}<label>Bill payment reference<input required value={draft.reference} onChange={event=>setDraft({...draft,reference:event.target.value})}/></label><p>Confirm success on the bank or terminal before recording payment.</p></>}
    {storageError && <p role="alert">{storageError}</p>}
    <SubmitButton className="primary-button" disabled={!total || !!pricingError || changed}>Save bill payment</SubmitButton><button type="button" className="filter-button" onClick={()=>{setDraft(fresh());setMode('whole')}}>Refresh payment entry</button><button type="button" className="filter-button" onClick={close}>Close payment entry</button>
  </AsyncForm>
}
