import { useEffect, useState } from 'react'
import { AsyncButton, AsyncForm, SubmitButton } from './AsyncControls'
import { posRequest } from './PosTools'
import { reservationLocalTime } from '../server/reservation-time.mjs'
import { businessDate } from '../server/report-timezone.mjs'

export type Reservation = {id:string;name:string;phone:string;guests:number;tableId:string;tableName:string;startAt:string;endAt:string;timeZone:string;occurrence:string;endOccurrence:string;note:string;status:string;billId?:string;sessionId?:string;events:any[];archived?:boolean}
type Draft = {action:'create'|'update';id:string;commandId:string;expectedUpdatedAt:string;name:string;phone:string;guests:string;tableId:string;startLocal:string;endLocal:string;timeZone:string;occurrence:string;endOccurrence:string;note:string}
type Data = {book:{updatedAt:string;entries:Reservation[];archiveIds?:string[]};archives:Array<{entries:Reservation[]}>;timeZone:string;layout:{tables:Array<{id:string;name:string;seats:number}>};tabs:any[]}
const fresh=(timeZone='UTC',revision=''):Draft=>({action:'create',id:'reservation:'+crypto.randomUUID(),commandId:crypto.randomUUID(),expectedUpdatedAt:revision,name:'',phone:'',guests:'2',tableId:'',startLocal:reservationLocalTime(new Date(Date.now()+3600000).toISOString(),timeZone),endLocal:reservationLocalTime(new Date(Date.now()+7200000).toISOString(),timeZone),timeZone,occurrence:'earlier',endOccurrence:'earlier',note:''})
const labels:Record<string,string>={confirmed:'Confirmed',arrived:'Arrived',seated:'Seated',completed:'Completed',cancelled:'Cancelled','no-show':'No-show'}
const live=(row:Reservation)=>['confirmed','arrived','seated'].includes(row.status)
const csv=(value:unknown)=>{let text=String(value??'');if(/^[\s]*[=+@-]/.test(text))text="'"+text;return '"'+text.replace(/"/g,'""')+'"'}

export function RestaurantReservations({headers,storageKey,manager,onOpen,onBill}: {
  headers:Record<string,string>;storageKey:string;manager:boolean;
  onOpen:(reservation:Reservation)=>void;onBill:(bill:{id:string;sessionId:string})=>void
}) {
  const key=storageKey+':reservations'
  const [saved]=useState(()=>{try{return JSON.parse(localStorage.getItem(key)||'{}')}catch{return {}}})
  const [draft,setDraft]=useState<Draft>(()=>({...fresh(),...(saved.draft||{})})),[creating,setCreating]=useState(Boolean(saved.creating))
  const [selected,setSelected]=useState<string>(saved.selected||''),[pending,setPending]=useState<any>(saved.pending||null)
  const [data,setData]=useState<Data>({book:{updatedAt:'',entries:[]},archives:[],timeZone:'UTC',layout:{tables:[]},tabs:[]})
  const [loaded,setLoaded]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[search,setSearch]=useState(''),[date,setDate]=useState(''),[filter,setFilter]=useState('active')
  const [saving,setSaving]=useState(false)
  async function reload(){const next=await posRequest('/api/pos/restaurant/reservations',headers);setData(next);setLoaded(true);return next as Data}
  useEffect(()=>{let active=true;const load=()=>{void posRequest('/api/pos/restaurant/reservations',headers).then(value=>{if(active){setData(value);setLoaded(true);setError('')}}).catch(e=>{if(active)setError(e.message)})};load();const timer=setInterval(load,10000);window.addEventListener('stockroom-data-refreshed',load);return()=>{active=false;clearInterval(timer);window.removeEventListener('stockroom-data-refreshed',load)}},[headers.Authorization,headers['X-Stockroom-Branch']])
  useEffect(()=>{try{localStorage.setItem(key,JSON.stringify({draft,creating,selected,pending}))}catch{setError('This reservation draft could not be saved. Keep the screen open.')}},[key,draft,creating,selected,pending])
  const all=[...data.book.entries,...data.archives.flatMap(archive=>archive.entries.map(row=>({...row,archived:true})))],row=all.find(row=>row.id===selected)
  const visible=all.filter(row=>(filter==='all'||filter==='active'&&live(row)||filter==='history'&&!live(row))&&(!date||(businessDate(row.startAt,data.timeZone)<=date&&businessDate(new Date(Date.parse(row.endAt)-1).toISOString(),data.timeZone)>=date))&&[row.name,row.phone,row.tableName,row.id,row.note].join(' ').toLowerCase().includes(search.toLowerCase())).sort((a,b)=>a.startAt.localeCompare(b.startAt))
  const existing=row?data.tabs.find(bill=>bill.status==='open'&&!bill.mergedInto&&bill.reservationId===row.id):null
  async function send(input:any){setSaving(true);try{const result=await posRequest('/api/pos/restaurant/reservations',headers,input);await reload();window.dispatchEvent(new Event('stockroom-data-refreshed'));return result}finally{setSaving(false)}}
  function status(action:string){if(!row)return;setPending({action,id:row.id,commandId:crypto.randomUUID(),expectedUpdatedAt:data.book.updatedAt,...(action==='seat'?{billId:existing?.id,sessionId:existing?.sessionId}:{}),...(['cancel','no-show'].includes(action)?{reason:''}:{})});setMessage('')}
  function exportHistory(){const rows=[['Reservation ID','Guest','Phone','Guests','Table','Arrival (UTC)','Departure (UTC)','Booked timezone','Status','Note','Archived'],...all.map(row=>[row.id,row.name,row.phone,row.guests,row.tableName,row.startAt,row.endAt,row.timeZone,row.status,row.note,row.archived?'Yes':'No'])];const url=URL.createObjectURL(new Blob([rows.map(row=>row.map(csv).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='reservations-'+businessDate(new Date().toISOString(),data.timeZone)+'.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  return <section className="restaurant-reservations"><section className="panel"><h3>Reservations</h3><p>Book tables or keep an unassigned request. Times use {data.timeZone}, on every device. An unassigned request does not hold a table. Reservations do not collect deposits or record sales.</p><p>Synchronize before confirming a shared booking. Conflicting offline calendars need review in Sync issues.</p>
    <div className="report-actions"><button type="button" className="primary-button" disabled={!loaded||saving||Boolean(pending)} onClick={()=>{if(!creating)setDraft(fresh(data.timeZone,data.book.updatedAt));setCreating(true);setSelected('');setMessage('')}}>New reservation</button><AsyncButton className="filter-button" onClick={async()=>{await reload();setMessage('Reservations refreshed. Drafts were kept.')}}>Refresh reservations</AsyncButton>{manager&&<><button type="button" className="filter-button" disabled={!loaded} onClick={exportHistory}>Export reservation history</button><button type="button" className="filter-button" disabled={Boolean(pending)||saving||!data.book.entries.some(row=>!live(row))} onClick={()=>setPending({action:'archive',id:'reservation:archive-'+crypto.randomUUID(),commandId:crypto.randomUUID(),expectedUpdatedAt:data.book.updatedAt})}>Archive finished reservations</button></>}</div>
    {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
  </section>
  {creating&&!pending&&<AsyncForm className="panel settings-form" onSubmit={async()=>{const result=await send({...draft,guests:Number(draft.guests)});setCreating(false);setSelected(result.entry.id);setDraft(fresh(data.timeZone,result.book.updatedAt));setMessage('Reservation saved. No payment was recorded.')}}>
    <h3>{draft.action==='create'?'New reservation':'Change reservation'}</h3><p>Enter times in {draft.timeZone}. Changing business settings does not rewrite saved booking times.</p>
    <label>Guest name<input required maxLength={100} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Guest phone (optional)<input type="tel" maxLength={80} value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})}/></label><label>Reservation guests<input required type="number" min="1" max="100" step="1" value={draft.guests} onChange={e=>setDraft({...draft,guests:e.target.value})}/></label>
    <label>Reservation table<select aria-label="Reservation table" value={draft.tableId} onChange={e=>setDraft({...draft,tableId:e.target.value})}><option value="">Unassigned request - no table held</option>{data.layout.tables.map(table=><option key={table.id} value={table.id}>{table.name} / {table.seats} seats</option>)}</select></label>
    <label>Expected arrival<input required type="datetime-local" value={draft.startLocal} onChange={e=>setDraft({...draft,startLocal:e.target.value})}/></label><label>Expected departure<input required type="datetime-local" value={draft.endLocal} onChange={e=>setDraft({...draft,endLocal:e.target.value})}/></label>
    <details><summary>Daylight-saving repeated time</summary><p>If a clock time occurs twice when clocks go back, choose the earlier or later occurrence separately for arrival and departure. A skipped clock time cannot be booked.</p><label>Arrival repeated time choice<select aria-label="Arrival repeated time choice" value={draft.occurrence} onChange={e=>setDraft({...draft,occurrence:e.target.value})}><option value="earlier">Earlier occurrence</option><option value="later">Later occurrence</option></select></label><label>Departure repeated time choice<select aria-label="Departure repeated time choice" value={draft.endOccurrence} onChange={e=>setDraft({...draft,endOccurrence:e.target.value})}><option value="earlier">Earlier occurrence</option><option value="later">Later occurrence</option></select></label></details>
    <label>Reservation note<textarea maxLength={1000} value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})}/></label>
    {draft.expectedUpdatedAt!==data.book.updatedAt&&<><p role="alert">The calendar changed. Check current reservations before retrying or reviewing this draft.</p><button type="button" className="filter-button" onClick={()=>setDraft({...draft,expectedUpdatedAt:data.book.updatedAt,commandId:crypto.randomUUID(),timeZone:data.timeZone})}>Review current calendar for this draft</button></>}
    <SubmitButton className="primary-button">Save reservation</SubmitButton><button type="button" className="filter-button" onClick={()=>setCreating(false)}>Cancel</button>
  </AsyncForm>}
  {pending&&<AsyncForm className="panel settings-form" onSubmit={async()=>{const result=await send(pending);setPending(null);setMessage(pending.action==='archive'?'Finished reservations archived. Their history is preserved.':'Reservation status saved.');if(result.entry)setSelected(result.entry.id)}}>
    <h3>{pending.action==='archive'?'Archive finished reservations':`Confirm ${pending.action==='arrive'?'arrival':pending.action==='seat'?'seating':pending.action==='complete'?'completed visit':labels[pending.action]||pending.action}`}</h3>
    <p>{pending.action==='archive'?'Completed, cancelled and no-show bookings move to saved history. Active bookings remain in the calendar; no reservation is deleted.':row?.name}</p>
    {['cancel','no-show'].includes(pending.action)&&<label>Reservation status reason<input required maxLength={300} value={pending.reason} onChange={e=>setPending({...pending,reason:e.target.value})}/></label>}
    <SubmitButton className={['cancel','no-show','archive'].includes(pending.action)?'closure-confirm':'primary-button'}>Confirm reservation action</SubmitButton><button type="button" className="filter-button" disabled={saving} onClick={()=>setPending(null)}>Cancel</button>
    {pending.expectedUpdatedAt!==data.book.updatedAt&&<button type="button" className="filter-button" onClick={()=>setPending({...pending,expectedUpdatedAt:data.book.updatedAt,commandId:crypto.randomUUID()})}>Review current calendar for this action</button>}
  </AsyncForm>}
  {row&&!creating&&!pending&&<section className="panel"><button type="button" className="filter-button" onClick={()=>setSelected('')}>Back to reservations</button><h3>{row.name}</h3><p>{row.phone} / {row.guests} guests / {row.tableName||'Unassigned'}</p><p>{reservationLocalTime(row.startAt,data.timeZone).replace('T',' ')} to {reservationLocalTime(row.endAt,data.timeZone).replace('T',' ')} / {data.timeZone}</p><p>{labels[row.status]}{row.archived?' / Archived':''}{row.note?' / '+row.note:''}</p>{row.sessionId&&<p>Linked bill: {row.billId} / Session {row.sessionId}</p>}
    {!row.archived&&<div className="report-actions">{['confirmed','arrived'].includes(row.status)&&<button type="button" className="filter-button" onClick={()=>{setDraft({action:'update',id:row.id,commandId:crypto.randomUUID(),expectedUpdatedAt:data.book.updatedAt,name:row.name,phone:row.phone,guests:String(row.guests),tableId:row.tableId,startLocal:reservationLocalTime(row.startAt,data.timeZone),endLocal:reservationLocalTime(row.endAt,data.timeZone),timeZone:data.timeZone,occurrence:row.occurrence,endOccurrence:row.endOccurrence,note:row.note});setCreating(true)}}>Assign table / change reservation</button>}{row.status==='confirmed'&&<button type="button" className="filter-button" onClick={()=>status('arrive')}>Mark arrived</button>}{['confirmed','arrived'].includes(row.status)&&row.tableId&&!existing&&<button type="button" className="primary-button" disabled={Date.now()<Date.parse(row.startAt)-1800000||Date.now()>=Date.parse(row.endAt)} onClick={()=>onOpen(row)}>Open reservation bill</button>}{existing&&<button type="button" className="filter-button" onClick={()=>onBill(existing)}>Go to reservation bill</button>}{['confirmed','arrived'].includes(row.status)&&existing&&<button type="button" className="primary-button" onClick={()=>status('seat')}>Mark seated</button>}{row.status==='seated'&&<button type="button" className="filter-button" onClick={()=>status('complete')}>Mark visit completed</button>}{['confirmed','arrived'].includes(row.status)&&<><button type="button" className="filter-button" onClick={()=>status('cancel')}>Cancel reservation</button><button type="button" className="filter-button" onClick={()=>status('no-show')}>Mark no-show</button></>}</div>}
    <details><summary>Reservation history</summary>{row.events.map(event=><p key={event.commandId}>{new Date(event.at).toLocaleString()} / {event.staffName} / {event.input.action}{event.input.reason?' / '+event.input.reason:''}{['create','update'].includes(event.input.action)?` / ${event.input.name}, ${event.input.guests} guests / ${event.input.startLocal} to ${event.input.endLocal} (${event.input.timeZone})`:''}</p>)}</details>
  </section>}
  {!creating&&!pending&&!row&&<section className="panel"><label>Find reservation<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Guest, phone, table or reference"/></label><label>Booking date (optional)<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Show reservations<select aria-label="Show reservations" value={filter} onChange={e=>setFilter(e.target.value)}><option value="active">Active bookings</option><option value="history">Finished and archived history</option><option value="all">All reservations</option></select></label>{visible.length?visible.map(row=><button type="button" className="filter-button job-list-item" key={row.id} onClick={()=>setSelected(row.id)}><strong>{row.name} / {row.guests} guests / {row.tableName||'Unassigned'}</strong><span>{reservationLocalTime(row.startAt,data.timeZone).replace('T',' ')} / {labels[row.status]}{row.archived?' / Archived':''}</span>{live(row)&&Date.parse(row.endAt)<Date.now()&&<span>Booking time ended: review its status.</span>}</button>):<p>No matching reservations.</p>}</section>}
  </section>
}
