import { useEffect, useState } from 'react'
import { AsyncButton, AsyncForm, SubmitButton } from './AsyncControls'
import { posRequest, DigitalReceipt } from './PosTools'
import { PosProviderSelect } from './PosProviderSelect'
import { CounterRefund } from './CounterService'
import { printDocument } from './lib/printing'
import { createPortal, flushSync } from 'react-dom'
import type { Sale } from './types'
const labels: Record<string,string> = {estimate:'Estimate',new:'New', 'in-progress':'In progress',ready:'Ready',completed:'Completed',cancelled:'Cancelled'}
const fresh = () => ({id:'service-job:'+crypto.randomUUID(),commandId:crypto.randomUUID(),expectedUpdatedAt:'',estimate:false,title:'',customerName:'',customerPhone:'',note:'',dueDate:'',lines:[{id:crypto.randomUUID(),description:'',quantity:'1',price:''}]})
function read<T>(key:string,fallback:()=>T):T { try {return JSON.parse(localStorage.getItem(key)||'null') || fallback()}catch{return fallback()} }
export function ServiceJobs({headers,storageKey,providers,money,print,manager,enabled,beforeSend}:{headers:Record<string,string>;storageKey:string;providers:string[];money:(n:number)=>string;print:(sale:Sale)=>Promise<void>;manager:boolean;enabled:boolean;beforeSend:()=>Promise<void>}) {
 const [jobs,setJobs]=useState<any[]>([]),[error,setError]=useState(''),[message,setMessage]=useState('')
 const [draft,setDraft]=useState(()=>read(storageKey+':job-draft',fresh))
 const [creating,setCreating]=useState(false),[selected,setSelected]=useState(()=>localStorage.getItem(storageKey+':selected-job')||'')
 const [pay,setPay]=useState<any>(null),[receipt,setReceipt]=useState<Sale|null>(null),[refund,setRefund]=useState<Sale|null>(null),[returns,setReturns]=useState<any[]>([])
 const [document,setDocument]=useState<{job:any;kind:string}|null>(null)
 const job=jobs.find(item=>item.id===selected)
 const jobMoney=(amount:number,source=job)=>source?new Intl.NumberFormat(undefined,{style:'currency',currency:source.currency}).format(amount):money(amount)
 async function reload(){const data=await posRequest('/api/pos/service-jobs',headers);setJobs(data.jobs);return data.jobs}
 useEffect(()=>{let live=true;const load=async()=>{try{const data=await posRequest('/api/pos/service-jobs',headers);if(live){setJobs(data.jobs);setError('')}}catch(e){if(live)setError((e as Error).message)}};void load();const timer=setInterval(load,10000);window.addEventListener('stockroom-data-refreshed',load);return()=>{live=false;clearInterval(timer);window.removeEventListener('stockroom-data-refreshed',load)}},[headers.Authorization,headers['X-Stockroom-Branch']])
 useEffect(()=>{try{localStorage.setItem(storageKey+':job-draft',JSON.stringify(draft));localStorage.setItem(storageKey+':selected-job',selected)}catch{setError('Job draft could not be saved. Keep this screen open.')}},[draft,selected,storageKey])
 useEffect(()=>{if(!job || pay)return;const saved=read<any>(storageKey+':job-payment:'+job.id,()=>null);if(saved){const existing=job.payments.find((entry:any)=>entry.sale.id==='service-payment:'+saved.commandId);if(existing){setReceipt(existing.sale);localStorage.removeItem(storageKey+':job-payment:'+job.id)}else setPay(saved)}},[job?.id,job?.updatedAt])
 useEffect(()=>{if(pay)try{localStorage.setItem(storageKey+':job-payment:'+pay.id,JSON.stringify(pay))}catch{setError('Payment draft could not be saved. Keep this screen open.')}},[pay,storageKey])
 async function act(path:string,input:any){setError('');const result=await posRequest(path,headers,input);await reload();window.dispatchEvent(new Event('stockroom-data-refreshed'));return result}
 async function printJob(kind:string){flushSync(()=>setDocument({job,kind}));try{await printDocument('order')}finally{setDocument(null)}}
 function beginPayment(){setReceipt(null);setPay({id:job.id,commandId:crypto.randomUUID(),expectedUpdatedAt:job.updatedAt,amount:String(job.balance.due),method:'cash',cash:'',provider:'',reference:''})}
 return <section className="service-jobs"><div className="panel-heading"><h2>Jobs &amp; invoices</h2><button type="button" className="primary-button" onClick={()=>{setCreating(true);setSelected('');setPay(null)}}>New job / estimate</button></div>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 {creating?<AsyncForm className="panel settings-form" onSubmit={async()=>{const result=await act('/api/pos/service-jobs',{...draft,lines:draft.lines.map(line=>({...line,quantity:Number(line.quantity),price:Number(line.price)}))});setSelected(result.job.id);setCreating(false);setDraft(fresh())}}>
 <h3>New job</h3><label>Job description<input required maxLength={200} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Customer name<input required maxLength={200} value={draft.customerName} onChange={e=>setDraft({...draft,customerName:e.target.value})}/></label><label>Customer phone<input maxLength={80} value={draft.customerPhone} onChange={e=>setDraft({...draft,customerPhone:e.target.value})}/></label>
 {draft.lines.map((line,index)=><fieldset key={line.id}><legend>Item {index+1}</legend><label>Job item<input required maxLength={150} value={line.description} onChange={e=>setDraft({...draft,lines:draft.lines.map(row=>row.id===line.id?{...row,description:e.target.value}:row)})}/></label><div className="form-grid"><label>Quantity<input required type="number" min="0.001" step="0.001" value={line.quantity} onChange={e=>setDraft({...draft,lines:draft.lines.map(row=>row.id===line.id?{...row,quantity:e.target.value}:row)})}/></label><label>Unit price<input required type="number" min="0" step="0.01" value={line.price} onChange={e=>setDraft({...draft,lines:draft.lines.map(row=>row.id===line.id?{...row,price:e.target.value}:row)})}/></label></div>{draft.lines.length>1&&<button type="button" className="filter-button" onClick={()=>setDraft({...draft,lines:draft.lines.filter(row=>row.id!==line.id)})}>Remove item</button>}</fieldset>)}
 <button type="button" className="filter-button" disabled={draft.lines.length>=100} onClick={()=>setDraft({...draft,lines:[...draft.lines,{id:crypto.randomUUID(),description:'',quantity:'1',price:''}]})}>Add job item</button><details><summary>Due date and instructions (optional)</summary><label>Due date<input type="date" value={draft.dueDate} onChange={e=>setDraft({...draft,dueDate:e.target.value})}/></label><label>Job instructions<textarea maxLength={1000} value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></details><label><input type="checkbox" checked={draft.estimate} onChange={e=>setDraft({...draft,estimate:e.target.checked})}/>Start as an estimate</label><p>Prices are saved when issued. Receipt tax settings apply. No stock is reduced.</p><SubmitButton className="primary-button" disabled={!enabled}>Save job</SubmitButton><button type="button" className="filter-button" onClick={()=>setCreating(false)}>Back to jobs</button>
 </AsyncForm>:job?<section className="panel"><button type="button" className="filter-button" onClick={()=>{setSelected('');setPay(null);setReceipt(null)}}>Back to jobs</button><h3>{job.title}</h3><p>{job.customerName}{job.customerPhone&&' / '+job.customerPhone} / {labels[job.status]}</p><p>{job.status==='estimate'?'Estimate':'Invoice'} #{job.id.slice(-8).toUpperCase()}{job.dueDate&&' / Due '+job.dueDate}</p><div className="payment-summary"><p>Total: {jobMoney(job.pricing.total)}</p><p>Received: {jobMoney(job.balance.paid)}{job.balance.refunded>0&&' / Refunded: '+jobMoney(job.balance.refunded)}</p><p><strong>{job.status==='estimate'?'Quoted total':job.status==='cancelled'?'Cancelled; balance':'Balance due'}: {jobMoney(job.balance.due)}</strong></p></div><div className="report-actions"><AsyncButton className="filter-button" onClick={()=>printJob(job.status==='estimate'?'estimate':'invoice')}>Print {job.status==='estimate'?'estimate':'invoice'}</AsyncButton>{!['estimate','cancelled'].includes(job.status)&&<AsyncButton className="filter-button" onClick={()=>printJob('job')}>Print job ticket</AsyncButton>}{job.status==='estimate'&&<AsyncButton className="primary-button" onClick={()=>act('/api/pos/service-jobs/status',{id:job.id,commandId:crypto.randomUUID(),expectedUpdatedAt:job.updatedAt,status:'new'})}>Accept estimate / issue invoice</AsyncButton>}{!['estimate','cancelled'].includes(job.status)&&job.balance.due>0&&!pay&&<button type="button" className="primary-button" disabled={!enabled} onClick={beginPayment}>Take payment</button>}</div>
 {pay&&<AsyncForm className="settings-form" onSubmit={async()=>{const result=await act('/api/pos/service-jobs/pay',pay);setReceipt(result.sale);localStorage.removeItem(storageKey+':job-payment:'+job.id);setPay(null)}}><h3>Invoice payment</h3><label>Payment amount<input required type="number" min="0.01" max={job.balance.due} step="0.01" value={pay.amount} onChange={e=>setPay({...pay,amount:e.target.value})}/></label><label htmlFor="job-payment-method">Payment Method</label><select id="job-payment-method" value={pay.method} onChange={e=>setPay({...pay,method:e.target.value,cash:'',reference:''})}><option value="cash">Cash</option><option value="external-pos">POS Terminal</option><option value="bank-transfer">Bank Transfer</option></select>{pay.method==='cash'?<label>Cash received<input type="number" min={pay.amount} step="0.01" value={pay.cash} placeholder={pay.amount} onChange={e=>setPay({...pay,cash:e.target.value})}/></label>:<>{pay.method==='external-pos'?<PosProviderSelect providers={providers} value={pay.provider} onChange={provider=>setPay((value:any)=>({...value,provider}))}/>:<label>Bank Transfer provider<input required value={pay.provider} onChange={e=>setPay({...pay,provider:e.target.value})}/></label>}<label>Payment reference<input required value={pay.reference} onChange={e=>setPay({...pay,reference:e.target.value})}/></label><p>Confirm the payment succeeded outside the app before saving.</p></>}<SubmitButton className="primary-button" disabled={!enabled}>Save invoice payment</SubmitButton><button type="button" className="filter-button" onClick={()=>{localStorage.removeItem(storageKey+':job-payment:'+job.id);setPay(null)}}>Close payment</button>{pay.expectedUpdatedAt!==job.updatedAt&&<button type="button" className="filter-button" onClick={()=>setPay({...pay,expectedUpdatedAt:job.updatedAt,commandId:crypto.randomUUID()})}>Review updated invoice</button>}</AsyncForm>}
 {receipt&&<div role="status"><p>Payment saved: {jobMoney(receipt.total)}</p><AsyncButton className="primary-button" onClick={()=>print(receipt)}>Print receipt</AsyncButton><DigitalReceipt sale={receipt} headers={headers} beforeSend={beforeSend}/></div>}
 <details><summary>Job details and actions</summary>{job.lines.map((line:any)=><p key={line.id}>{line.description} / {line.quantity} x {jobMoney(line.price)}</p>)}{job.note&&<p>{job.note}</p>}{({new:'in-progress','in-progress':'ready',ready:'completed'} as Record<string,string>)[job.status]&&<AsyncButton className="filter-button" onClick={()=>act('/api/pos/service-jobs/status',{id:job.id,commandId:crypto.randomUUID(),expectedUpdatedAt:job.updatedAt,status:({new:'in-progress','in-progress':'ready',ready:'completed'} as Record<string,string>)[job.status]})}>Mark {labels[({new:'in-progress','in-progress':'ready',ready:'completed'} as Record<string,string>)[job.status]]}</AsyncButton>}{manager&&job.status!=='cancelled'&&<AsyncButton className="filter-button" onClick={async()=>{await act('/api/pos/service-jobs/status',{id:job.id,commandId:crypto.randomUUID(),expectedUpdatedAt:job.updatedAt,status:'cancelled'});setMessage('Job cancelled. History is retained.')}}>Cancel job</AsyncButton>}</details>
 {job.payments.length>0&&<details><summary>Payment history</summary>{job.payments.map((entry:any)=><div className="customer-row" key={entry.sale.id}><div><strong>{jobMoney(entry.sale.total)}</strong><small>{new Date(entry.sale.createdAt).toLocaleString()} / {entry.sale.id.slice(-8).toUpperCase()}</small></div><AsyncButton className="filter-button" onClick={()=>print(entry.sale)}>Reprint receipt</AsyncButton>{manager&&<AsyncButton className="filter-button" onClick={async()=>{const data=await posRequest('/api/pos',headers);setReturns(data.returns);setRefund(entry.sale)}}>Refund payment</AsyncButton>}</div>)}</details>}
 {refund&&<CounterRefund title="Refund invoice payment" sale={refund} returns={returns} money={jobMoney} close={()=>setRefund(null)} save={async input=>{await posRequest('/api/pos/returns',headers,input);await reload();setRefund(null);setMessage('Refund recorded. The balance has been updated.');window.dispatchEvent(new Event('stockroom-data-refreshed'))}}/>}
 </section>:<div className="panel">{!jobs.length?<p>No jobs yet. Immediate payments remain in New payment.</p>:jobs.map(item=><button type="button" className="filter-button job-list-item" key={item.id} onClick={()=>{setSelected(item.id);setReceipt(null);setPay(null)}}><strong>{item.title}</strong><span>{item.customerName}{item.dueDate&&' / Due '+item.dueDate} / {labels[item.status]} / {jobMoney(item.balance.due,item)} {item.status==='estimate'?'quoted':item.status==='cancelled'?'balance':'due'}</span></button>)}</div>}
 {document&&createPortal(<div className="print-order thermal-document"><h2>{document.job.businessName}</h2>{document.kind!=='job'&&<p>{document.job.profile.address}{document.job.profile.phone&&' / '+document.job.profile.phone}{document.job.profile.email&&' / '+document.job.profile.email}</p>}<h1>{document.kind==='job'?'JOB TICKET':document.kind==='estimate'?'ESTIMATE':'INVOICE'}</h1><p>#{document.job.id.slice(-8).toUpperCase()} / {new Date(document.job.createdAt).toLocaleDateString()}</p><p>{document.job.customerName}{document.job.customerPhone&&' / '+document.job.customerPhone}</p><p>{document.job.title}</p>{document.job.status==='cancelled'&&<strong>CANCELLED</strong>}{document.job.dueDate&&<p>Due: {document.job.dueDate}</p>}{document.job.lines.map((line:any)=><div className="thermal-line" key={line.id}><strong>{line.description}</strong><div className="thermal-line-amount"><span>{document.kind==='job'?'Qty: '+line.quantity:line.quantity+' x '+jobMoney(line.price)}</span>{document.kind!=='job'&&<span>{jobMoney(Math.round(line.quantity*line.price*100)/100)}</span>}</div></div>)}{document.kind!=='job'&&<section><p>Subtotal: {jobMoney(document.job.pricing.subtotal)}</p>{document.job.pricing.tax>0&&<p>Tax{document.job.profile.taxIncluded?' included':''}: {jobMoney(document.job.pricing.tax)}</p>}<strong>Total: {jobMoney(document.job.pricing.total)}</strong>{document.kind==='invoice'&&<><p>Paid: {jobMoney(document.job.balance.netPaid)}</p><strong>Balance due: {jobMoney(document.job.balance.due)}</strong></>}</section>}{document.kind==='job'&&document.job.note&&<p className="receipt-multiline">{document.job.note}</p>}<footer>{document.kind==='job'?'Work instructions - not a payment receipt.':document.kind==='estimate'?'Quotation - not a payment receipt.':'Not a payment receipt.'}</footer></div>, window.document.querySelector('.app-shell') || window.document.body)}
 </section>
}
