import { WorkspaceHelp } from './WorkspaceHelp'
import { useEffect, useState } from 'react'
import type { Product } from './types'
import { posRequest } from './PosTools'
import { AsyncForm, SubmitButton } from './AsyncControls'

export function SupermarketStock({headers,products,branchId,refresh,money}:{headers:Record<string,string>;products:Product[];branchId:string;refresh:()=>Promise<void>;money:(n:number)=>string}) {
  const [data,setData]=useState<any>({records:[],batches:{lots:[],expired:[],expiring:[],costValue:0}})
  const [error,setError]=useState(''),[productId,setProductId]=useState(''),[batchId,setBatchId]=useState('')
  async function reload(){setData(await posRequest('/api/retail',headers))}
  useEffect(()=>{void reload().catch(caught=>setError(caught.message))},[branchId,headers.Authorization,products])
  const product=products.find(row=>row.id===productId),batch=data.batches.lots.find((row:any)=>row.id===batchId)
  async function save(input:any){setError('');try{await posRequest('/api/retail',headers,{id:crypto.randomUUID(),...input});await refresh();await reload()}catch(caught){setError(caught instanceof Error?caught.message:'Could not save changes.');throw caught}}
  return <section className="panel full-panel"><h2>Stock costs and expiry</h2>{error && <p role="alert">{error}</p>}<WorkspaceHelp title="Stock costs and expiry"><p>Expiry dates and batch labels are optional. Ordinary stock is tracked automatically.</p></WorkspaceHelp><p>Inventory at recorded purchase cost: <strong>{money(data.batches.costValue)}</strong>. Opening stock uses its existing catalogue cost until a delivery supplies a recorded cost.</p>
    {data.batches.expired.length>0 && <p role="alert">{data.batches.expired.length} expired batches cannot be sold. Record disposal under Purchasing and receiving: Record wastage.</p>}
    {data.batches.expiring.length>0 && <p role="status">{data.batches.expiring.length} batches expire in the next 30 days.</p>}
    <details><summary>Batch stock and expiry alerts</summary><div className="table-wrap"><table><thead><tr><th>Product</th><th>Batch</th><th>Expiry</th><th>Stock</th><th>Cost per unit</th></tr></thead><tbody>{data.batches.lots.map((row:any)=><tr key={`${row.id}:${row.branch_id}`}><td>{row.productName}</td><td>{row.batch_number||'Unlabelled'}</td><td>{row.expiry||'No expiry recorded'}</td><td>{row.quantity} {row.unit}</td><td>{money(row.unit_cost)}</td></tr>)}</tbody></table></div></details>
    <details><summary>Correct a batch label or expiry</summary><label>Batch<select aria-label="Batch" value={batchId} onChange={event=>setBatchId(event.target.value)}><option value="">Choose batch</option>{data.batches.lots.map((row:any)=><option key={row.id} value={row.id}>{row.productName} ? {row.batch_number||row.id}</option>)}</select></label>{batch && <AsyncForm key={batchId} busyLabel="Saving batch..." onSubmit={event=>{const form=new FormData(event.currentTarget);return save({kind:'batch-update',batchId,batchNumber:form.get('batchNumber'),expiry:form.get('expiry'),reason:form.get('reason')})}}><label>Batch number<input name="batchNumber" maxLength={100} defaultValue={batch.batch_number}/></label><label>Expiry date<input name="expiry" type="date" defaultValue={batch.expiry}/></label><label>Reason for correction<input name="reason" required maxLength={200}/></label><SubmitButton className="filter-button">Save batch correction</SubmitButton></AsyncForm>}</details>
    <details><summary>Change a product price, cost, or barcode</summary><label>Product<select aria-label="Pricing product" value={productId} onChange={event=>setProductId(event.target.value)}><option value="">Choose product</option>{products.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label>{product && <AsyncForm key={`${productId}:${product.updated}`} busyLabel="Saving price..." onSubmit={event=>{const form=new FormData(event.currentTarget);return save({kind:'pricing',productId,expectedUpdatedAt:product.updated,price:form.get('price'),cost:form.get('cost'),barcode:form.get('barcode'),reason:form.get('reason')})}}><label>Selling price<input name="price" type="number" min="0" step="0.01" required defaultValue={product.price}/></label><label>Cost for opening / adjusted stock<input name="cost" type="number" min="0" step="0.01" required defaultValue={product.cost||0}/></label><label>Barcode<input name="barcode" maxLength={100} defaultValue={product.barcode||''}/></label><label>Reason for change<input name="reason" required maxLength={200}/></label><SubmitButton className="filter-button">Save product changes</SubmitButton></AsyncForm>}</details>
    <details><summary>Price and batch correction history</summary>{data.records.filter((row:any)=>['pricing','batch-update'].includes(row.kind)).map((row:any)=><p key={row.id}>{new Date(row.createdAt).toLocaleString()} ? {row.staffName} ? {products.find(product=>product.id===row.productId)?.name} ? {row.kind==='pricing'?`${money(row.before.price)} ? ${money(row.price)}`:`${row.before.expiry||'No expiry'} ? ${row.expiry||'No expiry'}`} ? {row.reason}</p>)}</details>
  </section>
}
