import { useEffect,useState } from 'react'
export function SupermarketReports({headers,branchId,money,revision,oilMode=false}:{headers:Record<string,string>;branchId:string;money:(n:number)=>string;revision?:unknown;oilMode?:boolean}){
 const [data,setData]=useState<any>(null),[error,setError]=useState('')
 useEffect(()=>{let active=true;fetch('/api/reports',{headers}).then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error);if(active)setData(result)}).catch(caught=>{if(active)setError(caught.message)});return()=>{active=false}},[branchId,headers.Authorization,revision])
 if(error)return <p role="alert">{error}</p>
 if(!data?.supermarket)return null
 const report=data.supermarket
 function exportReport(){const rows=[['Metric','Value'],['Inventory at purchase cost',report.costValue],['Month net purchases',report.purchases],['Month wastage',report.wastage],['Month stock shortages',report.stockLoss],['Month cash shortages',report.cashShortage],['Month cash surplus',report.cashSurplus],['Month tax',report.tax],['Month net revenue',data.profit.revenue],['Month profit',data.profit.amount],...report.bestSellers.map((row:any)=>[row.productName,row.quantity])];const csv=rows.map(row=>row.map((value:any)=>'"'+String(value??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=oilMode?'oil-business-report.csv':'supermarket-report.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <section className="panel full-panel"><h2>{oilMode?'Oil business reports':'Supermarket reports'}</h2>{report.zeroCostSaleLines>0 && <p role="alert">{report.zeroCostSaleLines} goods lines sold this month have zero or missing cost. Check purchase costs before relying on profit.</p>}<p>Inventory at recorded purchase cost: <strong>{money(report.costValue)}</strong></p><p>This month: net purchases {money(report.purchases)} ? wastage {money(report.wastage)} ? receipt tax {money(report.tax)}</p><p>Net revenue excludes receipt tax. Profit deducts sold stock costs, running expenses, wastage, stock shortages and cash shortages; cash surplus is added. Opening stock uses the catalogue cost saved when its batch is established. A negative profit is a loss. Stock-count shortages and manual reductions are costed automatically and shown separately from wastage.</p><p>This month: stock shortages {money(report.stockLoss||0)} ? cash shortages {money(report.cashShortage||0)} ? cash surplus {money(report.cashSurplus||0)}</p><h3>Supplier balances</h3>{(report.suppliers||[]).map((row:any)=><p key={row.id}>{row.name}: {money(Math.abs(row.balance))} {row.balance<0?'credit':'owed'}</p>)}<button type="button" className="filter-button" onClick={exportReport}>{oilMode?'Export oil business report':'Export supermarket report'}</button><h3>Outstanding supplier deliveries</h3>{report.outstanding.length?report.outstanding.map((row:any)=><p key={`${row.orderId}:${row.productName}`}>{row.reference} ? {row.productName}: {row.quantity} outstanding</p>):<p>No outstanding deliveries.</p>}<h3>Best-selling products this month (after returns)</h3>{report.bestSellers.map((row:any)=><p key={row.productName}>{row.productName}: {row.quantity} units</p>)}<h3>Expired stock</h3>{report.expired.length?report.expired.map((row:any)=><p key={row.id}>{row.batch_number||row.product_id}: {row.quantity} units ? expired {row.expiry}</p>):<p>No recorded expired stock.</p>}</section>
}
