import { syncComparison } from '../server/sync-comparison.mjs'
import { AsyncButton } from './AsyncControls'
import { WorkspaceHelp } from './WorkspaceHelp'
import { useEffect, useState } from 'react'
import { AsyncForm, SubmitButton } from './AsyncControls'
export type SyncConflict = { id: string; entityType: string; entityId: string; reason: string; createdAt: string; localPayload?: string; remotePayload?: string; reviewNote?: string; reviewAction?: string; reviewerId?: string; resolvedAt?: string }
export function SyncIssues({ conflicts, resolveConflict, navigate, headers }: { conflicts: SyncConflict[]; resolveConflict: (id: string, input: {action:string;note:string;confirmed:boolean}) => Promise<void>; navigate: (screen:string) => void; headers: Record<string,string> }) {
  const [selected,setSelected]=useState('')
  const [reviews,setReviews]=useState<SyncConflict[]>([])
  const [historyError,setHistoryError]=useState('')
  useEffect(()=>{let active=true;fetch('/api/sync/conflicts/reviews',{headers}).then(async response=>{if(!response.ok)throw new Error('Could not load review history.');return response.json()}).then(result=>{if(active){setReviews(result.conflicts);setHistoryError('')}}).catch(error=>{if(active)setHistoryError(error.message)});return()=>{active=false}},[conflicts,headers.Authorization])
  const current=conflicts.find(row=>row.id===selected)
  const comparison=current?syncComparison(current.localPayload,current.remotePayload):null
  const title=(type:string)=>({settings:'Business settings',product:'Product',customer:'Customer',sale:'Sale',pos_record:'Business record',branch:'Branch'}[type]||'Business record')
  return <section className="panel full-panel"><h2>Sync issues</h2><WorkspaceHelp><p>Review the changed business details. Recording an outcome keeps an audit history and does not change money or stock.</p></WorkspaceHelp>
    {conflicts.length ? <ul>{conflicts.map(row=><li key={row.id}><button className="filter-button" onClick={()=>setSelected(row.id)}>{title(row.entityType)} - {new Date(row.createdAt).toLocaleDateString()}</button><p>{row.reason}</p></li>)}</ul> : <p>No open sync issues.</p>}
    {current && <article key={current.id}><h3>{title(current.entityType)}</h3><p>{current.reason}</p>{comparison?.available ? comparison.matching ? <p role="status">Both versions contain the same business details. Only synchronization information may differ.</p> : <div className="table-wrap"><table><thead><tr><th>Changed setting or detail</th><th>This device</th><th>Cloud record</th></tr></thead><tbody>{comparison.rows.map((row,index)=><tr key={index}><th scope="row">{row.label}</th><td>{row.localLogo?<img className="sync-logo-preview" src={row.localLogo} alt="Logo on this device"/>:row.local}</td><td>{row.remoteLogo?<img className="sync-logo-preview" src={row.remoteLogo} alt="Logo in cloud record"/>:row.remote}</td></tr>)}</tbody></table></div> : <p>Saved comparison details are unavailable. Open the affected records or contact support.</p>}
      {current.entityType==='settings' && comparison?.matching && <AsyncButton className="primary-button" onClick={async()=>{await resolveConflict(current.id,{action:'accepted',confirmed:true,note:'Compared both settings snapshots. All business details match; only synchronization metadata differs.'});setSelected('')}}>Confirm matching settings</AsyncButton>}
      <WorkspaceHelp><p>Check the current records before accepting differences. Correct stock through Stock count and payments through Sales history.</p></WorkspaceHelp>
      <div className="form-grid">{(current.entityType==='settings'?[['Settings','Open Business settings']]:[['Stocktake','Open Stock count'],['Sales','Open Sales history'],['Inventory','Open Inventory'],['Payments','Open Payments & receipts'],['Settings','Open Business settings']]).map(([screen,label])=><button key={screen} className="filter-button" onClick={()=>navigate(screen)}>{label}</button>)}</div>
      {!(current.entityType==='settings' && comparison?.matching) && <AsyncForm busyLabel="Recording outcome..." onSubmit={async event=>{const form=new FormData(event.currentTarget);await resolveConflict(current.id,{action:String(form.get('action')),note:String(form.get('note')),confirmed:form.get('confirmed')==='on'});setSelected('')}}><label>Outcome<select name="action"><option value="corrected">I corrected the affected records using their normal tools</option><option value="accepted">I checked and accept the current records</option></select></label><label>What you checked or corrected<textarea name="note" required minLength={10} maxLength={1000} placeholder="Include the receipt, stock count or corrected record reference." /></label><label><input type="checkbox" name="confirmed" required />I checked the current records and any money or stock difference.</label><SubmitButton className="primary-button">Record review outcome</SubmitButton></AsyncForm>}
    </article>}
    <details><summary>Recorded review outcomes</summary>{historyError&&<p role="alert">{historyError}</p>}{reviews.map(row=><p key={row.id}><strong>{title(row.entityType)}</strong> / {row.reviewAction==='corrected'?'Records corrected':'Current records accepted'} / {row.resolvedAt?new Date(row.resolvedAt).toLocaleString():'Review recorded'}<br/>{row.reviewNote}</p>)}{!reviews.length&&!historyError&&<p>No recorded review outcomes.</p>}</details>
  </section>
}
