import { SupportContacts } from './SupportContacts'
import { useRef, useState } from 'react'
import { BookOpen, Download, Search } from 'lucide-react'
import chapters from './user-guide.json'

export function UserGuide({role,headers,scope,openScreen,canOpenScreen}:{role:string;headers?:Record<string,string>;scope?:string;openScreen?:(screen:string)=>void;canOpenScreen?:(screen:string)=>boolean}) {
 const visible=chapters.filter(chapter=>role==='owner'||chapter.id!=='section-33')
 const [query,setQuery]=useState(''),[topic,setTopic]=useState(visible[0].id)
 const heading=useRef<HTMLHeadingElement>(null)
 const matches=visible.filter(chapter=>[chapter.title,...chapter.steps,chapter.note].join(' ').toLowerCase().includes(query.trim().toLowerCase()))
 const current=matches.find(chapter=>chapter.id===topic)||matches[0],index=matches.findIndex(chapter=>chapter.id===current?.id)
 function select(id:string){setTopic(id);requestAnimationFrame(()=>{heading.current?.focus();heading.current?.scrollIntoView({block:'start'})})}
 function download(){const text=visible.map(chapter=>chapter.title+'\n\n'+chapter.steps.map((step,index)=>(index+1)+'. '+step).join('\n')+'\n\nRemember: '+chapter.note).join('\n\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='Stockroom-user-guide.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const screen=current&&[/staff|cashier/i.test(current.title)?'Team':null,/subscription/i.test(current.title)?'Subscription':null,/report|profit/i.test(current.title)?'Reports':null,/stock count/i.test(current.title)?'Stocktake':null,/inventory|catalogue/i.test(current.title)?'Inventory':null,/customer|wallet/i.test(current.title)?'Wallet':null,/printer|device/i.test(current.title)?'Device':null,/settings|workspace|timezone/i.test(current.title)?'Settings':null].find(Boolean)
 return <section className="user-guide"><div className="panel guide-header"><h2><BookOpen size={22} aria-hidden="true"/> How to use Stockroom</h2><p>Choose a topic or follow the guide with Next topic. Tools shown in the app depend on your workspace and staff access.</p><label className="guide-search"><Search size={18} aria-hidden="true"/><span className="sr-only">Search guide</span><input type="search" placeholder="Search: staff access, receipt, stock…" value={query} onChange={event=>setQuery(event.target.value)}/></label><button type="button" className="filter-button" onClick={download}><Download size={17} aria-hidden="true"/> Download full guide</button></div><div className="guide-layout"><nav className="guide-contents panel" aria-label="Guide topics"><h3>Topics</h3>{matches.map(chapter=><button type="button" key={chapter.id} aria-current={current?.id===chapter.id?'page':undefined} onClick={()=>select(chapter.id)}>{chapter.title}</button>)}</nav>{current?<article className="panel guide-chapter"><p className="guide-progress">Topic {index+1} of {matches.length}{query.trim()?' matching your search':''}</p><h2 tabIndex={-1} ref={heading}>{current.title}</h2>{screen&&openScreen&&(!canOpenScreen||canOpenScreen(screen))&&<button type="button" className="filter-button" onClick={()=>openScreen(screen)}>Open related screen →</button>}<ol>{current.steps.map((step,index)=><li key={index}>{step}</li>)}</ol>{current.id==='section-31'&&<figure className="guide-example"><img src="/guide/staff-access.png" alt="Example staff access with separate checkboxes for selling, inventory, customers and reports" loading="lazy"/><figcaption>Example: open Choose staff access in the staff table’s Access column. Tick only the operations this person needs, then Save staff access and confirm your owner password.</figcaption></figure>}{current.note&&<aside className="guide-note"><strong>Remember</strong><p>{current.note}</p></aside>}<nav className="guide-pagination" aria-label="Read guide topics"><button type="button" className="filter-button" disabled={index<=0} onClick={()=>select(matches[index-1].id)}>← Previous topic</button><button type="button" className="primary-button" disabled={index>=matches.length-1} onClick={()=>select(matches[index+1].id)}>Next topic →</button></nav></article>:<p role="status">No matching topics. Try a shorter search.</p>}</div><SupportContacts headers={headers} scope={scope}/></section>
}
