import { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowLeft, Copy, LogOut, Menu, Share2, WalletCards } from 'lucide-react'
import { moneyMinor, portalRequest, visitorPortalKeys } from './lib/portalApi'
import { isBrowserPwa } from './lib/platform'
import { NotificationCenter } from './NotificationCenter'
import './portal.css'

type Balance = { currency: string; earnedMinor: number; paidMinor: number; pendingMinor: number; availableMinor: number }
type Commission = { reference: string; amountMinor: number; currency: string; percent: number; kind: string; createdAt: string }
type Payout = { id: string; amountMinor: number; currency: string; status: string; method: string; createdAt: string; paidAt: string | null; automaticError: string }
type Wallet = { referrer: { name: string; email: string; type: string }; link: string; referredBusinesses: number; automaticTransfersEnabled: boolean; balances: Balance[]; profiles: Array<{ currency: string; name: string; bankName: string; accountLast4: string; automaticReady: boolean }>; commissions: Commission[]; payouts: Payout[] }
type DeletionStatus = { status: 'active' | 'pending'; scheduledFor?: string; graceDays?: number }
const currencies = ['NGN', 'GHS', 'ZAR', 'KES', 'USD', 'XOF']
const bankCurrencies = ['NGN', 'GHS', 'ZAR', 'KES', 'USD']

function VisitorPortal() {
  const [wallet, setWallet] = useState<Wallet | null>(null)
  const [deletion, setDeletion] = useState<DeletionStatus | null>(null)
  const [registering, setRegistering] = useState(true)
  const [tab, setTab] = useState<'promote' | 'wallet'>('promote')
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState('')
  const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false); const [currency, setCurrency] = useState('NGN'); const [amount, setAmount] = useState(''); const [payoutNote, setPayoutNote] = useState('')
  const [banks, setBanks] = useState<Array<{name: string; code: string}>>([])
  const signedIn = Boolean(wallet || deletion?.status === 'pending')
  const load = async () => { const data = await portalRequest<Wallet>('/v1/referral-wallet/me', {}, visitorPortalKeys); setWallet(data); setEmail(data.referrer.email); setError('') }
  const loadDeletion = async () => { const data = await portalRequest<DeletionStatus>('/v1/account-deletion/me', {}, visitorPortalKeys); setDeletion(data); if (data.status === 'active') await load() }
  useEffect(() => { const token = localStorage.getItem(visitorPortalKeys.access) || sessionStorage.getItem(visitorPortalKeys.session); if (token) void loadDeletion().catch(() => { localStorage.removeItem(visitorPortalKeys.access); sessionStorage.removeItem(visitorPortalKeys.session) }) }, [])
  useEffect(() => { if (!wallet?.automaticTransfersEnabled || !bankCurrencies.includes(currency)) return; let cancelled = false; void portalRequest<{banks: Array<{name: string; code: string}>}>(`/v1/referral-wallet/banks?currency=${currency}`, {}, visitorPortalKeys).then(result => { if (!cancelled) setBanks(result.banks) }).catch(caught => { if (!cancelled) setError(caught instanceof Error ? caught.message : 'Paystack bank list is unavailable.') }); return () => { cancelled = true } }, [wallet?.automaticTransfersEnabled, currency])
  const submitAuth = async (event: React.FormEvent) => {
    event.preventDefault(); setBusy(true); setError(''); setMessage('')
    try {
      const response = await fetch(`${__STOCKROOM_SYNC_API_URL__.replace(/\/$/, '')}/v1/visitors/${registering ? 'register' : 'login'}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, email, password }) })
      const data = await response.json().catch(() => ({}))
      if (!response.ok) throw new Error(data.error || 'Could not open your promoter account.')
      localStorage.setItem(visitorPortalKeys.access, data.accessToken); sessionStorage.setItem(visitorPortalKeys.session, data.accessToken)
      setPassword(''); await loadDeletion()
    } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not sign in.') }
    finally { setBusy(false) }
  }
  const copyLink = async () => {
    if (!wallet?.link) return
    try { await navigator.clipboard.writeText(wallet.link); setMessage('Your referral link is copied and ready to share.') }
    catch { const input = document.getElementById('visitor-share-link') as HTMLInputElement | null; input?.focus(); input?.select(); setMessage('The link is selected. Copy it and share it with a business owner.') }
  }
  const requestPayout = async (event: React.FormEvent) => {
    event.preventDefault(); setError(''); setMessage(''); setBusy(true)
    try { const amountMinor = Math.round(Number(amount) * 100); const result = await portalRequest<{message: string}>('/v1/referral-wallet/payouts', { method: 'POST', body: JSON.stringify({ currency, amountMinor, note: payoutNote }) }, visitorPortalKeys); setMessage(result.message); setAmount(''); await load() }
    catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not request a payout.') }
    finally { setBusy(false) }
  }
  const saveBank = async (event: React.FormEvent) => {
    event.preventDefault(); setError(''); setMessage(''); setBusy(true)
    try { const form = new FormData(event.currentTarget as HTMLFormElement); const result = await portalRequest<{profile: {bankName: string; accountLast4: string}}>('/v1/referral-wallet/profile', { method: 'POST', body: JSON.stringify(Object.fromEntries(form)) }, visitorPortalKeys); setMessage(`Paystack payout destination saved${result.profile.bankName ? `: ${result.profile.bankName}` : ''} ending ${result.profile.accountLast4}.`); await load() }
    catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not save payout destination.') }
    finally { setBusy(false) }
  }
  const loadBanks = (selected: string) => { setCurrency(selected); setBanks([]) }
  const logout = () => { localStorage.removeItem(visitorPortalKeys.access); sessionStorage.removeItem(visitorPortalKeys.session); setWallet(null); setMessage('You have signed out.') }
  const changeDeletion = async (action: 'request' | 'cancel') => {
    setBusy(true); setError(''); setMessage('')
    try {
      const result = await portalRequest<DeletionStatus>('/v1/account-deletion/me', { method: 'POST', body: JSON.stringify({ action, confirmation: 'DELETE' }) }, visitorPortalKeys)
      setDeletion(result)
      if (result.status === 'active') await load()
      else setWallet(null)
    } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not update account deletion request.') }
    finally { setBusy(false) }
  }
  const available = wallet?.balances.find(row => row.currency === currency)?.availableMinor || 0
  if (!wallet && deletion?.status === 'pending') return <main className="portal-login"><section className="portal-login-card"><a className="portal-brand" href="/welcome"><img src="/logo.png" alt="" /><span><strong>Stockroom Promoter Wallet</strong><small>Account deletion request</small></span></a><h1>Your account is deactivated</h1><p>Your account and personal profile are scheduled for deletion on <strong>{deletion.scheduledFor ? new Date(deletion.scheduledFor).toLocaleString() : 'the scheduled date'}</strong>, after a {deletion.graceDays}-day protection period. You can cancel before then to restore access.</p>{error && <div className="portal-alert error" role="alert">{error}</div>}<button className="portal-btn secondary" disabled={busy} onClick={() => void changeDeletion('cancel')}>{busy ? 'Please wait…' : 'Cancel deletion and restore my account'}</button><button className="portal-btn secondary" style={{marginTop:12}} onClick={logout}>Sign out</button></section></main>
  if (!signedIn) return <main className="portal-login"><section className="portal-login-card"><a className="portal-brand" href="/welcome"><img src="/logo.png" alt="" /><span><strong>Stockroom Promoter Wallet</strong><small>S. B. Ibhadode Technologies</small></span></a><h1>{registering ? 'Become a Stockroom promoter' : 'Sign in to your promoter account'}</h1><p>Share a tracked Stockroom link, see the businesses that register, and follow verified referral rewards in your wallet.</p>{error && <div className="portal-alert error" role="alert">{error}</div>}<form className="portal-form" onSubmit={submitAuth}>{registering && <label>Your name<input autoComplete="name" required maxLength={100} value={name} onChange={event => setName(event.target.value)} /></label>}<label>Email<input type="email" autoComplete="email" required value={email} onChange={event => setEmail(event.target.value)} /></label><label>Password<input type="password" autoComplete={registering ? 'new-password' : 'current-password'} minLength={10} maxLength={256} required value={password} onChange={event => setPassword(event.target.value)} /></label><button className="portal-btn" disabled={busy}>{busy ? 'Please wait…' : registering ? 'Create promoter account' : 'Sign in'}</button></form><button className="portal-btn secondary" style={{marginTop:12}} onClick={() => { setRegistering(!registering); setError('') }}>{registering ? 'I already have a promoter account' : 'Create a new promoter account'}</button><p><a className="portal-link" href="/welcome">Back to Stockroom welcome page</a></p><p><a className="portal-link" href="privacy.html">Privacy Policy</a> | <a className="portal-link" href="terms.html">Terms and Conditions</a></p></section></main>
  return <div className="portal"><aside className={`portal-sidebar${menuOpen ? ' open' : ''}`}><a className="portal-brand" href="/welcome"><img src="/logo.png" alt="" /><span><strong>Stockroom</strong><small>Promoter account</small></span></a><nav className="portal-nav"><button className={tab === 'promote' ? 'active' : ''} onClick={() => { setTab('promote'); setMenuOpen(false) }}><Share2 size={17} />My referral link</button><button className={tab === 'wallet' ? 'active' : ''} onClick={() => { setTab('wallet'); setMenuOpen(false) }}><WalletCards size={17} />Wallet & payouts</button><a href="/welcome"><ArrowLeft size={17} />Stockroom welcome page</a></nav><div className="portal-sidebar-foot">{wallet?.referrer.name}<br />{wallet?.referrer.email}</div></aside><main className="portal-main"><header className="portal-top"><div className="portal-actions"><button className="portal-btn secondary portal-mobile-menu" onClick={() => setMenuOpen(!menuOpen)}><Menu size={16} /></button><div><h1>{tab === 'promote' ? 'My referral link' : 'Wallet & payouts'}</h1><p>Stockroom visitor promoter account</p></div></div><NotificationCenter apiUrl={__STOCKROOM_SYNC_API_URL__.replace(/\/$/, "")} token="" onToken={() => {}} allowPush={isBrowserPwa()} request={(path, init) => portalRequest(path, init || {}, visitorPortalKeys)} /><button className="portal-btn secondary" onClick={logout}><LogOut size={15} />Sign out</button></header><div className="portal-content">{error && <div className="portal-alert error" role="alert">{error}</div>}{message && <div className="portal-alert success" role="status">{message}</div>}
    {tab === 'promote' && <><div className="portal-heading"><div><h2>Help Stockroom reach more businesses</h2><p>Share your personal link. Referral credit is confirmed when the business redeems its registration key.</p></div></div><div className="portal-grid"><Metric title="Businesses registered from your link" value={wallet?.referredBusinesses || 0} detail="Key redeemed and attribution saved" /><Metric title="Available reward currencies" value={wallet?.balances.length || 0} detail="A separate balance is kept for each currency" /><Metric title="Automatic payout" value={wallet?.automaticTransfersEnabled ? 'Setup available' : 'Manual'} detail="Automatic needs Paystack and a saved bank destination" /><Metric title="Verified rewards" value={wallet?.commissions.length || 0} detail="Successful subscription payments" /></div><div className="portal-panel"><h3>Your tracked referral link</h3><p>Businesses can use this link to start registration. Tell them to keep the referral code through the key redemption step.</p><div className="portal-actions"><input id="visitor-share-link" className="portal-input" readOnly value={wallet?.link || ''} onFocus={event => event.currentTarget.select()} /><button className="portal-btn" onClick={() => void copyLink()}><Copy size={15} />Copy link</button></div></div><div className="portal-panel"><h3>How rewards are earned</h3><p>Only verified successful subscription payments earn a reward. Account creation and link clicks do not create a balance. The developer sets the visitor first-payment and renewal rates; each referred business can earn on up to four successful payments.</p></div></>}
    {tab === 'wallet' && <><div className="portal-heading"><div><h2>Your referral wallet</h2><p>Rewards are shown separately for each currency. Pending payouts are reserved until payment is confirmed.</p></div><button className="portal-btn secondary" onClick={() => void load()}>Refresh wallet</button></div>{!wallet?.balances.length ? <div className="portal-empty">No verified rewards have reached your wallet yet.</div> : <div className="portal-balance-row">{wallet.balances.map(row => <article className="portal-balance" key={row.currency}><span>{row.currency} wallet</span><strong className="available">{moneyMinor(row.availableMinor, row.currency)}</strong><small>Available</small><small>Earned {moneyMinor(row.earnedMinor, row.currency)}</small><small>Paid {moneyMinor(row.paidMinor, row.currency)} · Pending {moneyMinor(row.pendingMinor, row.currency)}</small></article>)}</div>}
      <div className="portal-panel"><h3>Request a payout</h3><p>{wallet?.automaticTransfersEnabled ? 'If your Paystack destination is ready, Stockroom will start an automatic transfer. If Paystack is unavailable or rejects it, your request will be queued for manual payment.' : 'Automatic transfers are not enabled yet. Your request will be queued for manual payment.'}</p><form className="portal-form" onSubmit={requestPayout}><label>Currency<select value={currency} onChange={event => void loadBanks(event.target.value)}>{(wallet?.balances || []).map(row => <option key={row.currency} value={row.currency}>{row.currency} · available {moneyMinor(row.availableMinor, row.currency)}</option>)}{!wallet?.balances.length && currencies.map(code => <option key={code}>{code}</option>)}</select></label><label>Amount<input type="number" min="0.01" step="0.01" max={available / 100} required value={amount} onChange={event => setAmount(event.target.value)} placeholder="0.00" /></label><label>Note for the developer (optional)<input maxLength={300} value={payoutNote} onChange={event => setPayoutNote(event.target.value)} placeholder="Preferred contact or payout detail" /></label><button className="portal-btn" disabled={busy || Number(amount) * 100 > available}>{busy ? 'Submitting…' : 'Request payout'}</button></form></div>
      {wallet?.automaticTransfersEnabled && <div className="portal-panel"><h3>Automatic payout destination</h3><p>Stockroom sends bank details to Paystack to create a transfer recipient. It keeps the recipient code and last four account digits; it does not store your full account number.</p><form className="portal-form" onSubmit={saveBank}><label>Currency<select name="currency" value={bankCurrencies.includes(currency) ? currency : 'NGN'} onChange={event => void loadBanks(event.target.value)}>{bankCurrencies.map(code => <option key={code}>{code}</option>)}</select></label><label>Account holder name<input name="name" required maxLength={100} /></label><label>Bank<select name="bankCode" required>{banks.length ? <><option value="">Select your bank</option>{banks.map(bank => <option key={bank.code} value={bank.code}>{bank.name}</option>)}</> : <option value="">Choose a supported currency to load banks</option>}</select></label><label>Account number<input name="accountNumber" inputMode="numeric" autoComplete="off" minLength={6} maxLength={20} pattern="[0-9]{6,20}" required /></label><button className="portal-btn" disabled={busy}>{busy ? 'Saving destination…' : 'Save Paystack destination'}</button></form>{wallet.profiles.map(profile => <div className="portal-alert success" key={profile.currency}>{profile.currency}: {profile.bankName || 'Bank account'} ending {profile.accountLast4} · {profile.automaticReady ? 'Ready' : 'Not ready'}</div>)}</div>}
      <div className="portal-panel"><h3>Reward history</h3><Records rows={wallet?.commissions || []} /></div><div className="portal-panel"><h3>Payout history</h3><PayoutHistory rows={wallet?.payouts || []} /></div>
    </>}
    <div className="portal-panel"><h3>Close promoter account</h3><p>Deactivation is immediate. Your personal account details are scheduled for deletion after the developer-configured {deletion?.graceDays || 90}-day waiting period; paid payout records may be retained for financial and legal record keeping.</p><button className="portal-btn secondary" disabled={busy || deletion?.status === 'pending'} onClick={() => { if (window.confirm('Deactivate your promoter account now and schedule its deletion? You can cancel during the waiting period.')) void changeDeletion('request') }}>{busy ? 'Submitting…' : 'Deactivate and schedule deletion'}</button></div>
  </div></main></div>
}
function Metric({ title, value, detail }: { title: string; value: number | string; detail: string }) { return <article className="portal-card"><span>{title}</span><strong>{value}</strong><small>{detail}</small></article> }
function Records({ rows }: { rows: Commission[] }) { return <div className="portal-table-wrap"><table><thead><tr><th>Payment</th><th>Reward</th><th>Rate</th><th>Earned</th></tr></thead><tbody>{rows.map(row => <tr key={row.reference}><td>{row.kind === 'first' ? 'First payment' : 'Renewal'}<small>{row.reference}</small></td><td>{moneyMinor(row.amountMinor, row.currency)}</td><td>{row.percent}%</td><td>{new Date(row.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table>{!rows.length && <div className="portal-empty">No verified referral rewards yet.</div>}</div> }
function PayoutHistory({ rows }: { rows: Payout[] }) { return <div className="portal-table-wrap"><table><thead><tr><th>Amount</th><th>Status</th><th>Method</th><th>Requested</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td>{moneyMinor(row.amountMinor, row.currency)}</td><td>{row.status}{row.automaticError && <small>{row.automaticError}</small>}</td><td>{row.method || '—'}</td><td>{new Date(row.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table>{!rows.length && <div className="portal-empty">No payout requests yet.</div>}</div> }

createRoot(document.getElementById('root')!).render(<VisitorPortal />)
