import { ShoppingCart, ReceiptText, Utensils, Armchair } from 'lucide-react'
import { WorkspaceHelp } from './WorkspaceHelp'
import { useEffect, useState } from 'react'
import { posRequest } from './PosTools'
import { restaurantBillLines } from '../server/restaurant-payments.mjs'
import type { Sale } from './types'
type Workspace={stock:boolean;payments:boolean;fastFood:boolean;restaurant:boolean}
export function WorkspaceOverview({workspace,headers,receipts,money,open}:{workspace:Workspace;headers:Record<string,string>;receipts:Sale[];money:(n:number)=>string;open:(screen:'POS'|'Payments'|'Counter'|'Restaurant')=>void}) {
 const [orders,setOrders]=useState<any[]>([]),[restaurant,setRestaurant]=useState<any>(null),[error,setError]=useState('')
 useEffect(()=>{let live=true;async function load(){const requests=[...(workspace.fastFood?[posRequest('/api/pos/counter',headers).then(data=>{if(live)setOrders(data.orders)})]:[]),...(workspace.restaurant?[posRequest('/api/pos/restaurant',headers).then(data=>{if(live)setRestaurant(data)})]:[])];const results=await Promise.allSettled(requests);if(live)setError(results.some(result=>result.status==='rejected')?'Some live order totals could not load. You can still open the payment screens.':'')}void load();window.addEventListener('stockroom-data-refreshed',load);const timer=setInterval(load,10000);return()=>{live=false;clearInterval(timer);window.removeEventListener('stockroom-data-refreshed',load)}},[headers.Authorization,headers['X-Stockroom-Branch'],workspace.fastFood,workspace.restaurant])
 const enabled=[...(workspace.stock?[{screen:'POS' as const,name:'Product sales',icon:ShoppingCart,examples:'For supermarkets, mini-marts and retail shops.',action:'Start a sale',description:'Choose or scan products, take payment and print a receipt.'}]:[]),...(workspace.payments?[{screen:'Payments' as const,name:'Payments & receipts',icon:ReceiptText,examples:'For printing presses, church offices and service businesses.',action:'Record a payment',description:'Enter what was paid for, quantities and amounts, then issue a receipt.'}]:[]),...(workspace.fastFood?[{screen:'Counter' as const,name:'Order counter',icon:Utensils,examples:'For fast food, cafes and takeaway shops.',action:'Take a new order',description:'Choose menu items, send the order and collect payment.'}]:[]),...(workspace.restaurant?[{screen:'Restaurant' as const,name:'Tables & tabs',icon:Armchair,examples:'For restaurants, bars and lounges.',action:'Open tables and tabs',description:'Choose a table or bar tab, add orders and settle its bill.'}]:[])]
 const kind=(sale:Sale)=>sale.paymentDetails?.restaurantBill||sale.paymentDetails?.counterOrder?.tableService?'Restaurant':sale.paymentDetails?.counterOrder?'Counter':sale.paymentDetails?.servicePayment?'Payments':'POS'
 const today=new Date().toDateString()
 const bills=(restaurant?.tabs||[]).filter((tab:any)=>tab.status==='open'&&!tab.mergedInto)
 return <section className="workspace-overview" aria-label="Daily work"><div className="hero-row"><div><h2>Start today's work</h2><WorkspaceHelp><p>Choose a workspace to start a transaction. Configuration is in Business settings; past receipts are in History.</p></WorkspaceHelp></div></div><div className="workspace-launch-grid">{enabled.map(item=>{const saved=receipts.filter(sale=>kind(sale)===item.screen&&new Date(sale.createdAt).toDateString()===today);return <section className={`panel workspace-launch workspace-accent-${item.screen}`} key={item.screen}><div className="workspace-card-heading"><span className="workspace-icon"><item.icon size={25} aria-hidden="true" /></span><h3>{item.name}</h3></div><p>{item.examples}</p><WorkspaceHelp><p>{item.description}</p></WorkspaceHelp><div className="workspace-card-total"><span>Received today</span><strong>{money(saved.reduce((sum,sale)=>sum+sale.total,0))}</strong><small>{saved.length} receipts</small></div>{item.screen==='Counter'&&<p>{orders.filter(order=>!['collected','cancelled'].includes(order.status)).length} active orders / {orders.filter(order=>order.status!=='cancelled'&&!order.receiptId).length} awaiting payment</p>}{item.screen==='Restaurant'&&<p>{bills.length} open bills / {money(bills.reduce((sum:number,tab:any)=>sum+restaurantBillLines(tab,restaurant.orders,restaurant.receipts).reduce((n:number,line:any)=>n+line.remainingAmount,0),0))} awaiting payment</p>}<button type="button" className="primary-button" onClick={()=>open(item.screen)}>{item.action}</button></section>})}</div>{error&&<p role="status">{error}</p>}</section>
}
