import { useEffect, useState } from 'react'
import { posRequest } from './PosTools'
import { restaurantBillLines } from '../server/restaurant-payments.mjs'
import type { Sale } from './types'
type Workspace={stock:boolean;payments:boolean;fastFood:boolean;restaurant:boolean}
export function WorkspaceOverview({workspace,headers,receipts,money,open}:{workspace:Workspace;headers:Record<string,string>;receipts:Sale[];money:(n:number)=>string;open:(screen:'POS'|'Payments'|'Counter'|'Restaurant')=>void}) {
 const [orders,setOrders]=useState<any[]>([]),[restaurant,setRestaurant]=useState<any>(null),[error,setError]=useState('')
 useEffect(()=>{let live=true;async function load(){const requests=[...(workspace.fastFood?[posRequest('/api/pos/counter',headers).then(data=>{if(live)setOrders(data.orders)})]:[]),...(workspace.restaurant?[posRequest('/api/pos/restaurant',headers).then(data=>{if(live)setRestaurant(data)})]:[])];const results=await Promise.allSettled(requests);if(live)setError(results.some(result=>result.status==='rejected')?'Some live order totals could not load. You can still open the payment screens.':'')}void load();const timer=setInterval(load,10000);return()=>{live=false;clearInterval(timer)}},[headers.Authorization,headers['X-Stockroom-Branch'],workspace.fastFood,workspace.restaurant])
 const enabled=[...(workspace.stock?[{screen:'POS' as const,name:'Stock & checkout',action:'Start a sale',description:'Choose or scan products, take payment and print a receipt.'}]:[]),...(workspace.payments?[{screen:'Payments' as const,name:'Payments & receipts',action:'Record a payment',description:'Enter what was paid for, quantities and amounts, then issue a receipt.'}]:[]),...(workspace.fastFood?[{screen:'Counter' as const,name:'Fast food',action:'Take a new order',description:'Choose food and drinks, send the order and collect payment.'}]:[]),...(workspace.restaurant?[{screen:'Restaurant' as const,name:'Restaurant & bar',action:'Open tables and tabs',description:'Choose a table or bar tab, add orders and settle its bill.'}]:[])]
 const kind=(sale:Sale)=>sale.paymentDetails?.restaurantBill||sale.paymentDetails?.counterOrder?.tableService?'Restaurant':sale.paymentDetails?.counterOrder?'Counter':sale.paymentDetails?.servicePayment?'Payments':'POS'
 const today=new Date().toDateString()
 const bills=(restaurant?.tabs||[]).filter((tab:any)=>tab.status==='open'&&!tab.mergedInto)
 return <section className="workspace-overview" aria-label="Daily work"><div className="hero-row"><div><h2>Start today's work</h2><p>Choose a payment screen below. Setup and past records have their own controls.</p></div></div><div className="workspace-launch-grid">{enabled.map(item=>{const saved=receipts.filter(sale=>kind(sale)===item.screen&&new Date(sale.createdAt).toDateString()===today);return <section className="panel workspace-launch" key={item.screen}><h3>{item.name}</h3><p>{item.description}</p><p><strong>{money(saved.reduce((sum,sale)=>sum+sale.total,0))}</strong> received today / {saved.length} receipts</p>{item.screen==='Counter'&&<p>{orders.filter(order=>!['collected','cancelled'].includes(order.status)).length} active orders / {orders.filter(order=>order.status!=='cancelled'&&!order.receiptId).length} awaiting payment</p>}{item.screen==='Restaurant'&&<p>{bills.length} open bills / {money(bills.reduce((sum:number,tab:any)=>sum+restaurantBillLines(tab,restaurant.orders,restaurant.receipts).reduce((n:number,line:any)=>n+line.remainingAmount,0),0))} awaiting payment</p>}<button type="button" className="primary-button" onClick={()=>open(item.screen)}>{item.action}</button></section>})}</div>{error&&<p role="status">{error}</p>}</section>
}
